### ISSUE TITLE
Failed to ./waf after enabling PyViz with Pybindgen

### ISSUE THREAD

**Issue by paraparata** [nyuwireless-unipd/ns3-mmwave#100]
I try to visualizing mc-twoenb.cc with enabling Pybindgen and PyViz when running ./waf configure and it works. But when I try to ./waf it got me an error

`from ./ns3/object.h:29,                                       [36/1919]
                 from ./ns3/simulator-impl.h:27,                                        
                 from ../src/visualizer/model/visual-simulator-impl.h:24,               
                 from ../src/visualizer/model/visual-simulator-impl.cc:21:              
./ns3/type-id.h: In instantiation of ‘static ns3::ObjectBase* ns3::TypeId::AddConstructo
r()::Maker::Create() [with T = ns3::VisualSimulatorImpl]’:                              
./ns3/type-id.h:659:3:   required from ‘ns3::TypeId ns3::TypeId::AddConstructor() [with 
T = ns3::VisualSimulatorImpl]’                                                          
../src/visualizer/model/visual-simulator-impl.cc:50:43:   required from here            
./ns3/type-id.h:656:27: error: invalid new-expression of abstract class type ‘ns3::Visua
lSimulatorImpl’                                                                         
       ObjectBase * base = new T ();                                                    
                           ^~~~~~~~                                                     
In file included from ../src/visualizer/model/visual-simulator-impl.cc:21:0:            
../src/visualizer/model/visual-simulator-impl.h:44:7: note:   because the following virt
ual functions are pure within ‘ns3::VisualSimulatorImpl’:                               
 class VisualSimulatorImpl : public SimulatorImpl                                       
       ^~~~~~~~~~~~~~~~~~~                                                              
In file included from ../src/visualizer/model/visual-simulator-impl.h:24:0,             
                 from ../src/visualizer/model/visual-simulator-impl.cc:21:              
./ns3/simulator-impl.h:103:20: note:    virtual uint64_t ns3::SimulatorImpl::GetEventCou
nt() const                                                          `

Does anybody know how to solve it? Thx for ur time to look at this question.

**Comment by tommasozugno** [comment]
Hi,
Did you clone the new-handover branch?

**Comment by paraparata** [comment]
yaps, I use new-handover branch and the pybindgen from https://github.com/gjcarneiro/pybindgen link that mentioned in wscript file under bindings/python/ folder.
I also had python install setup.py the pybindgen folder

**Comment by tommasozugno** [comment]
Please check if the you correctly installed all the dependencies, when you run ./waf configure you should see Python Bindings : enabled and Python API Scan Support : enabled. Is it the case?

**Comment by paraparata** [comment]
Yes, the status alreadt enabled : 

`PyViz visualizer              : enabled
Python API Scanning Support   : enabled
Python Bindings               : enabled
Real Time Simulator           : enabled
SQlite stats data output      : enabled
Tap Bridge                    : enabled
Tap FdNetDevice               : enabled
Tests                         : not enabled (defaults to disabled)
Threading Primitives          : enabled
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
XmlIo                         : enabled
'configure' finished successfully (5.961s)
`

The problem comes after ./waf like I mentioned before : 

`In file included from ./ns3/object-base.h:23:0,                                                                               [112/1966]
                 from ./ns3/object.h:29,                                                                                                
                 from ./ns3/simulator-impl.h:27,                                                                                        
                 from ../src/visualizer/model/visual-simulator-impl.h:24,                                                               
                 from ../src/visualizer/model/visual-simulator-impl.cc:21:                                                              
./ns3/type-id.h: In instantiation of ‘static ns3::ObjectBase* ns3::TypeId::AddConstructor()::Maker::Create() [with T = ns3::VisualSimul$
torImpl]’:                                                                                                                              
./ns3/type-id.h:659:3:   required from ‘ns3::TypeId ns3::TypeId::AddConstructor() [with T = ns3::VisualSimulatorImpl]’                  
../src/visualizer/model/visual-simulator-impl.cc:50:43:   required from here                                                            
./ns3/type-id.h:656:27: error: invalid new-expression of abstract class type ‘ns3::VisualSimulatorImpl’                                 
       ObjectBase * base = new T ();                                                                                                    
                           ^~~~~~~~                                                                                                     
In file included from ../src/visualizer/model/visual-simulator-impl.cc:21:0:                                                            
../src/visualizer/model/visual-simulator-impl.h:44:7: note:   because the following virtual functions are pure within ‘ns3::VisualSimul$
torImpl’:                                                                                                                               
 class VisualSimulatorImpl : public SimulatorImpl                                                                                       
       ^~~~~~~~~~~~~~~~~~~                                                                                                              
In file included from ../src/visualizer/model/visual-simulator-impl.h:24:0,                                                             
                 from ../src/visualizer/model/visual-simulator-impl.cc:21:                                                              
./ns3/simulator-impl.h:103:20: note:    virtual uint64_t ns3::SimulatorImpl::GetEventCount() const                                      
   virtual uint64_t GetEventCount (void) const = 0;                                                                                     
                    ^~~~~~~~~~~~~
`

Well here is the screenshot : 
![Screenshot from 2019-03-19 17-32-52](https://user-images.githubusercontent.com/21979281/54599419-343fd500-4a6d-11e9-8f9d-6b982a0fbf63.png)
![Screenshot from 2019-03-19 17-32-27](https://user-images.githubusercontent.com/21979281/54599417-33a73e80-4a6d-11e9-9d5b-1e7b214e96db.png)

**Comment by tommasozugno** [comment]
I think the problem is with PyViz. I never used it within the mmwave module and I am afraid that is not supported. I will check and let you know.

Best,
Tommaso

**Comment by paraparata** [comment]
Thanks for your time @tommasozugno for helping me in case. I really appreciate it.

**Comment by tommasozugno** [comment]
As described [here](https://www.nsnam.org/wiki/PyViz), PyViz is not available for the LTE module. Unfortunately this is true also for the mmwave module, since it is based on the LTE module.

Best,
Tommaso

**Comment by paraparata** [comment]
I see. Thank you so much for helping me. May I ask one more question? I face another error when running my scenario. The build, configure, and ./waf was succeed but it wont run my scenario file.
Here is the error : 

msg="Log component "Ping6Application" has already been registered once.", file=../src/core/model/log.cc, line=127
terminate called without an active exception

Big thx,
Parata

**Comment by tommasozugno** [comment]
It seems that you have registered two NS_LOG components with the same name, i.e., you have used NS_LOG_COMPONENT_DEFINE ("Ping6Application") twice.
