### ISSUE TITLE
NetAnim problem- mmwave-ca-same-bandwidth.cc

### ISSUE THREAD

**Issue by rsmadhuri** [nyuwireless-unipd/ns3-mmwave#103]
Hi,

When I tried to run mmwave-ca-same-bandwidth.cc by adding the NetAnim tool, I am getting segmentation error. 

Command ['/home/ubuntu/try_proj/ns3-mmwave/build/scratch/ca-same-bandwidth'] terminated with signal SIGSEGV. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

Please help. Thanks in advance.

**Comment by tommasozugno** [comment]
Hi,
Unfortunately the mmwave module does not support NetAnim.

Best,
Tommaso

**Comment by rsmadhuri** [comment]
Okay, Thank you.

Regards
Madhuri
