### ISSUE TITLE
Changing time resolution

### ISSUE THREAD

**Issue by arturandre** [nyuwireless-unipd/ns3-mmwave#105]
Hello everyone,

I'm new to ns-3 and to mmWave as well. I just learnt from tutorials that one can change time resolution of a simulation to seconds by executing `Time::SetResolution(Time::S)`. By testing some different resolutions at the mmWave/examples/mmwave-example.cc I found out that the only resolution that actually works (and I'm assuming that's because it's the default one) it nanoseconds.

I get the following error when I try to run the script (by using `./waf --run example-mmwave`) after changing the time resolution to seconds:

`msg="cannot TX while RX: Cannot transmit while receiving", file=../src/mmwave/model/mmwave-spectrum-phy.cc, line=893
terminate called without an active exception
Command ['/misc/users/arturao/ns3-mmwave/build/src/mmwave/examples/ns3-dev-mmwave-example-optimized'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").
`

I'll attach my version of mmwave-example.cc for reference. (I had to change the extension to .txt in order to make it a valid attachment.)

Is this a bug or I'm doing something wrong?

Thanks in advance =D
[mmwave-example.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/3146133/mmwave-example.txt)

**Comment by tommasozugno** [comment]
Hi!

I'm afraid that the only working resolution is nanoseconds. Btw, why do you need to change it?
 
Best,
Tommaso

**Comment by arturandre** [comment]
> Hi!
> 
> I'm afraid that the only working resolution is nanoseconds. Btw, why do you need to change it?
> 
> Best,
> Tommaso

I'd like to simulate a whole day considering bus traffic in a city with varying (from 1 to 40) cellphones in each bus. So that I could investigate the SINR for each cellphone given a set of eNBs deployed in the city.

**Comment by tommasozugno** [comment]
This module does not support simulations at different time scales, hence you have to use the default time resolution and... be patient :)

**Comment by arturandre** [comment]
> This module does not support simulations at different time scales, hence you have to use the default time resolution and... be patient :)

All right! Thanks very much.
