### ISSUE TITLE
3gpp Channel code reference to .m file 

### ISSUE THREAD

**Issue by mkp1072** [nyuwireless-unipd/ns3-mmwave#108]
Hi, 
I found that the file mmwave-3gpp-channel refers to two ".m" files for channel estimations. these are mentioned to be in the mmwave/model directory but I could not find them. Is it possible to get a copy of these files, since my work on Mimo requires me to add more functionality then available at present and I  want extend some classes
Regards
mkp1072

**Comment by mychele** [comment]
Hi,
please see here: https://github.com/nyuwireless-unipd/ns3-mmwave/blob/master/src/mmwave/model/BeamFormingMatrix/SqrtMatrix.m
Michele
