### ISSUE TITLE
Linear Precoding

### ISSUE THREAD

**Issue by mkp1072** [nyuwireless-unipd/ns3-mmwave#109]
IMHO, the mmwave channel implementation uses  an excellent implementation of Linear Algebra / Random Matrices in C++. Great work indeed ! If any extension to cover Linear Precoding of any type, such as,  ZF/MR/ MMSE..., has also been done, may I request a pointer to the same,,,,
Regards,

**Comment by mychele** [comment]
Hi, not in this version of the code! Contributions are welcome, though :)

**Comment by mkp1072** [comment]
Hi,
         Thank you so Very much for clarifying...
I will be working on adding Linear Precoding functions  ... For Massive
Mimo studies it appears inevitable,
keeping mind multiuser case, and the Pilot contamination...
I think in the channel and beamforming code, you have put quite some
information though.
I will start with that...

Any advice you can give will be very welcome...

With Warm Regards,
madan pande
