### ISSUE TITLE
Generating the graphs

### ISSUE THREAD

**Issue by Mehul18166** [nyuwireless-unipd/ns3-mmwave#110]
Hi,
I am quite new to ns3 and have gone through the ns3 tutorial. I am working on the paper "End-to-end simulation of 5G mmwave networks". Currently I am working on the new handover branch, I am able to generate RxPacketTrace.txt file but I do not know how to generate the graphs such as the SINR plot. Can you please guide me on how to generate the graphs from the output files. I tried using the plot_sinr_rate.py file but it was showing errors.
Please help.

**Comment by mychele** [comment]
Hi,
please consider this wiki page, with a list of all the traces that this module can export: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces

**Comment by Mehul18166** [comment]
Thank you for your quick response. I have gone through the wiki link. Please correct me if I am wrong, do I need to write separate python scripts in order to generate the graphs or the graphs can be generated using plot_sinr_rate.py file. I am facing errors while running this particular script.

**Comment by mychele** [comment]
Yes, you can write a script in any language you feel comfortable with.
