### ISSUE TITLE
nc-twoenbs.cc throughput

### ISSUE THREAD

**Issue by HaidarAbbas** [nyuwireless-unipd/ns3-mmwave#111]
Hello everyone

could you please help me to find the calculation of throughput in this scenario.
with my best regards ...

**Comment by tommasozugno** [comment]
Hi,

here you can find the description of the output files https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces. To read them and compute the throughput you can either develop your own script or use this one https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/scripts/read_traces.pl.

Best,
Tommaso

**Comment by HaidarAbbas** [comment]
Thanks
