### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gustavostorck** [nyuwireless-unipd/ns3-mmwave#112]
Hello,

Following the instructions:

https://github.com/nyuwireless-unipd/mmwave#getting-started

Operational system

DISTRIB_ID = Ubuntu
DISTRIB_RELEASE = 18.04
DISTRIB_CODENAME = bionic
DISTRIB_DESCRIPTION = "Ubuntu 18.04.1 LTS"
NAME = "Ubuntu"
VERSION = "18.04.1 LTS (Bionic Beaver)"
ID = ubuntu
ID_LIKE = debian
PRETTY_NAME = "Ubuntu 18.04.1 LTS"
VERSION_ID = "18.04"

gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1 ~ 18.04.1) 7.4.0

- // -

In this step:

Then, clone the mmwave module and patch the LTE one:

git clone https://github.com/nyuwireless-unipd/mmwave mmwave
cp mmwave / ns-3-patches / patch-for-lte.diff lte
cd lte
patch -p1 -N -E -i patch-for-lte.diff
rm patch-for-lte.diff

Execution

File to patch: patch-for-lte.diff
patching file patch-for-lte.diff
Hunk # 1 FAILED at 38.
Hunk # 2 FAILED at 59.
Hunk # 3 FAILED at 80.
Hunk # 4 FAILED at 88.
Hunk # 5 FAILED at 97.
Hunk # 6 FAILED at 143.
Hunk # 7 FAILED at 208.
Hunk # 8 FAILED at 249.
Hunk # 9 FAILED at 258.
9 out of 9 hunks FAILED - saving rejects to file patch-for-lte.diff.rej
can not find file to patch at input line 43305
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
| diff -Naru a / test / lte-test-fading.h b / test / lte-test-fading.h
| --- a / test / lte-test-fading.h 2018-08-03 16: 38: 46,683807085 +0200
| +++ b / test / lte-test-fading.h 2018-08-03 16: 39: 02.895957709 +0200

- // -

Output when trying to compile

[1540/2802] Compiling src / lte / model / lte-rlc-um-lowlat.cc
In file included from ../src/lte/model/lte-ue-mac.h:29:01,
                 from ../src/lte/model/lte-ue-phy.cc:41:
./ns3/lte-mac-sap.h:95:3: error: 'virtual' outside class declaration
   virtual void NotifyDlHarqDeliveryFailure (uint8_t harqId);

Waf: Leaving directory `/ var / ns-3-dev / build '
Build failed
 -> task in 'ns3-lte' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lte' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lte' failed with exit status 1 (run with -v to display more information)
 -> task in 'ns3-lte' failed with exit status 1 (run with -v to display more information)

**Comment by tommasozugno** [comment]
Hi,

You can clone the ns3-mmwave repo, it contains both ns-3 and the mmwave module. The main branch is new-handover.

Best,
Tommaso

**Comment by gustavostorck** [comment]
Hi

Sorted out. Thank you!

Best Regards,
Gustavo
