### ISSUE TITLE
Simulate the throughput in "mmwave-amc-test.cc"

### ISSUE THREAD

**Issue by majiteng** [nyuwireless-unipd/ns3-mmwave#113]
Dear nyuwireless-unipd,

I want to simulate your result of the relationship between SINR and throughput. In your script example "mmwave-amc-test.cc". I add the epc and RemoteHost. Then add UDP application to UE and RemoteHost. Then calculate the throughput of a specific SINR.

However, the result is quite different from your result. the maximum throughput is 720Mbps.

Can you help me check my .cc script? thank you very much.

Best Regards
Jiteng

`/* -*-  Mode: C++; c-file-style: "gnu"; indent-tabs-mode:nil; -*- */
/*
*   Copyright (c) 2011 Centre Tecnologic de Telecomunicacions de Catalunya (CTTC)
*   Copyright (c) 2015, NYU WIRELESS, Tandon School of Engineering, New York University
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License version 2 as
*   published by the Free Software Foundation;
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
*   Author: Marco Miozzo <marco.miozzo@cttc.es>
*           Nicola Baldo  <nbaldo@cttc.es>
*
*   Modified by: Marco Mezzavilla < mezzavilla@nyu.edu>
*                         Sourjya Dutta <sdutta@nyu.edu>
*                         Russell Ford <russell.ford@nyu.edu>
*                         Menglei Zhang <menglei@nyu.edu>
*/

#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/mobility-module.h"
#include "ns3/config-store.h"
#include "ns3/mmwave-helper.h"
#include <ns3/buildings-helper.h>
#include "ns3/global-route-manager.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/internet-module.h"
#include "ns3/applications-module.h"
#include "ns3/log.h"
#include "ns3/mmwave-propagation-loss-model.h"
#include "ns3/mmwave-point-to-point-epc-helper.h"
#include "ns3/point-to-point-helper.h"

using namespace ns3;
using namespace mmwave;

double snrUpdateIntervalMs = 100.0;  // in ms
double snrIncDb = 0.1; // increment by 10 meters
double snrMinDb = 30;  // eNB-UE distance in meters
double snrMaxDb = 30;  // eNB-UE distance in meters
bool smallScale = true;
double speed = 1.0;

Ptr<PacketSink> sink;                         /* Pointer to the packet sink application */
uint64_t lastTotalRx = 0;                     /* The value of the last total received bytes */

void
CalculateThroughput ()
{
  Time now = Simulator::Now ();                                         /* Return the simulator's virtual time. */
  double cur = (sink->GetTotalRx () - lastTotalRx) * (double) 8 / 1e5;     /* Convert Application RX Packets to MBits. */
  std::cout << now.GetSeconds () << "s: \t" << cur << " Mbit/s" << std::endl;
  lastTotalRx = sink->GetTotalRx ();
  Simulator::Schedule (MilliSeconds (100), &CalculateThroughput);
}

void updateSnr (double snrInit, Ptr<MmWaveEnbNetDevice> enbDev, Ptr<SpectrumModel> model, Ptr<MmWaveAmc> amc)
{
//  std::cout << "************* distance changing to " << dist << " *************" << std::endl;
//  Ptr<MobilityModel> mobModel = ue->GetObject<MobilityModel> ();
//  mobModel->SetPosition (Vector (dist, 0.0, 0.0));

  Ptr<MmWavePhyMacCommon> config = enbDev->GetPhy ()->GetConfigurationParameters ();

  SpectrumValue specVals (model);
  Values::iterator specIt = specVals.ValuesBegin ();
  for (unsigned ichunk = 0; ichunk < model->GetNumBands (); ichunk++)
    {
      //double sinrLin = std::pow (10, itCqi->second.m_ueUlCqi.at (ichunk) / 10);
      //						double se1 = log2 ( 1 + (std::pow (10, sinrLin / 10 )  /
      //								( (-std::log (5.0 * m_berDl )) / 1.5) ));
      //						cqi += m_amc->GetCqiFromSpectralEfficiency (se1);
      NS_ASSERT (specIt != specVals.ValuesEnd ());
      *specIt = std::pow (10, snrInit / 10);         //sinrLin;
      specIt++;
    }

  int mcsTmp = 28;
  int mcs = 0;
  int mcsOrig = 0;
  while (true)
    {
      int tbs = amc->GetTbSizeFromMcsSymbols (mcsTmp, 22) / 8;
      amc->CreateCqiFeedbackWbTdma (specVals, 22, tbs, mcs);
      if (mcs == mcsTmp || mcs == mcsOrig)
        {
          break;
        }
      mcsOrig = mcsTmp;
      mcsTmp = mcs;
    }
  enbDev->GetMac ()->SetMcs (mcs);
  std::cout << "************* SINR changing to " << snrInit << " (MCS = " << mcs << " ) *************" << std::endl;

  Simulator::Schedule (MicroSeconds (3 * 100), &MmWaveSpectrumPhy::UpdateSinrPerceived,
                       enbDev->GetPhy ()->GetDlSpectrumPhy (), specVals);

  //enbPhy->GenerateDataCqiReport(specVals);

  if (snrInit > snrMaxDb)
    {
      return;
    }

  Simulator::Schedule (MilliSeconds (snrUpdateIntervalMs), &updateSnr, snrInit + 0.1, enbDev, model, amc);
}

int
main (int argc, char *argv[])
{
  /* Information regarding the traces generated:
   *
   * 1. UE_1_SINR.txt : Gives the SINR for each sub-band
   *    Subframe no.  | Slot No. | Sub-band  | SINR (db)
   *
   * 2. UE_1_Tb_size.txt : Allocated transport block size
   *    Time (micro-sec)  |  Tb-size in bytes
   * */

//	LogComponentEnable ("MmWaveSpectrumPhy", LOG_LEVEL_DEBUG);
//	LogComponentEnable ("MmWaveBeamforming", LOG_LEVEL_DEBUG);
//	LogComponentEnable ("MmWaveUePhy", LOG_LEVEL_DEBUG);
//	LogComponentEnable ("MmWaveEnbPhy", LOG_LEVEL_DEBUG);
//	LogComponentEnable ("MmWaveFlexTtiMacScheduler", LOG_LEVEL_DEBUG);
  LogComponentEnable ("MmWavePhyRxTrace", LOG_LEVEL_DEBUG);
  //LogComponentEnable ("LteRlcUm", LOG_LEVEL_LOGIC);
  //LogComponentEnable ("MmWaveUeMac", LOG_LEVEL_LOGIC);
  //LogComponentEnable ("UdpClient", LOG_LEVEL_INFO);
  //LogComponentEnable ("PacketSink", LOG_LEVEL_INFO);
  //LogComponentEnable("PropagationLossModel",LOG_LEVEL_ALL);

  uint16_t numEnb = 1;
  uint16_t numUe = 1;

  uint32_t payloadSize = 1000;                       /* Transport layer payload size in bytes. */
  std::string dataRate = "4000Mbps";

  double simTime = 1.0;
  bool harqEnabled = true;
  int mcsDl = 28;
  std::string channelState = "n";

  // Command line arguments
  CommandLine cmd;
  cmd.AddValue ("numEnb", "Number of eNBs", numEnb);
  cmd.AddValue ("numUe", "Number of UEs per eNB", numUe);
  cmd.AddValue ("simTime", "Total duration of the simulation [s])", simTime);
  cmd.AddValue ("harq", "Enable Hybrid ARQ", harqEnabled);
  cmd.AddValue ("mcsDl", "Fixed DL MCS", mcsDl);
  cmd.AddValue ("channelState", "Channel state 'l'=LOS, 'n'=NLOS, 'a'=all", channelState);
  cmd.AddValue ("snrMinDb", "Minimum (final) SNR", snrMinDb);
  cmd.AddValue ("snrMaxDb", "Maximum (initial) SNR", snrMaxDb);
  cmd.AddValue ("snrIncDb", "SNR increment", snrIncDb);
  cmd.AddValue ("snrUpdateIntervalMs", "Period after which distance is updated", snrUpdateIntervalMs);
  cmd.AddValue ("smallScale", "Enable small scale fading", smallScale);
  cmd.Parse (argc, argv);

  simTime = ((snrMaxDb - snrMinDb) / snrIncDb) * (snrUpdateIntervalMs / 1000.0) + 1;

  if (mcsDl >= 0 && mcsDl < 29)
    {
      Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::FixedMcsUl", BooleanValue (true));
      Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::McsDefaultUl", UintegerValue (mcsDl));
    }

  Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::HarqEnabled", BooleanValue (harqEnabled));
  Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::UlSchedOnly", BooleanValue (true));
  Config::SetDefault ("ns3::MmWavePhyMacCommon::ResourceBlockNum", UintegerValue (1));
  Config::SetDefault ("ns3::MmWavePhyMacCommon::ChunkPerRB", UintegerValue (72));
  Config::SetDefault ("ns3::MmWaveBeamforming::LongTermUpdatePeriod", TimeValue (Seconds (2 * simTime)));
  Config::SetDefault ("ns3::LteEnbRrc::SystemInformationPeriodicity", TimeValue (MilliSeconds (1.0)));
  Config::SetDefault ("ns3::MmWaveAmc::Ber", DoubleValue (0.001));
  Config::SetDefault ("ns3::MmWaveBeamforming::SmallScaleFading", BooleanValue (smallScale));
  Config::SetDefault ("ns3::MmWaveBeamforming::FixSpeed", BooleanValue (true));
  Config::SetDefault ("ns3::MmWaveBeamforming::UeSpeed", DoubleValue (speed));
  //Config::SetDefault ("ns3::MmWavePropagationLossModel::ChannelStates", StringValue (channelState));
  Config::SetDefault ("ns3::MmWavePropagationLossModel::FixedLossTst", BooleanValue (false));
  Config::SetDefault ("ns3::MmWavePropagationLossModel::LossFixedDb", DoubleValue (100.0));
  Config::SetDefault ("ns3::MmWaveHelper::UseIdealRrc", BooleanValue(true));

  Ptr<MmWaveHelper> mmwHelper = CreateObject<MmWaveHelper> ();
  Ptr<MmWavePointToPointEpcHelper>  epcHelper = CreateObject<MmWavePointToPointEpcHelper> ();
  mmwHelper->SetEpcHelper (epcHelper);
  mmwHelper->Initialize ();
  mmwHelper->SetHarqEnabled (harqEnabled);
  mmwHelper->SetSnrTest (true);
  // Ptr<MmWavePropagationLossModel> lossModel = mmwHelper->GetPathLossModel ()->GetObject<MmWavePropagationLossModel> ();

  /* A configuration example.
   * mmwHelper->GetPhyMacConfigurable ()->SetAttribute("SymbolPerSlot", UintegerValue(30)); */
  //ConfigStore inputConfig;
  //inputConfig.ConfigureDefaults ();

  Ptr<Node> pgw = epcHelper->GetPgwNode ();

  // Create a single RemoteHost
  NodeContainer remoteHostContainer;
  remoteHostContainer.Create (1);
  Ptr<Node> remoteHost = remoteHostContainer.Get (0);
  InternetStackHelper internet;
  internet.Install (remoteHostContainer);

  // Create the Internet
  PointToPointHelper p2ph;
  p2ph.SetDeviceAttribute ("DataRate", DataRateValue (DataRate ("100Gb/s")));
  p2ph.SetDeviceAttribute ("Mtu", UintegerValue (1500));
  p2ph.SetChannelAttribute ("Delay", TimeValue (Seconds (0.010)));
  NetDeviceContainer internetDevices = p2ph.Install (pgw, remoteHost);
  Ipv4AddressHelper ipv4h;
  ipv4h.SetBase ("1.0.0.0", "255.0.0.0");
  Ipv4InterfaceContainer internetIpIfaces = ipv4h.Assign (internetDevices);
  // interface 0 is localhost, 1 is the p2p device
  Ipv4Address remoteHostAddr = internetIpIfaces.GetAddress (1);

  Ipv4StaticRoutingHelper ipv4RoutingHelper;
  Ptr<Ipv4StaticRouting> remoteHostStaticRouting = ipv4RoutingHelper.GetStaticRouting (remoteHost->GetObject<Ipv4> ());
  remoteHostStaticRouting->AddNetworkRouteTo (Ipv4Address ("7.0.0.0"), Ipv4Mask ("255.0.0.0"), 1);

  // Create two nodes for UE and Enb
  NodeContainer enbNodes;
  NodeContainer ueNodes;
  enbNodes.Create (numEnb);
  ueNodes.Create (numUe);

  Ptr<ListPositionAllocator> enbPositionAlloc = CreateObject<ListPositionAllocator> ();
  enbPositionAlloc->Add (Vector (0.0, 0.0, 0.0));

  MobilityHelper enbmobility;
  enbmobility.SetMobilityModel ("ns3::ConstantPositionMobilityModel");
  enbmobility.SetPositionAllocator (enbPositionAlloc);
  enbmobility.Install (enbNodes);
  BuildingsHelper::Install (enbNodes);

  MobilityHelper uemobility;
  Ptr<ListPositionAllocator> uePositionAlloc = CreateObject<ListPositionAllocator> ();
  uePositionAlloc->Add (Vector (snrMinDb, 0.0, 0.0));

  uemobility.SetMobilityModel ("ns3::ConstantPositionMobilityModel");
  uemobility.SetPositionAllocator (uePositionAlloc);
  uemobility.Install (ueNodes);
  BuildingsHelper::Install (ueNodes);

  // Install mmWave Devices to the nodes
  NetDeviceContainer enbNetDev = mmwHelper->InstallEnbDevice (enbNodes);
  NetDeviceContainer ueNetDev = mmwHelper->InstallUeDevice (ueNodes);

  // Install the IP stack on the UEs
  internet.Install (ueNodes);
  Ipv4InterfaceContainer ueIpIface;
  ueIpIface = epcHelper->AssignUeIpv4Address (NetDeviceContainer (ueNetDev));

  // Set the default gateway for the UE
  Ptr<Ipv4StaticRouting> ueStaticRouting = ipv4RoutingHelper.GetStaticRouting (ueNodes.Get (0)->GetObject<Ipv4> ());
  ueStaticRouting->SetDefaultRoute (epcHelper->GetUeDefaultGatewayAddress (), 1);

  mmwHelper->AttachToClosestEnb (ueNetDev, enbNetDev);
  mmwHelper->EnableTraces ();

  //Choose RemoteHost transmit(DL) or UE transmit(UL)
  bool RemoteHost_Tx = false;  // RemoteHost_Tx = false if UE is transmitter
  if (RemoteHost_Tx == true)
	{
	  // Install UDP Receiver on the UE
	  PacketSinkHelper sinkHelper ("ns3::UdpSocketFactory", InetSocketAddress (Ipv4Address::GetAny (), 9));
	  ApplicationContainer sinkApp = sinkHelper.Install (ueNodes);
	  sink = StaticCast<PacketSink> (sinkApp.Get (0));

	  // Install UDP Transmitter on the RemoteHost
	  OnOffHelper server ("ns3::UdpSocketFactory", (InetSocketAddress (ueIpIface.GetAddress (0), 9)));
	  server.SetAttribute ("PacketSize", UintegerValue (payloadSize));
	  server.SetAttribute ("OnTime", StringValue ("ns3::ConstantRandomVariable[Constant=1]"));
	  server.SetAttribute ("OffTime", StringValue ("ns3::ConstantRandomVariable[Constant=0]"));
	  server.SetAttribute ("DataRate", DataRateValue (DataRate (dataRate)));
	  ApplicationContainer serverApp = server.Install (remoteHost);

	  // Start Applications
	  sinkApp.Start (Seconds (0.0));
	  serverApp.Start (Seconds (0.0));
	  Simulator::Schedule (Seconds (0.1), &CalculateThroughput);

	}
  else
  {
	  // Install UDP Receiver on the RemoteHost
	  PacketSinkHelper sinkHelper ("ns3::UdpSocketFactory", InetSocketAddress (Ipv4Address::GetAny (), 9));
	  ApplicationContainer sinkApp = sinkHelper.Install (remoteHost);
	  sink = StaticCast<PacketSink> (sinkApp.Get (0));

	  // Install UDP Transmitter on the ue
	  OnOffHelper server ("ns3::UdpSocketFactory", (InetSocketAddress (remoteHostAddr, 9)));
	  server.SetAttribute ("PacketSize", UintegerValue (payloadSize));
	  server.SetAttribute ("OnTime", StringValue ("ns3::ConstantRandomVariable[Constant=1]"));
	  server.SetAttribute ("OffTime", StringValue ("ns3::ConstantRandomVariable[Constant=0]"));
	  server.SetAttribute ("DataRate", DataRateValue (DataRate (dataRate)));
	  ApplicationContainer serverApp = server.Install (ueNodes);

	  // Start Applications
	  sinkApp.Start (Seconds (0.0));
	  serverApp.Start (Seconds (0.0));
	  Simulator::Schedule (Seconds (0.1), &CalculateThroughput);
  }

  /*
  // Activate a data radio bearer
  enum EpsBearer::Qci q = EpsBearer::GBR_CONV_VOICE;
  EpsBearer bearer (q);
  mmwHelper->ActivateDataRadioBearer (ueNetDev, bearer);
  */

  Ptr<MmWaveEnbNetDevice> enbMmwDev = enbNetDev.Get (0)->GetObject<MmWaveEnbNetDevice> ();

  Ptr<MmWaveAmc> amc = CreateObject <MmWaveAmc> (mmwHelper->GetCcPhyParams ().at (0).GetConfigurationParameters ());

  Simulator::Schedule (MilliSeconds (0), &updateSnr, snrMinDb,
                       enbMmwDev,
                       MmWaveSpectrumValueHelper::GetSpectrumModel (mmwHelper->GetCcPhyParams ().at (0).GetConfigurationParameters ()),
                       amc);

  Simulator::Stop (Seconds (simTime+0.1));
  NS_LOG_UNCOND ("Simulation running for " << simTime << " seconds");
  Simulator::Run ();

  double averageThroughput = ((sink->GetTotalRx () * 8) / (1e6 * simTime));

  Simulator::Destroy ();

  std::cout << "\nAverage throughput: " << averageThroughput << " Mbit/s" << std::endl;

  return 0;
}
`

**Comment by tommasozugno** [comment]
Hi,

I'm not familiar with this example but I think the difference is because you are evaluating the throughput at the application layer, while in the original example they evaluated the throughput at the MAC layer using the RLC SM configuration (https://www.nsnam.org/docs/models/html/lte-design.html#sm-rlc).

Best,
Tommaso

**Comment by majiteng** [comment]
> Hi,
> 
> I'm not familiar with this example but I think the difference is because you are evaluating the throughput at the application layer, while in the original example they evaluated the throughput at the MAC layer using the RLC SM configuration (https://www.nsnam.org/docs/models/html/lte-design.html#sm-rlc).
> 
> Best,
> Tommaso

Thank you very much, Tommaso. I get the same result in MAC.

**Comment by majiteng** [comment]
> > Hi,
> > I'm not familiar with this example but I think the difference is because you are evaluating the throughput at the application layer, while in the original example they evaluated the throughput at the MAC layer using the RLC SM configuration (https://www.nsnam.org/docs/models/html/lte-design.html#sm-rlc).
> > Best,
> > Tommaso
> 
> Thank you very much, Tommaso. I get the same result in MAC.

Hi Tommaso,

Could you please tell me how do you calculate the IP layer latency? I use the TCP stream in the application layer to trace the RTT(round trip time) value. The result is again poorer than yours.

Sincerely
Jiteng

**Comment by tommasozugno** [comment]
You need to add a time stamp to the packets. You can have a look at the method DoTransmitPdcpSdu in the file mc-ue-pdcp.cc to see how this can be done.

Tommaso

**Comment by majiteng** [comment]
> You need to add a time stamp to the packets. You can have a look at the method DoTransmitPdcpSdu in the file mc-ue-pdcp.cc to see how this can be done.
> 
> Tommaso

Hi Tommaso,

It is still hard for me, could you explain a little bit more in detail or give me a similar example? 

Jiteng

**Comment by tommasozugno** [comment]
If you want to measure the end-to-end delay you need to modify your application in this way:
- at the sender side: add a time stamp to each packet before sending it
- at the receiver side: retrieve the time stamp and compute the delay
You can find an example in mc-ue-pdcp.cc. In the method DoTransmitPdcpSdu, a PdcpTag containing the time stamp is added, while in the method DoReceivePdu, the tag is removed to compute the delay.

Notice that if you are using RLC SM mode as above you won't be able to compute the end-to-end delay because you are simulating the radio access only and up to the RLC layer. In this case you can evaluate the delay at the RLC layer by looking at the Dl[Ul]RlcStats.txt files (see https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces).

Best,
Tommaso

**Comment by majiteng** [comment]
> If you want to measure the end-to-end delay you need to modify your application in this way:
> 
> * at the sender side: add a time stamp to each packet before sending it
> * at the receiver side: retrieve the time stamp and compute the delay
>   You can find an example in mc-ue-pdcp.cc. In the method DoTransmitPdcpSdu, a PdcpTag containing the time stamp is added, while in the method DoReceivePdu, the tag is removed to compute the delay.
> 
> Notice that if you are using RLC SM mode as above you won't be able to compute the end-to-end delay because you are simulating the radio access only and up to the RLC layer. In this case you can evaluate the delay at the RLC layer by looking at the Dl[Ul]RlcStats.txt files (see https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces).
> 
> Best,
> Tommaso

Thank you very much, it is very clear

Best regards
Jiteng

**Comment by EliseuFelipe** [comment]
Hi, I'm having problem with it.
Config::SetDefault ("ns3::MmWavePhyMacCommon::ResourceBlockNum", UintegerValue (1));

msg="Could not set default value for ns3::MmWavePhyMacCommon::ResourceBlockNum", file=../src/core/model/config.cc, line=854
terminate called without an active exception

**Comment by tommasozugno** [comment]
The attribute MmWavePhyMacCommon::ResourceBlockNum no longer exists, it was removed in the last release. Please consider updating your script accordingly.
