### ISSUE TITLE
mc-twoenbs .cc trace plot

### ISSUE THREAD

**Issue by YoussefMoukabaa** [nyuwireless-unipd/ns3-mmwave#115]
Hello 
whenever i try to run one of the plot scripts in scripts folder i encounter the same error :

Traceback (most recent call last):
  File "/home/ns3-1/PycharmProjects/NS3 2.7/test.py", line 48, in <module>
    tsLast = float(c.read().rstrip()) / 1e9
ValueError: could not convert string to float: 

could you help me the solution or am I doing any thing wrong like input file ?

**Comment by tommasozugno** [comment]
Hi,

I never used those scripts but I think they are targeted for specific examples and may not work in your case. I recommend you to write your own script, here you can find a description of the output trace files: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces

Best,
Tommaso

**Comment by YoussefMoukabaa** [comment]
Hi @tommasozugno 
I know these scripts are targeted for specific examples, I think I am using the right example, anyway is there any documentation for the examples and what scripts are written for and what are the input files required.

Best regards,
Youssef

**Comment by tommasozugno** [comment]
Unfortunately they are not documented, I see they have been added by @rustyolford but I think he is not working on this project anymore. 
They have not been updated so far, so they may be not compatible with the current version of the code (some output files may be different). Anyway, I guess it would not be difficult to fix them, maybe I can help you. What do you want to plot?

**Comment by YoussefMoukabaa** [comment]
I want to plot the PDCP throughput with time and cell id i tried from read_traces.pl but i got different results from mentioned in the paper "End_to End Simulation of 5G mmwave Networks" and the plot_Pdcp-rate.py is not working

Regards 
Youssef

**Comment by tommasozugno** [comment]
Can you please provide the results you got with read_traces.pl?

**Comment by YoussefMoukabaa** [comment]
I attached the results here 
Please check
[DlPdcpStats_sampled.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/3485423/DlPdcpStats_sampled.txt)
@tommasozugno

**Comment by tommasozugno** [comment]
What parameters and configurations did you used? Notice that the results depend also on the seed, so you may not obtain exactly the same results (e.g., the buildings are deployed randomly, hence their positions change if you use a different seed). I recommend you to read https://arxiv.org/pdf/1611.04748.pdf and https://arxiv.org/pdf/1607.05425.pdf which have a more extensive description of this or similar examples.

**Comment by YoussefMoukabaa** [comment]
ok thank you were very helpful
