### ISSUE TITLE
Rate calculation

### ISSUE THREAD

**Issue by YoussefMoukabaa** [nyuwireless-unipd/ns3-mmwave#117]
Good day,
I am trying to simulate the results in the paper " A framework for E2E evaluation of 5G mmwave cellular networks in ns-3" specially the "mmwave-tdma" example and get the results similar to the figure 6, I was trying to get the rate in Mbps (Throughput) from the packet size in the result file "UlRlcStats.txt" but the results are very different.
Could you please tell me the equation or the method used to calculate the rate and what are the inputs.

Thanks in advance
Youssef

**Comment by tommasozugno** [comment]
Hi, 

The figure refers to the DL case, you should consider the file "DlRlcStats.txt"

Best,
Tommaso

**Comment by YoussefMoukabaa** [comment]
Thank you for the quick @tommasozugno response but there is no "DlRlcstats.txt" file generated, only "UlRlcStats.txt" and "PxPacketTrace.txt" 
How to generate this file?

Best regards
Youssef

**Comment by tommasozugno** [comment]
This is because the attribute MmWaveFlexTtiMacScheduler::UlSchedOnly is set to true, you should change it to false.

**Comment by YoussefMoukabaa** [comment]
Ok, it worked for me, 
Thank you very  much

**Comment by RahulSinghGulia** [comment]
Could you please let me know how you generated the Figure-6 of the paper  " A framework for E2E evaluation of 5G mmwave cellular networks in ns-3", after generating the "DlRlcStats.txt". 
We can get the Empirical Probability from RxPacketTrace.txt file (last column). But how to get the Rate (Mbps) from these files?

I would really appreciate any kind of help on this one..
