### ISSUE TITLE
5G-Indoor Localization for mobile devices

### ISSUE THREAD

**Issue by OmarHory** [nyuwireless-unipd/ns3-mmwave#119]
We are bachelor Network Engineering Students doing a research on 5G- Adaptive Indoor Localization for mobile devices using ns-3 mmWave module.
My question is, how can this module help me? where should I start?
I would really appreciate some help since I am a beginner, I am not quite sure how to start.

Regards,
Omar

**Comment by tommasozugno** [comment]
Hi Omar, 

This module does not support any localization feature. You can have a look at this paper https://ieeexplore.ieee.org/document/8344116 which  contains the overall description of the module.

Tommaso

**Comment by OmarHory** [comment]
> Hi Omar,
> 
> This module does not support any localization feature. You can have a look at this paper https://ieeexplore.ieee.org/document/8344116 which contains the overall description of the module.
> 
> Tommaso

This link is not working.
