### ISSUE TITLE
How to speed up the simulation, they run way too slow

### ISSUE THREAD

**Issue by iabdullahsk** [nyuwireless-unipd/ns3-mmwave#120]
Most of the examples run at 0.1 sec/sec. I have another vehicle simulator interfaced with ns3 for some research which results in that running at the same speed. I have been digging into the code to find a way to somehow speed up the simulation so that I can work with the vehicle simulator as well to test some scenarios. This is not exactly an issue, but any help about what I should be digging into or changing to achieve this would be really helpful. Thank you.

**Comment by tommasozugno** [comment]
Hi,

If you are using the 3GPP channel model, the bottleneck of the simulation is the update of the channel matrices (method MmWave3gppChannel::UpdateChannel). To speed up the simulations you can try to update the channel matrices less frequently by increasing the value of the attribute MmWave3gppChannel::UpdatePeriod (the default is 1 ms).

Best,
Tommaso

**Comment by iabdullahsk** [comment]
Thank you Tommaso, I tried that and though it does improve the speed of the simulation. But still it maxes out one of my CPU cores while simulation. This is with a single UE ENB pair. Increasing the number of these significantly increases the simulation time to the point that it just keeps processing without any progress on the simulation time. What would you suggest I could do that would allow me to use this module with lets say 125 UE nodes and 50 ENBs. Anything that I can try to make reduce the computations to the minimum?

**Comment by tommasozugno** [comment]
If you have access, you could try with a computing cluster. Otherwise I think you need to use a simpler channel model, like the Nakagami, but it would lead to quite different results (see https://arxiv.org/pdf/1806.06125.pdf)

**Comment by iabdullahsk** [comment]
Thank you, I went through it and seems to be ideal for my use case if it will increase the simulation time by a magnitude. I understand that you are from the same faculty, so thought i'd ask that would it be possible to get access to the "MmWaveSimpleChannel" module and a corresponding simplified beamforming, I could not find it in this mmWave module. Or is it not supposed to be public?

**Comment by mychele** [comment]
Hi,
we decided not to release that model yet because the results in some cases diverged from those obtained with the 3GPP channel, as highlighted in the paper that Tommaso referenced. We are discussing internally on whether it makes sense to release it with sufficient documentation to warn the users of this, and we'll keep you posted!
Michele

**Comment by iabdullahsk** [comment]
Thank you, I appreciate all the help.
