### ISSUE TITLE
Using SUMO/ns3-mmwave to Simulate 5G Networks

### ISSUE THREAD

**Issue by ibrotutic** [nyuwireless-unipd/ns3-mmwave#121]
Hi, I am student working on a project at Iowa State University to implement a new scheduling algorithm built for highly mobile 5G networks (vehicles for example).

 I have been familiarizing myself with OAI (Open Air Interface) but it seems that they have lost support for SUMO for 5G simulations, meaning that we would have to write this before we could even begin developing. Because of this, I wanted to see if there were other options, and it seems like this project may work (as it is built off of ns-3, which supports SUMO).

My plan is to modify the scheduling algorithm at the enb-MAC layer, but wasn't sure if this was possible with this project. Would you be able to give me any tips to get started?

**Comment by tommasozugno** [comment]
Hi,

Yes, it is possible. You can start by looking at this paper https://arxiv.org/pdf/1705.02882.pdf, which provides an overall description of the module, including the different scheduling policies which are currently implemented. To develop your own scheduler you should write a new class extending the MmWaveMacScheduler interface.

Best,
Tommaso

**Comment by ibrotutic** [comment]
Thanks for the info!
