### ISSUE TITLE
lte traces from mc-twoenbs

### ISSUE THREAD

**Issue by YoussefMoukabaa** [nyuwireless-unipd/ns3-mmwave#122]
Hii,
I want to get sinr values from the lte ENB in the mc-twoEnbs.cc example, i tired to include
#include "ns3/lte-helper.h"
#include "ns3/lte-module.h"
and   lteHelper->EnableTraces ();
but it didn't work, what is the easiest way to get these values
Thanks
Youssef

**Comment by mychele** [comment]
Hi,
please take a look at the LTE documentation on how to generate traces from the LTE classes: https://www.nsnam.org/docs/models/html/lte-user.html
For the traces related to mmWave, you can take a look here:
https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces
Michele
