### ISSUE TITLE
mmWave UE-gnb Handover

### ISSUE THREAD

**Issue by OmarHory** [nyuwireless-unipd/ns3-mmwave#124]
Can someone please guide me through the handover process from a UE to another gnb?
There is a function called AttachToEnb in the mmwave-helper.cc line:764... But there is nothing to DeAttach,.. Can someone please guide me through the process of DeAttaching and Attaching to another one? Because when I repeat the AttachToEnb on another gnb I get a ton of "nullptr" errors.

**Comment by tommasozugno** [comment]
The handover logic is implemented in the RRC model. The gNB RRC triggers the handover of a UE to another cell through a connection reconfiguration procedure. When the UE receives the connection reconfiguration message, it is synchronized with the new cell (see https://github.com/nyuwireless-unipd/ns3-mmwave/blob/ac44a461252eea95e17d739538b9c9da1d9dd47f/src/lte/model/lte-ue-rrc.cc#L1208). You can start by having a look at lte-enb-rrc and lte-ue-rrc.

Best,
Tommaso

**Comment by OmarHory** [comment]
Thanks Tommaso, I've checked it in detail just now.. but bare with me, I am somewhat trying to understand the logic.
The AttachToEnb from the mmWave Helper should be called? Or use the AttachToEnb from the LTEHelper then use the lte RRC model?

Would appreciate the help a lot Tommaso!

**Comment by tommasozugno** [comment]
The method MmWaveHelper::AttachToEnb is called once before the start of the simulation to force the attachment of the users. When the simulation starts, the gNB RRC entity decides about the handovers based on the measurements received by the UEs.

**Comment by iabdullahsk** [comment]
@OmarHory were you able to have the automatic handover working from one enb to another during the simulation? I have simple scenario, which i have tested with the arrangement used in https://www.nsnam.org/doxygen/lena-x2-handover-measures_8cc.html . For lte the handover the the ueDevices works fine but trying the similar scenario for mmwave, the handover doesnt happen. Is there something im missing? I have 1 UE and 2 eNBs. Even though the SINR degrades significantly, the handover does not take place. Is there a need on an LTE enb as well for this to work or should it work with just mmwavehelper's enbs as well? 
@tommasozugno @mychele  Any help will be appreciated, thank you

**Comment by mychele** [comment]
Hi,
yes - you should use the configuration with dual connectivity and the McUeNetDevice. See the mc-twoenbs.cc example as a reference.
