### ISSUE TITLE
Beamforming Vector

### ISSUE THREAD

**Issue by OmarHory** [nyuwireless-unipd/ns3-mmwave#126]
Hello!

Can someone assist me in how to get the BeamformingVector?
I am doing this and it isn't working.

##################################################################

Ptr<MmWaveSpectrumPhy > ue1SpectrumPhy1 = DynamicCast<MmWaveUeNetDevice> (uenetdev.Get(0))->GetPhy(0)->GetSpectrumPhy();

Ptr<AntennaArrayModel> antennaArray = DynamicCast<AntennaArrayModel> (ue1SpectrumPhy1->GetRxAntenna());

typedef std::pair<uint8_t, double> BeamId;
typedef std::pair<complexVector_t, BeamId>  BeamformingVector;

BeamformingVector a = antennaArray->GetBeamformingVector(uenetdev.Get(0));
BeamId b = a.second;
cout<<b;

###############################################################

When I print it I get: [Sector: 255, Elevation: -1}, noting that Cell Scan is on.

**Comment by tommasozugno** [comment]
Hi, 

Which repo/branch are you using?

**Comment by mychele** [comment]
Closing as inactive.
