### ISSUE TITLE
Elevation Angle

### ISSUE THREAD

**Issue by OmarHory** [nyuwireless-unipd/ns3-mmwave#127]
Why is the elevation angle between 60 and 120 degrees.
I understand the process of brute forcing and trying all the possible combinations until highest power is received, but why is it between 60 and 120? 
Elevation is supposed to be this angle?:

![az_elevation](https://user-images.githubusercontent.com/43903002/68851754-26675000-06df-11ea-868a-ad15ca62f67b.jpg)

![Capture2](https://user-images.githubusercontent.com/43903002/68851524-c40e4f80-06de-11ea-8f07-8e3e72ba2724.PNG)

**Comment by mychele** [comment]
Hi,
the angle that is scanned is on the azimuth, not the elevation. The range is just an example, you can adjust it at your convenience.
