### ISSUE TITLE
Are the default settings for H_usn restrictive

### ISSUE THREAD

**Issue by mkp1072** [nyuwireless-unipd/ns3-mmwave#129]
Hi,
        Just need an answer to one or two simple queries please...
2.        I would like to know whether the default choices for u,s and n would have any impact on the maximum number of BS and UE antenna array size. 
3. Since, number of BS antennas is very much greater than those in the UEs, in constructing the H_usn, for Downlink and Uplink, some zeros would get introduced, and would some time lead to a singular matrix, and requirement of SVD ... In Matlab way, one could reshapes and resize... is that the right way to avoid SVD issue and  in C++ Code, use sub-matrices ...Or just accept SVD and work with it...
4. I have done a couple of precoders for the mmwave but have faced some of these issues and that is why I am looking for a clarification please...
With Regards,

**Comment by mychele** [comment]
Hi,
replies inline.

> 2. I would like to know whether the default choices for u,s and n would have any impact on the maximum number of BS and UE antenna array size.

u and s (if I interpret your question correctly) are the number of antenna elements at the TX and RX, so the answer is yes. You can set them using attributes in the MmWaveEnb/UeNetDevices. The number of cluster n is given by the 3GPP model in the TR 38.901.

> 3. Since, number of BS antennas is very much greater than those in the UEs, in constructing the H_usn, for Downlink and Uplink, some zeros would get introduced, and would some time lead to a singular matrix, and requirement of SVD ... In Matlab way, one could reshapes and resize... is that the right way to avoid SVD issue and in C++ Code, use sub-matrices ...Or just accept SVD and work with it...

This question is not particularly clear..

> 4. I have done a couple of precoders for the mmwave but have faced some of these issues and that is why I am looking for a clarification please...

Did you try them in this module?

**Comment by mkp1072** [comment]
Michele,
                It was nice of you to respond so quickly, thank you. I have
been working on my own for some time
to write Linear Precoders, for research directed towards Massive MU-MIMO
...

2. I have acquired a great respect for NYU and Lund universities, who have
done some pioneering work on mmwave.

3. I was working first with NR stage 1 code, as CTTC said that the
ns3-mmwave implementation does not use the correct
slots and numerologies, and is thus obsolete now. I also didnot see any
updates on the gitHub. While I was working with NR stage 1,
CTTC announced Lena5gNR. The stage 1 did have a very crude implementation,
which arose from cutting and chopping the
ns3-mmwave code...to suit the stage 1 NR specs. Lena5G has a lot still more
changes everywhere,for instance, in the netdevice code,
in the mmwave-3gpp-channel code and so on. Not only this, on their code
(both stage 1 and stage 2, none
of the mmwave examples work). They give some modified examples code
prefixed by CTTC-. Every time they changed code, I had to redo
the coders, as they would make changes to mmwave-3gpp-channel, Antenna
Array module etc (but not address the Pilot messages, so that one could
use them in finding Pilot Contamination). They again changed the defaults
for H_[u][s][n] as well. So it was like developing and testing precoders
against shifting goal posts.

4. When I asked CTTC, about the NYU contributed files, they asked me to
direct the questions to your website.

5. So far I have coded using GSL the MRT/MRC decoder (which you have done
in C++), the  ZF Precoder and RZF Precoders.
In absence of inteference and missing Pilot data, I got held for going on
to testing RZF and MMSE...precoders.

6. I chose GSL, which  has a good integration with both NS3 and Octave, and
uses Row major, whereas,
Eigen3, though easy to use and some other libraries that are rated for good
performance, have only a Col major
implementation.Coding in C++ then would require a number of changing of
indices back and forth. The problem with
most Linear Algebra C++ libraries is that they donot deal with inversion of
complex matrices, and leave it to Lapack/lapcke,
which again brings in the Col Major/ Row major issue. I have used one work
around for SVD and GSL taking ideas from
Numerics C++ book to basically convert complex matrix to real and back, to
be able to use LinAlg GSL
function meant for real matrices...

7. They way I test it is to calculate, SINR vs BS AntennaPerformance,
Spectral Efficiency vs BS Antenna performance and Energy Efficiency
vs BS Antenna Performance. I would change the  BS antennas Nt, Wt... (Tell
me if it is incorrect ...) I have done some work with
NYUSim, which has now made the code open, though Java UI and main.m need
changes if one likes to prove and get good figures for
finding SE/EE etc... For myself, I use Octave with some added source-forge
packages...(which includes GSL)

8. *If there is any interest still in NS3-Mmwave*, I would surely like to
try both ZF and RZF precoders with it and any others
you may have in mind (ZF-SIC or MMSE/MMSE-SIC...or any space-time codes now
being experimented with).
But I would like you to suggest which example code (from examples or Test
codes) of your distribution, you think, would be the closest
to enhance in to  a satisfactory campaign Script. Let me know if you have
any interest...And which ns3-mmwave distribution to use...
I currently have NS3-mmwave with HO added branch..

9. What i had meant in para 3 was the following:
- when you have a large number of BS antennas the H_[u][s][n] becomes big,
yet, AFIK, in the Matlab way of reducing complexity,
one would use Reshape or Resize, so that matrix operations like transpose
for square matrices may be applied, thereby reducing the complexity.
If one does not follow that path IMHO, one would in some cases, find zeros
in the upper right triangle and thereby an SVD issue. It is not always
easy to test for SVD by calculating the Determinant, atleast for large
complex matrices... This is my learning working with precoders...maybe
I could be better but with some guidance or suggestions...

With Thanks and Regards,
madan
