### ISSUE TITLE
Can mmWave module works with new mptcp linux kernel through DCE?

### ISSUE THREAD

**Issue by ytxing** [nyuwireless-unipd/ns3-mmwave#132]
I am trying to run the example `dce-example-mptcp-mmwave.cc` with new version of mptcp linux kernel such as v0.94. It is possible to achieve that goal by following the sequence in a closed issue as 

1. Install ns3-DCE (version 1.10， latest)
2. Replace whole ns-3.28 folder to ns3-mmwave folder
3. Apply patch file to `kernel-socket-fd-factory.cc` and `kernel-socket-fd-factory.h`
4. Modify wscript file in ns-3-dce folder. In configure function add ns3waf.check_modules(conf, ['mmwave'], mandatory = False) code.
5. Build bake.py again to configure changed ns-3.28

It is quite confusing when I try to figure out how this works, as I notice that in [https://www.nsnam.org/docs/dce/manual/html/dce-user-kernel.html#build-an-mptcp-kernel-with-net-next-sim](manual) it require a mptcp kernel which is missing in above sequence.

I am following the manual now and I will update this issue when things happen.
Good day ;-)

**Comment by mychele** [comment]
Hi,
did you manage to install everything? In case, feel free to close this issue.
