### ISSUE TITLE
carriers aggregation of mmwave

### ISSUE THREAD

**Issue by fish-debug** [nyuwireless-unipd/ns3-mmwave#136]
Hello！
I would like to ask  some question  about carriers aggregation of mmwave.
First，why the reference subcarriers per symbol(m_numRefScPerSym) is default setting as 25% of total?
Second，I set up three carriers,working as RLC UM and UDP mode .The second carrier and the third carrier are the  same frequency and bandwidth.But when the data is stable，the transmission capacity of the third carrier is always smaller than that of the second carrier.I have observed the txQueueSize  of DoReportBufferStatus in the second carrier and the third carrier;they are exactly equal.So I don't know why the transmission capacity is different so much.Could you give me some advice？
Thank you very much!

**Comment by tommasozugno** [comment]
Hi!
What do you mean by "so much"? What is the offered rate? Which kind of component carrier manager are you using? What is the bandwidth of each carrier? What channel model are you using? Notice that the two carriers may interfere if you use the same frequency.

Best, 
Tommaso

**Comment by fish-debug** [comment]
Hi Tommaso.
The UDP offered rate is 535Mbps.I use the MmWaveRrComponentCarrierManager and each carrier bandwidth is 100M.The first carrier frequency is 4.9G,and the second carrier frequency is 2.65G,the third carrier frequency is 2.55G.I use the MmWave3gppChannel channel model.

Today I have changed some parameters based on your suggestions. I change the the update period of&nbsp;MmWave3gppChannel channel model.The first image shows the result of 100ms update period,the second image shows the result 500ms update period&nbsp;,and the last image shows the result no upadte.As you can see, when the channel is updated the cc2 throughput&nbsp; drops dramatically.Could you give me some suggestions?
Thanks again,
Jun



&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tommaso Zugno"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上11:37
收件人:&nbsp;"nyuwireless-unipd/ns3-mmwave"<ns3-mmwave@noreply.github.com&gt;;
抄送:&nbsp;"浅笑"<1423954698@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nyuwireless-unipd/ns3-mmwave] carriers aggregation of mmwave (#136)




Hi!
 What do you mean by "so much"? What is the offered rate? Which kind of component carrier manager are you using? What is the bandwidth of each carrier? What channel model are you using? Notice that the two carriers may interfere if you use the same frequency.
 
Best,
 Tommaso

**Comment by tommasozugno** [comment]
I am not able to see the images. Btw, each carrier is attached to an independent channel, hence you may have different propagation condition in the two carriers (for instance, one carrier can be in LOS and the other in NLOS). I suggest you to run multiple independent simulations and average the results.
