### ISSUE TITLE
mmwave module ported to python?

### ISSUE THREAD

**Issue by superSaen36** [nyuwireless-unipd/ns3-mmwave#137]
Hi,

is there a python module built for mmwave? I'm working on a project where we use mostly python and I wanted to make sure there was python code available.

**Comment by mychele** [comment]
Hi Sean,
we periodically regenerate the python bindings for the mmWave module. You can take a look here for instructions on how to use ns-3 with python: https://www.nsnam.org/wiki/Python_bindings
Please reopen this issue if you encounter any issue or missing binding.
Michele
