### ISSUE TITLE
mmwave cc manager 

### ISSUE THREAD

**Issue by fish-debug** [nyuwireless-unipd/ns3-mmwave#140]
Hello！
I would like to ask some question about MmWaveBaRrComponentCarrierManager . The CC manager implemented in the MmWaveBaRrMacComponentCarrierManager class is
made aware of the bandwidth available to the different carriers during the simulation setup, and then, when it receives the BSRs from the RLC layer instances in the base station or the UE, it divides the reports according to the bandwidth ratio across the carriers.The code you have set
in line 592 of src/mmwave/model/mmwave-no-op-component-carrier-manager.cc

`for ( uint16_t i = 0;  i < numberOfCarriersForUe; i++)
        {
          NS_LOG_DEBUG ("m_bandwidthMap[i] / totalBandwidth = " << m_bandwidthMap[i] / totalBandwidth);
          params.retxQueueSize = params.retxQueueSize * m_bandwidthMap[i] / totalBandwidth;
          params.txQueueSize = params.txQueueSize * m_bandwidthMap[i] / ``totalBandwidth;`
But if the PCC and the SCC have the same bandwidth,the PCC txQueueSize is 1/2 of total and the SCC is only 1/4 of total txQueueSize,because the next CC the txQueueSize has changed.So I want to confirm this to you.

Thank you very much!

**Comment by tommasozugno** [comment]
Hi!
Yes, you are right. Thank you for reporting this issue, I will fix it.

Best, 
Tommaso

**Comment by tommasozugno** [comment]
Fixed https://github.com/nyuwireless-unipd/ns3-mmwave/commit/cbfb03d06c15aa82d0297a105bb373db88d1bb5c
