### ISSUE TITLE
Question about Multi-Connectivity

### ISSUE THREAD

**Issue by goksgie** [nyuwireless-unipd/ns3-mmwave#149]
Hello everyone!

I am working on a multi-connectivity enabled user association. In my scenarios, I consider a single LTE eNB base station and at least two mmWave gNB base stations. As I search through documentation, I realized it may not be possible to have multiple mmWave gNB stations supporting a single user at the same time. 
* My question is if the source code does not support multi-connectivity, would you direct me to implement this feature? If it is the other way around, would you guys point out where selecting suitable mmWave gNBs logic takes place?

Thank you!

**Comment by tommasozugno** [comment]
Hi! The current version of the code supports LTE-mmWave dual connectivity in which a single user is simultaneously connected to a LTE and a mmWave base station. Dual connectivity with multiple mmWave base stations is not supported. 
The main logic is handled by the LteEnbRrc class, which decides about the user-cell associations.

Best, 
Tommaso
