### ISSUE TITLE
Question about TCP

### ISSUE THREAD

**Issue by fish-debug** [nyuwireless-unipd/ns3-mmwave#150]
Hello everyone;
I'm working on a project about throughput under TCP .I added different delays between PDCP and RLC layers .I find that as the delay increases, so does the TCP RTT, but the TCP throughput decreases .I would like to ask if this phenomenon is correct ? In addition, I would like to ask how to change Core Network Latency? I want to do some comparative experiments by changing Core Network Latency.

Thank you very much.

**Comment by mychele** [comment]
Hi!
We also experienced that higher RTTs lead to lower throughput, as TCP becomes less reactive to the changes in the mmWave channel. Some results here, for example: https://ieeexplore.ieee.org/document/8613277
The core network latency can be changed with the S1uLinkDelay attribute in MmWavePointToPointEpcHelper: https://github.com/nyuwireless-unipd/ns3-mmwave/blob/cbfb03d06c15aa82d0297a105bb373db88d1bb5c/src/mmwave/helper/mmwave-point-to-point-epc-helper.cc#L183
Best,
Michele
