### ISSUE TITLE
Data rate

### ISSUE THREAD

**Issue by alissonzkv** [nyuwireless-unipd/ns3-mmwave#151]
Dear colleague,

I am not getting the expected data rate between 1 and 3 Gbps. Please, do you have any tips or code to help me?

I'm already using this snippet of code:
Time tNext (Seconds (1400 * 8 / datarate));
Simulator :: Schedule (tNext, &function, this);

and

Config::SetDefault ("ns3::LteRlcUmLowLat::MaxTxBufferSize", UintegerValue (1024 * 1024));
Config::SetDefault ("ns3::MmWaveHelper::RlcAmEnabled", BooleanValue(rlcAmEnabled));
Config::SetDefault ("ns3::LteRlcAm::PollRetransmitTimer", TimeValue(MilliSeconds(0.4)));
Config::SetDefault ("ns3::LteRlcAm::StatusProhibitTimer", TimeValue(MilliSeconds(1.0)));

How do you get data rates from 1 to 3 Gbps?

Best regards,
Alisson

**Comment by alissonzkv** [comment]
I am using a TCP application.

**Comment by tommasozugno** [comment]
Hi, can you please provide more details about your simulation?

**Comment by alissonzkv** [comment]
The topology is a UE connected to the eNB connected to the Remote Host. The UE sends packets on a TCP socket to the Remote Host.

But regardless of my scenario, I did not get the data rates expected even in the examples of mmwave.

**Comment by tommasozugno** [comment]
> The topology is a UE connected to the eNB connected to the Remote Host. The UE sends packets on a TCP socket to the Remote Host.

How do you compute the throughput? Can you please provide a plot of the SINR experienced by the user?

> But regardless of my scenario, I did not get the data rates expected even in the examples of mmwave.

What example did you try?

**Comment by alissonzkv** [comment]
> How do you compute the throughput? Can you please provide a plot of the SINR experienced by the user?

I compute by the time of send and receive. Regarding the SNR, the nodes are stopped and only 10 meters apart from each other.

> What example did you try?

I tested mainly on mmwave-tcp-example. But I tested the other examples as well.

**Comment by alissonzkv** [comment]
After all, please, what data rate or throughput did you get at mmwave-tcp-example?

**Comment by alissonzkv** [comment]
?

**Comment by mychele** [comment]
Hi,
the example has this line:
`  app->Setup (ns3TcpSocket, sinkAddress, 1000, 500, DataRate ("30Mb/s"));
`
which should set the source rate to 30Mb/s.
Best,
Michele

**Comment by alissonzkv** [comment]
Hi,
Thanks for the answer, Mychele. But, for example, if you set 2000Mbps or 3000Mbps, do you achieve this data rate when measuring the sending and receiving time? I did a test here and the data rate is not as expected.
Best,
Alisson

**Comment by tommasozugno** [comment]
I may need to change the settings of some parameters to improve TCP performance, try to add the following lines:

  // TCP settings
  Config::SetDefault ("ns3::TcpL4Protocol::SocketType", TypeIdValue (TcpCubic::GetTypeId ()));
  Config::SetDefault ("ns3::TcpSocketBase::MinRto", TimeValue (MilliSeconds (200)));
  Config::SetDefault ("ns3::Ipv4L3Protocol::FragmentExpirationTimeout", TimeValue (Seconds (0.2)));
  Config::SetDefault ("ns3::TcpSocket::SegmentSize", UintegerValue (1400));
  Config::SetDefault ("ns3::TcpSocket::DelAckCount", UintegerValue (1));
  Config::SetDefault ("ns3::TcpSocket::SndBufSize", UintegerValue (131072*400));
  Config::SetDefault ("ns3::TcpSocket::RcvBufSize", UintegerValue (131072*400));
  
  // RLC settings
  Config::SetDefault ("ns3::LteRlcUm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));
  Config::SetDefault ("ns3::LteRlcAm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));
  Config::SetDefault ("ns3::LteRlcUmLowLat::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));

**Comment by xpbeyo** [comment]
> Hi, Thanks for the answer, Mychele. But, for example, if you set 2000Mbps or 3000Mbps, do you achieve this data rate when measuring the sending and receiving time? I did a test here and the data rate is not as expected. Best, Alisson

Hey, I have the exact same problem. If I set the sending DataRate to 2Gb/s, I'm not observing the throughput close to that. In fact, the throughput is about 700Mb/s.



> I may need to change the settings of some parameters to improve TCP performance, try to add the following lines:
> 
> // TCP settings Config::SetDefault ("ns3::TcpL4Protocol::SocketType", TypeIdValue (TcpCubic::GetTypeId ())); Config::SetDefault ("ns3::TcpSocketBase::MinRto", TimeValue (MilliSeconds (200))); Config::SetDefault ("ns3::Ipv4L3Protocol::FragmentExpirationTimeout", TimeValue (Seconds (0.2))); Config::SetDefault ("ns3::TcpSocket::SegmentSize", UintegerValue (1400)); Config::SetDefault ("ns3::TcpSocket::DelAckCount", UintegerValue (1)); Config::SetDefault ("ns3::TcpSocket::SndBufSize", UintegerValue (131072_400)); Config::SetDefault ("ns3::TcpSocket::RcvBufSize", UintegerValue (131072_400));
> 
> // RLC settings Config::SetDefault ("ns3::LteRlcUm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024)); Config::SetDefault ("ns3::LteRlcAm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024)); Config::SetDefault ("ns3::LteRlcUmLowLat::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));

I applied these changes but it doesn't seem to help.

**Comment by mrahman2-vt** [comment]
Hi there,
We are from Virginia Tech, our research focuses mainly on Non-Terrestrial
Network/6G. Are you also working towards NTN, if so, could you please share
github page? Thank you.

Br
Mahfuz

**Comment by pagmatt** [comment]
> 

Hi Mahfuz,

it would be best to discuss this via e-mail, rather than commenting on this unrelated issue thread. Feel free to drop an e-mail at matteo.pagin.1@phd.unipd.it so that we can discuss this further.

Best,
Matteo
