### ISSUE TITLE
Throughput Calculation mmwave-tcp-building-example

### ISSUE THREAD

**Issue by Tarek-hassan024** [nyuwireless-unipd/ns3-mmwave#152]
Hello There,

I was working on congestion control with "mmwave-tcp-building-example" cc file. As I could determine the RTT, Cwnd and SINR but couldn't calculate the throughput. 

Could you please tell me the the method used to calculate the data rate and what are the inputs?

Thanks in Advance.
Tarek Hassan

**Comment by mychele** [comment]
Hi,
you can use the content of mmWave-tcp-data*, which logs received packet size in time.
Best,
Michele
