### ISSUE TITLE
Channel Frequency

### ISSUE THREAD

**Issue by rezapoorzare** [nyuwireless-unipd/ns3-mmwave#153]
Dear mychele,

First of all, Thank you so much because of your time and useful responses.
I would like to provide different slices in my 5G network. I have a question:
Is it possible to dedicate different channel frequencies to diffeent UEs in mmWave module? I mean for example, I have 5 UEs connecting to 1 gNb, so I want each one to work with a distinct frequency?

Many Thanks

**Comment by mychele** [comment]
Hi,
we recently published a work on slicing with carrier aggregation, please take a look here: https://arxiv.org/pdf/2005.10142.pdf
The answer to your question is that you should look into carrier aggregation.
Best,
Michele

**Comment by rezapoorzare** [comment]
Dear mychele,

Thanks a million for your response.

Regards,
