### ISSUE TITLE
SINR / Distance Relation

### ISSUE THREAD

**Issue by chusfer4** [nyuwireless-unipd/ns3-mmwave#160]
Hi,

In order to make a simple study of the SINR/Distance relation I have simulated an scenario of 1 UE moving away from the enb. At the end of the simulation ( distance2D = 505.5 ) I have 121.187 dB loss (8dB higher the expected ) and SINR = 15.62. 

Insn't the SINR suppossed to be so much lower? I have tought that the distance coverage by just 1 enb with mmwave would be so much smaller.

Thanks in advance.

**Comment by tommasozugno** [comment]
Hi, what channel model are you using?

**Comment by chusfer4** [comment]
Hi, I'm using MmWave3gppPropagationLossModel with this settings.

```
Config::SetDefault ("ns3::MmWave3gppPropagationLossModel::ChannelCondition", StringValue ("a"));
Config::SetDefault ("ns3::MmWave3gppPropagationLossModel::Scenario", StringValue ("UMi-StreetCanyon"));
Config::SetDefault ("ns3::MmWave3gppPropagationLossModel::OptionalNlos", BooleanValue (true));
Config::SetDefault ("ns3::MmWave3gppPropagationLossModel::Shadowing", BooleanValue (true)); 
Config::SetDefault ("ns3::MmWave3gppBuildingsPropagationLossModel::UpdateCondition", BooleanValue (true)); 
Config::SetDefault ("ns3::AntennaArrayModel::AntennaHorizontalSpacing", DoubleValue (0.5));
Config::SetDefault ("ns3::AntennaArrayModel::AntennaVerticalSpacing", DoubleValue (0.5));
Config::SetDefault ("ns3::MmWave3gppChannel::UpdatePeriod", TimeValue (MilliSeconds (50))); 
Config::SetDefault ("ns3::MmWave3gppChannel::DirectBeam", BooleanValue (true)); 
Config::SetDefault ("ns3::MmWave3gppChannel::Blockage", BooleanValue (true)); 
Config::SetDefault ("ns3::MmWave3gppChannel::PortraitMode", BooleanValue (true)); 
Config::SetDefault ("ns3::MmWave3gppChannel::NumNonselfBlocking", IntegerValue (4)); 

Config::SetDefault ("ns3::McUeNetDevice::AntennaNum", UintegerValue(16));
Config::SetDefault ("ns3::MmWaveEnbNetDevice::AntennaNum", UintegerValue(64));

mmwaveHelper->SetAttribute ("PathlossModel", StringValue ("ns3::MmWave3gppBuildingsPropagationLossModel"));
```

**Comment by chusfer4** [comment]
The Enb Tx Power is de default value, I think it's 30dbm, I think that the SINR value should be lower. Could you help me?

**Comment by tommasozugno** [comment]
You may be in LOS and have a high BF gain. However, I suggest you to run multiple independent simulations and evaluate the average metrics. The channel generation procedure involves multiple random processes and you may not be able to understand the general behavior from a single simulation run.

**Comment by chusfer4** [comment]
Hi, One question about the independent simulations, should I change any parameter on each simulation in orden to make it independent? such as,

`// rng things
  GlobalValue::GetValueByName ("runNumber", uintegerValue);
  uint32_t runSet = uintegerValue.Get ();
  uint32_t seedSet = 5;
  RngSeedManager::SetSeed (seedSet);
  RngSeedManager::SetRun (runSet);
  char seedSetStr[21];
  char runSetStr[21];
  sprintf (seedSetStr, "%d", seedSet);
  sprintf (runSetStr, "%d", runSet);`

On is enough to loop several times over the same code? 

Thanks in advance.

**Comment by tommasozugno** [comment]
You should change the run number, see https://www.nsnam.org/docs/manual/html/random-variables.html
