### ISSUE TITLE
SetSfAllocInfo scheduling for UE and eNB

### ISSUE THREAD

**Issue by lexsawada11** [nyuwireless-unipd/ns3-mmwave#161]
From my understanding, the TDD structure is alternating between DL and UL dynamically using SetSfAllocInfo based on the paper. I have been struggling to understand how this works, as I wanted to manually change the scheduling based on my algorithm that I have developed.

Can you advise on how to achieve that?
Thanks in advance.

**Comment by tommasozugno** [comment]
You could start from the class MmWaveFlexTtiMacScheduler and update it to implement your own scheduling algorithm. You may need to introduce some modifications in MmWaveEnb/UeMac and MmWaveEnb/UePhy to support the changes introduced in the scheduler.
