### ISSUE TITLE
DC / NSA

### ISSUE THREAD

**Issue by Uo23** [nyuwireless-unipd/ns3-mmwave#162]
Hi,

As long as I have understood in DC LTE enb is used to the control plane. 

¿Is this a king of NSA 5G use? ¿Or is just for the programming and the results are independent from the LTE conditions?

Thank you,

Regards

**Comment by tommasozugno** [comment]
The DC feature can be used to simulate a 5G NSA deployment in which the LTE base station acts as the master node and the mmWave cells act as secondary nodes.

**Comment by Uo23** [comment]
Is it possible to simulate Standalone deployment and study the latency and the handovers?

Thank you

**Comment by tommasozugno** [comment]
Yes, you can install mmwave-only devices through the methods InstallEnbDevice and InstallUeDevice of the MmWaveHelper class. In this way you can simulate a SA deployment operating at mmwaves
