### ISSUE TITLE
hi, I am trying to simulate simple epc lte model and using a EPS bearer, but I always get this error (assert failed. cond="bearerId == 0 || bid == bearerId", msg="bearer ID mismatch (2 != 1, the assumption that ID are allocated in the same way by MME and RRC is not valid any more", file=../src/lte/model/lte-enb-rrc.cc, line=439)

### ISSUE THREAD

**Issue by mohitsharma-eng** [nyuwireless-unipd/ns3-mmwave#164]
af: Entering directory `/home/ubuntu18/ns3-mmwave-2.0/build'
[2723/2773] Compiling scratch/mmwave-simple-epc.cc
[2732/2773] Linking build/scratch/mmwave-simple-epc
Waf: Leaving directory `/home/ubuntu18/ns3-mmwave-2.0/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (11.079s)
bandwidth 0 = 1.00001e+09
************* UPDATING CHANNEL MATRIX (instance 57) *************
************* UPDATING CHANNEL MATRIX (instance 76) *************
UE register to enb 1
UE register to enb 1
UE register to enb 1
UE register to enb 1
m_lteOutputFilename LteSwitchStats.txt
assert failed. cond="bearerId == 0 || bid == bearerId", msg="bearer ID mismatch (2 != 1, the assumption that ID are allocated in the same way by MME and RRC is not valid any more", file=../src/lte/model/lte-enb-rrc.cc, line=439
terminate called without an active exception
Command ['/home/ubuntu18/ns3-mmwave-2.0/build/scratch/mmwave-simple-epc'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

**Comment by tommasozugno** [comment]
Hi, are you running one of the scripts in the examples folder or a custom one?
