### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault for BuildingsHelper::MakeMobilityModelConsistent

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#165]
I am working on the UMi-StreetCanyon scenario, with 4 gNbs at the four vertices of a square, one Lte eNb at the center, and 10 UEs are moving with the help of random-walk mobility model. With the example given in the mc-twoenbs.cc I have generated 4 buildings in between two gNbs. So there are in total of 16 buildings.
My code compiled successfully but it gives ```Program received signal SIGSEGV, Segmentation fault```
On debugging with gdb I found
```bash
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4023cd5 in ns3::MobilityBuildingInfo::SetOutdoor (this=0x0)
    at ../src/buildings/model/mobility-building-info.cc:126
126	  m_indoor = false;
(gdb) bt
#0  0x00007ffff4023cd5 in ns3::MobilityBuildingInfo::SetOutdoor() (this=0x0)
    at ../src/buildings/model/mobility-building-info.cc:126
#1  0x00007ffff4048903 in ns3::BuildingsHelper::MakeConsistent(ns3::Ptr<ns3::MobilityModel>) (mm=...) at ../src/buildings/helper/buildings-helper.cc:101
#2  0x00007ffff4047d65 in ns3::BuildingsHelper::MakeMobilityModelConsistent()
    () at ../src/buildings/helper/buildings-helper.cc:70
#3  0x000055555557b4d8 in main(int, char**) (argc=1, argv=0x7fffffffdec8)
    at ../scratch/multicell-stat.cc:791

```

So the problem is on line 791 which is 
```bash
    BuildingsHelper::MakeMobilityModelConsistent ();
```
This method goes through the whole NodeList and, for each node in the list, calls BuildingsHelper::MakeConsistent() passing to it the MobilityModel of that node. 

Any suggestions for how to get rid of the signal SIGSEGV?

Thank you.

**Comment by tommasozugno** [comment]
Hi, you may need to aggregate a MobilityBuildingInfo to the MobilityModel of each node. See https://www.nsnam.org/docs/release/3.29/models/html/buildings-user.html#how-to-use-buildings-in-a-simulation
