### ISSUE TITLE
MmWaveBearerStatsCalculator for a particular Node

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#169]
Is it possible to use MmWaveBearerStatsCalculator for a particular node. According to wiki page on traces by enabling trace in the mmwavehelper  it will create trace files for entire simulation time for all the UEs and Enbs. However I am more interested in getting RLC/PDCP stats for a particular UE and the Enb on which that particular UE is connected?

**Comment by tommasozugno** [comment]
The simplest way is to use the RNTI field (4th column) to extract the metrics for a certain user. 
Instead, if you want the trace file to contain only the traces for a certain user, you should modify the class MmWaveBearerStatsConnector to connect the callbacks for the desired user (see the methods ConnectTracesUeIfFirstTime and ConnectTracesEnbIfFirstTime).

**Comment by arghasen10** [comment]
The RNTI changes dynamically. So, how can we determine if the RNTI stored in the trace file corresponds to the desired UE node?

Also,  for the second option that you have mentioned, if inside the callbacks ConnectTracesUeIfFirstTime or ConnectTracesEnbIfFirstTime we check if the imsi is equal to the desired ue (which in my case is always 9)  then build the model, will it work?

**Comment by arghasen10** [comment]
Just like this if we change this function this will always store trace for imsi 9 (which is desired value for my UE), right?
```c
void
MmWaveBearerStatsConnector::ConnectTracesEnbIfFirstTime (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
{
  if(imsi == 9)
{
NS_LOG_FUNCTION (this << context);

  //NB SRB1 traces are already connected

  //Connect PDCP and RLC for data radio bearers
  //Look for the RLCs
  std::string basePath = context.substr (0, context.rfind ("/")) + "/UeMap/" + std::to_string ((uint32_t) rnti);
  Config::MatchContainer rlc_container = Config::LookupMatches (basePath +  "/DataRadioBearerMap/*/LteRlc/");

  if (m_imsiSeenEnbDrb.find (imsi) == m_imsiSeenEnbDrb.end () && rlc_container.GetN () > 0)
    {
      //it is executed only if there exist at least one rlc layer
      m_imsiSeenEnbDrb.insert (imsi);
      ConnectDrbTracesEnb (context, imsi, cellId, rnti);
    }
}
}
```

**Comment by tommasozugno** [comment]
I never tried but it should work!

**Comment by arghasen10** [comment]
@tommasozugno It worked for me. 
Thank you.

**Comment by tommasozugno** [comment]
Great!
