### ISSUE TITLE
MCS value is not getting changed 

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#170]
I am working on simple TCP application where the client part is installed on the UE (with mc-netdevice) and the server is installed over the remotehost which is connected to PGW. In the simulation I have tried to generate RxPacket Trace at UE with the following code

```c
  Config::Connect ("/NodeList/"+std::to_string (ueNodes.Get (8)->GetId ())+"/DeviceList/*/
                                               MmWaveComponentCarrierMapUe /*/MmWaveUePhy/DlSpectrumPhy/
                                               RxPacketTraceUe",  MakeCallback (&traceuefunc));

void
traceuefunc (std::string path, RxPacketTraceParams params)
{
  std::fstream tracefile;
  std::string tracefilename = "tracefileue.csv";
  tracefile.open (tracefilename, std::ios::out | std::ios::app);
  tracefile << "DL," << Simulator::Now ().GetSeconds () << "," 
                      << params.m_frameNum << "," << +params.m_sfNum << "," 
                      << +params.m_slotNum << "," << +params.m_symStart << "," 
                      << +params.m_numSym << "," << params.m_cellId << "," 
                      << params.m_rnti << "," << +params.m_ccId << "," 
                      << params.m_tbSize << "," << +params.m_mcs << "," 
                      << +params.m_rv << "," << 10 * std::log10 (params.m_sinr) << "," 
                      << params.m_corrupt << "," <<  params.m_tbler << ","
                      << 10 * std::log10(params.m_sinrMin) << std::endl;
}
```
However the data generated shows that MCS value is mostly either 0 or 28 which is the minimum and maximum possible value. 
The UE is moving at very high speed (100m/s) with randomwalk model and I am using buildings propagation Model and I have added 20-30 buildings in my simulation. So I was expecting a fall in MCS value but the results shows something different. As the MCS value is either 0 or 28 the throughput as generated in the application also shows the variation as either very high (120 Mbps) or low(0Mbps). It does not show any value in between. This is not expected result. What might be going wrong here? 

Please help.
Thank you.

**Comment by tommasozugno** [comment]
Hi, could you please provide a plot of SINR vs simulation time?

**Comment by arghasen10** [comment]
@tommasozugno please check this.
![sinr_plot](https://user-images.githubusercontent.com/29783770/94133964-00721680-fe7f-11ea-9adf-bb8c8b1c71b2.png)

**Comment by arghasen10** [comment]
Hi @tommasozugno after many simulations I have found for a SINR value of 20-40dB MCS value at Downlink is constant i.e. 28 or 0. For a fall of SINR value in the range of -20 to +15 or +20dB, MCS value varries from 0 to 22, 24,26 like that. So my doubt is cleared.

This issue can be closed.

**Comment by tommasozugno** [comment]
Great!
