### ISSUE TITLE
eNb cellId vs node ID

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#171]
Hi,
So I am working on the mc-twoenbs.cc example. Whenever a handover is happening It logs on the terminal
`  NS_LOG_INFO ("Registered to eNB with CellId " << m_cellId);` 
I have a very simple question. The m_cellId value is unknown to end user. Can we somehow map it to eNb node id. So that it will be helpful to know exactly from which cell to which traget cell handover happened?
Thank you.

**Comment by tommasozugno** [comment]
The cell id is statically assigned to each gNB node by the helper, see the method MmWaveHelper::InstallSingleEnb. If you are using carrier aggregation, then each carrier has its own cell id.

**Comment by arghasen10** [comment]
Thank you. It is very clear now. Also with mmwaveEnvDev->GetCellId () I can retrieve it.
