### ISSUE TITLE
Can I measure radio related energy consumption in ns3 mmwave module?

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#172]
Hi,
I want to simulate mmwave module in different scenarios and want to produce a comparative study of energy consumption. Can we do that?
If not how should I proceed?

**Comment by tommasozugno** [comment]
You can use the trace file RxPacketTrace.txt to count the number of transmitted OFDM symbols and then multiply it by the energy per symbol.

**Comment by arghasen10** [comment]
@tommasozugno what should be the value of energy per symbol in mmwave?

**Comment by arghasen10** [comment]
@tommasozugno I want to focus on different states (such as IDLE, CONNECTED, Deep Sleep, Light Sleep, Micro Sleep, Data Transmission and Reception) and generate a rough energy consumption in these states. From the RxPacketTrace.txt file, one can only observe the simulation time when Ul or Dl data transfer happened. Can we somehow generate a c-DRX time from the RxPacketTrace.txt file? If I have the c DRX duration then I can figure out energy consumption (Power * time_taken) in different states such as Sleep, Data Transmission and Reception, Connected States. Already power consumption in different states is mentioned in [3GPP specs](https://www.3gpp.org/ftp/Specs/archive/38_series/38.840/38840-g00.zip)

**Comment by tommasozugno** [comment]
You can easily compute it from the transmission power and the symbol period. 
Currently the simulator does not support any DRX features, the UEs are either CONNECTED or IDLE.

**Comment by arghasen10** [comment]
@tommasozugno 
So is this relation correct?

Energy = Power * time
or, E = Tx Power(30dbm or 1 Watt) * symbols (Number of symbols allocated) * time(1 ms or size of subframe in time domain)

**Comment by tommasozugno** [comment]
You should multiply by the symbol period, not the subframe period. If you are using the [latest release](https://github.com/nyuwireless-unipd/ns3-mmwave/releases/tag/v3.0), which supports the NR frame structure, the symbol period depends on the numerology index you select. With numerology index 2 (the default one), the symbol period is 17.84 us (see https://www.sharetechnote.com/html/5G/5G_FrameStructure.html#OFDM_Symbol_Duration).

**Comment by arghasen10** [comment]
Thank you very much for clearing all my doubts.

**Comment by arghasen10** [comment]
@tommasozugno I want to implement DRX or cDRX in my simulation. As you told it is not implemented yet, Is there any possible way so that I can change the RRC State from CONNECTED_NORMALLY to a new state of RRC_INACTIVE. As per the 3GPP guidelines for every 160ms of a cycle I want to keep the UE in Connected mode for an on duration timer of 10ms and then I want to keep it in RRC_INACTIVE mode for rest of the time and if any PDCCH is received in that period I want to skip it. Can I implement this in my simulation?

**Comment by tommasozugno** [comment]
This module relies on the RRC models included in the lte module. You should modify the classes LteEnbRrc and LteUeRrc, which implements the RRC instances at the BS and UT side, respectively. You can have a look at the official ns-3 lte module documentation to better understand how these work.

**Comment by arghasen10** [comment]
@tommasozugno I have built a MmWave Energy Model mostly based on ns3 WifiRadioEnergyModel.
Can I create a pull request for your team's verification of it?

**Comment by tommasozugno** [comment]
Sure!
