### ISSUE TITLE
Question related to issue #152 Throughput Calculation mmwave-tcp-building-example 

### ISSUE THREAD

**Issue by erazemp** [nyuwireless-unipd/ns3-mmwave#173]
Hi. 
I was looking through the already closed issues about the calculation of the throughput in the mmwave-tcp-building-example #152.
The tcp-data* file logs the packets received in time but I cannot find a way to calculate throughput like in the following report: 
https://dl.acm.org/doi/pdf/10.1145/2915371.2915380
**A Framework for End-to-End Evaluation of 5G mmWave Cellular Networks in ns-3** under the section **5.2 TCP Performance over mmWave** 

Could you please provide additional information for the method of calculating the throughput for this example. 
Thank you in advance.

**Comment by tommasozugno** [comment]
You can use the script `read_traces.pl`. 
For example, to compute the downlink statistics at the PDCP layer you should run: `perl read_traces.pl -DlPdcpStats`
It outputs a file called `DlPdcpStats_sampled.txt` in which the first column is the time instant, the second is the received data, and the third is the instantaneous throughput.
