### ISSUE TITLE
Question: Modifications of the tcp-example for multiple UE devices

### ISSUE THREAD

**Issue by erazemp** [nyuwireless-unipd/ns3-mmwave#174]
Would it be possible to modify the mmwave-tcp-example for it to work for multiple UEs, for example up to 100 UE devices or maybe only for 10. 
I have tried to install 10 devices in a container and modify the code after the comment **//install and start applications on UEs and remote host** by creating multiple sink addresses and app setups and for each UE it's own txt file and so on with for loops but i don't know if this is the right way and if this affects the program's accuracy, etc.
1. Is there a simpler way to display the results and also be able to identify for which UE, rather than creating 10 - 100 different files for each UE? 
2.  How is the DlPdcpStats.txt file formatted column wise? (for 10 UEs in the 4th column it displays the UE number only once at the beginning and then only shows for the number 1 --> look at picture)
3. Is it possible to then get the throughput for each UE since the script read_traces.pl doesn't provide the identification of the UE device?
![DlPdcpStats](https://user-images.githubusercontent.com/36954864/97193546-6b2daf00-17a9-11eb-9ef1-1481fb731a81.jpg)

**Comment by tommasozugno** [comment]
1) You can modify the example in such a way that all the app traces are printed in the same file. In this case you would need an ID (e.g., node ID, IMSI or RNTI) to differentiate the logs of different users. 

2) See https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces

3) You can keep only the lines related to the desired UE and then run read_traces.pl. You can use awk for this, see https://www.tim-dennis.com/data/tech/2016/08/09/using-awk-filter-rows.html
