### ISSUE TITLE
can some one generously code this paper?? or even part of it

### ISSUE THREAD

**Issue by vamsnaidu** [nyuwireless-unipd/ns3-mmwave#175]
how do we model SINR in the lte cellular (3 cell) and map CQI VALUES TO MCS allocation based on SINR

[Optimization Method for the Joint Allocation of Modulation Schemes, Infocom, 2011, IMP IMP IMP (1).pdf](https://github.com/nyuwireless-unipd/ns3-mmwave/files/5445166/Optimization.Method.for.the.Joint.Allocation.of.Modulation.Schemes.Infocom.2011.IMP.IMP.IMP.1.pdf)

**Comment by tommasozugno** [comment]
This module is used to simulate 5G mmWave cellular networks, it includes an LTE model but is used to simulate non-standalone deployments. The mapping between SINR and CQI and between CQI and MCS is done in the class MmWaveAmc, the methods are CreateCqiFeedbacksTdma and GetMcsFromCqi, respectively.
