### ISSUE TITLE
Question about qd-channel-full-stack-example.cc

### ISSUE THREAD

**Issue by asydney** [nyuwireless-unipd/ns3-mmwave#178]
Not sure who to contact about this one so I'll post it here. Please let me know where the best forum is to send such questions. 

I was attempting to run this example "qd-channel-full-stack-example.cc" from the list of examples provided (Here is a url to it: https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/src/mmwave/examples/qd-channel-full-stack-example.cc).  In the main function, the following directory is specified "src/spectrum/model/QD/" and with the scenario "Indoor1". However, I can't seem to locate this directory. Can you kindly provide feedback?

Thanks,
Ali

**Comment by tommasozugno** [comment]
You need the qd-channel extension, you can find a beta version here https://github.com/signetlabdei/qd-channel

**Comment by asydney** [comment]
That was super quick. Thanks!
