### ISSUE TITLE
Question: Frequency, large data set of the mmwave-tcp-example

### ISSUE THREAD

**Issue by erazemp** [nyuwireless-unipd/ns3-mmwave#179]
1.) I am wondering if is it possible to change the mmwave-tcp-exaple so it would support frequencies lower than 6Ghz - maybe with 3gpp module. I would like to test basically the same thing as in the tcp-example but also with lower frequencies. How can I do that?

2.) Is there a way to reduce the amount of data generated in RxPacketTrace, DlPdcpStats, Rtt,... So that it would be less frequent for example between 0.1 and 0.2 second (less generated rows of data) because if I create 5 Ue devices the simulation takes more than 1,5 hours for a 6 second transmission.

I am thankful for your time.

These are my settings for now:
Config::SetDefault ("ns3::LteRlcUm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));
  Config::SetDefault ("ns3::LteRlcAm::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));
  Config::SetDefault ("ns3::LteRlcUmLowLat::MaxTxBufferSize", UintegerValue (10 * 1024 * 1024));
   
  Config::SetDefault ("ns3::MmWavePhyMacCommon::ResourceBlockNum", UintegerValue (1));
  Config::SetDefault ("ns3::MmWavePhyMacCommon::ChunkPerRB", UintegerValue (72));
  Config::SetDefault ("ns3::MmWaveHelper::RlcAmEnabled", BooleanValue (rlcAmEnabled));
  Config::SetDefault ("ns3::MmWaveHelper::HarqEnabled", BooleanValue (harqEnabled));
  Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::HarqEnabled", BooleanValue (true));
  Config::SetDefault ("ns3::MmWaveFlexTtiMaxWeightMacScheduler::HarqEnabled", BooleanValue (true));
  Config::SetDefault ("ns3::MmWaveFlexTtiMacScheduler::HarqEnabled", BooleanValue (true));
  Config::SetDefault ("ns3::MmWaveBeamforming::LongTermUpdatePeriod", TimeValue (MilliSeconds (100.0)));
  Config::SetDefault ("ns3::LteRlcAm::PollRetransmitTimer", TimeValue (MilliSeconds (4.0)));
  Config::SetDefault ("ns3::LteRlcAm::ReorderingTimer", TimeValue (MilliSeconds (2.0)));
  Config::SetDefault ("ns3::LteRlcAm::StatusProhibitTimer", TimeValue (MilliSeconds (1.0)));
  Config::SetDefault ("ns3::LteRlcAm::ReportBufferStatusTimer", TimeValue (MilliSeconds (4.0)));
  //Config::SetDefault ("ns3::LteRlcAm::MaxTxBufferSize", UintegerValue (20 * 1024 * 1024));

  //TCP settings
  Config::SetDefault ("ns3::TcpL4Protocol::SocketType", TypeIdValue (TcpCubic::GetTypeId ()));
  Config::SetDefault ("ns3::TcpSocketBase::MinRto", TimeValue (MilliSeconds (200)));
  Config::SetDefault ("ns3::Ipv4L3Protocol::FragmentExpirationTimeout", TimeValue (Seconds (0.2)));
  Config::SetDefault ("ns3::TcpSocket::SegmentSize", UintegerValue (1400));
  Config::SetDefault ("ns3::TcpSocket::DelAckCount", UintegerValue (1));
  Config::SetDefault ("ns3::TcpSocket::SndBufSize", UintegerValue (131072400));
  Config::SetDefault ("ns3::TcpSocket::RcvBufSize", UintegerValue (131072400))
  double stopTime = 5.9;
  double simStopTime = 7.00;

**Comment by tommasozugno** [comment]
> 1.) I am wondering if is it possible to change the mmwave-tcp-exaple so it would support frequencies lower than 6Ghz - maybe with 3gpp module. I would like to test basically the same thing as in the tcp-example but also with lower frequencies. How can I do that?

A simple approach would be to properly set the carrier frequency (thee 3GPP channel model supports frequencies between 0.5 and 100 GHz) and to use antenna arrays with a single antenna element, maybe excluding the beamforming part.

> 2.) Is there a way to reduce the amount of data generated in RxPacketTrace, DlPdcpStats, Rtt,... So that it would be less frequent for example between 0.1 and 0.2 second (less generated rows of data) because if I create 5 Ue devices the simulation takes more than 1,5 hours for a 6 second transmission.

You should modify the classes which generate those file (MmWaveBearerStatsCalculator and MmWavePhyTrace). However, the main bottleneck of the simulation is the generation of the channel matrices and the computation of the beamforming gain. You could try to decrease the channel update time through the attribute UpdateTime of the class ThreeGppChannelModel but consider that you may end up with less accurate results if you are simulating high mobility scenarios.
