### ISSUE TITLE
Integrated-Access Backhaul (IAB) feature

### ISSUE THREAD

**Issue by aSaFLaViX** [nyuwireless-unipd/ns3-mmwave#180]
**Hello,**
I'm an MSc student from BGU University, and my study is on AI-based scheduler with IAB technology.
I already saw that there is another mmWave module with the IAB feature, but that module is without handover functionality and it is no longer getting updated since 2018 either.

Does someone know if the IAB feature will be available in this module in the future? or maybe someone made it possible and can refer me to it?

**Many thanks and regards,
Asaf**

**Comment by tommasozugno** [comment]
Hi, we are considering the possibility to integrate the IAB feature but we don't know when it will happen because it may require a considerable amount of work. If you are interested and you want to help, let us know!

Best,
Tommaso

**Comment by aSaFLaViX** [comment]
Hello again,
I want to help with this feature!
Where and how can I start?

Best,
Asaf

‫בתאריך יום ד׳, 25 בנוב׳ 2020 ב-10:30 מאת ‪Tommaso Zugno‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by tommasozugno** [comment]
In my opinion, the easiest way would be to identify the features that have been implemented in the IAB module and try to port them in this module. For instance, I would start by defining the classes implementing the IAB devices and to include the methods to install them in the MmWaveHelper class
