### ISSUE TITLE
How to add cDRX in this module?

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#181]
Hi, I want to implement cDRX in this module. Can you help how to start working on this?

**Comment by tommasozugno** [comment]
Hi, I believe you should modify the RRC layer model to account for the cDRX state and include the procedures that are needed to switch to this state. The RRC layer model is implemented in the classes LteEnbRrc (the gNB part) and LteUeRrc (the UE part). Also, MmWavLteRrcProtocolReal handles the transmission of RRC messages between the UE and the gNB.

**Comment by arghasen10** [comment]
Can I consider the SpectrumPhy IDLE state as RRC_CONNECTED_INACTIVE state ?
