### ISSUE TITLE
5G bandwidths

### ISSUE THREAD

**Issue by Gabriela3000** [nyuwireless-unipd/ns3-mmwave#182]
Hello
In 5G we have bandwidths as 5,10,15,20,25,30,40,50, 100,200, 400 MHz.
How we can specify these values in the code?
I really appreciate your time and answer.
Best wishes

**Comment by tommasozugno** [comment]
You can use the attribute "Bandwidth" of the class MmWavePhyMacCommon. Insert the following line at the beginning of your simulation script: 

`Config::SetDefault ("MmWavePhyMacCommon::Bandwidth", DoubleValue (x));
`
where x is the desired value.

**Comment by Gabriela3000** [comment]
Hello and thank you very much for your answer
However, there is no Bandwidth parameter in the mmwavemaccommon.cc file and I did not find that. I see ResourceBlockNum, ChunkPerRB, ChunkWidth, ... but not bandwidth.
Could you please clear this for me.
I really appreciate your reply.
Best wishes

**Comment by tommasozugno** [comment]
Perhaps you are usings an older versione of the module, please consider to update it to [the latest release](https://github.com/nyuwireless-unipd/ns3-mmwave/releases/tag/v3.0). Alternatively, if you want to keep using the older version, you can properly set the value of ChunkPerRB based on the desired bandwidth, as it is done in [this example](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/592c1e4675238c7fc14f3f19127d54b717d10c1b/src/mmwave/examples/mmwave-ca-diff-bandwidth.cc#L83)

**Comment by Gabriela3000** [comment]
Thank you very much for your fast answer. Yes the version was old. I am going to download the new version.
Best wishes
