### ISSUE TITLE
operating frequency

### ISSUE THREAD

**Issue by Gabriela3000** [nyuwireless-unipd/ns3-mmwave#183]
Hello
Could you please kindly let me know what is the difference between frequency in MmWavePhyMacCommon (CenterFreq) and in ThreeGppChannelModel. I know that the CenterFreq is the operating frequency of mmwave, but I don't understand its relationship with the frequency in ThreeGppChannelModel. Should their values be different or similar?

I really appreciate your time and answer.
Best wishes

**Comment by tommasozugno** [comment]
They should be the same. This is done by the MmWaveHelper when installing the mmWave devices (see the method MmWaveChannelInitialization ())

**Comment by Gabriela3000** [comment]
Thank you very much for your fast reply
Best wishes
