### ISSUE TITLE
Distance vs SINR/Throughput NS3 RxPacketTrace.txt

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#184]
RxPacketTrace.txt can give us SINR of the channel for the whole simulated time. Is there also a way to get throughput from this file? 
I would really appreciate if anyone could give me even a small guidance on this topic...

**Comment by tommasozugno** [comment]
[Here](https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces) you can find the description of the fields reported in RxPacketTrace. 
To compute the throughput you can use [this](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/scripts/read_traces.pl) script, but it takes as input the traces generated by APP, PDCP or RLC layer. 
If you want to compute the throughput starting from RxPacketTrace you should write your own script.

Best, 
Tommaso
