### ISSUE TITLE
Transmit Power parameter in MmWaveHelper

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#185]
Some of the helper classes of ns3 has this feature of setting the transmit power.
1. ns3::YansWifiPhy, 
2. ns3::UanPhyGen, 
3. ns3::UanPhyDual, 
4. ns3::AcousticModemEnergyModel 

I am working on mmWave module of ns3. Is there a way to set the transmit power in this module too?
I would really appreciate if anyone could give me even a small guidance on this topic...

**Comment by tommasozugno** [comment]
You can use the attribute  TxPower of the classes MmWaveEnbPhy and MmWaveUePhy
