### ISSUE TITLE
Building module for mmWave frequencies

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#187]
As i see in the building module, the external walls penetration loss for buildings is according to COST 231 model. And this model only operates at 900 - 1200 MHz. 
Could you please let me now if there are any changes made on the mmWave module to include penetration losses at higher frequencies (28-100 GHz). 

I would really appreciate any kind of suggestion.

**Comment by tommasozugno** [comment]
Unfortunately not yet

**Comment by RahulSinghGulia** [comment]
Thank you Tommaso...
