### ISSUE TITLE
addind imsi to RxPacketTrace.txt

### ISSUE THREAD

**Issue by YoussefMoukabaa** [nyuwireless-unipd/ns3-mmwave#188]
Hii,
I am trying to add the IMSI to the RxPacketTrace.txt by modifying it and RxPacketTrace.h. However, When running I encounter the following error:

**lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status

lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status

lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status

lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status

lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status

lib/libns3-dev-mmwave-debug.so: undefined reference to `ns3::mmwave::MmWavePhyRxTrace::ReportInterferenceTrace(unsigned long, ns3::SpectrumValue&)'
collect2: error: ld returned 1 exit status**
and i don't know what is the problem. Please your support

Youssef Moukabaa

**Comment by tommasozugno** [comment]
Hi Youssef,
It is quite hard to find the problem without the code. It seems that your linker is not able to find the definition of the method `ReportInterferenceTrace`.

Best, 
Tommaso
