### ISSUE TITLE
Questions: ENB, SINR and Throughput

### ISSUE THREAD

**Issue by erazemp** [nyuwireless-unipd/ns3-mmwave#190]
Hi I am analyzing the TCP-example with some modifications and am wondering if you can help me answer this questions so I can better understand the simulations and their results.
1.) Could you tell me the main characteristics of the ENB (base station). Such as maximum throughput speed. Can I access the code where the enb is generated?
I have tested the max throughput with 1 UE and set the speed to 10Gb/s and it came out that the max is around 2.5Gb/s. I am wondering if there are any more important characteristics. 
2.) I noticed that if I run the same simulation twice or more I get the same SINR graph. Is this because of the fixed seed when the simulation is generated? If so is it possible to create a random seed?
3.) When testing the throughput speeds I noticed a big spike at the beginning of the simulation which for a brief moment exceeds the maximum set throughput of the device and then stabilizes. Is there a specific reason to this behavior?
The graphs for reference:
![tp2_01](https://user-images.githubusercontent.com/36954864/102571969-33791e80-40eb-11eb-8f71-099f86ae6397.png)
![tp2_01](https://user-images.githubusercontent.com/36954864/102572009-4be93900-40eb-11eb-9584-a322ad27d394.png)

I very much appreciate your time, Thank you.

**Comment by tommasozugno** [comment]
Hi, 
> 1.) Could you tell me the main characteristics of the ENB (base station). Such as maximum throughput speed. Can I access the code where the enb is generated?

Each base station is represented by an instance of `MmWaveEnbNetDevice`. These objects are generated by the method `InstallSingleEnbNetDevice` of the class `MmWaveHelper`.

> 2.) I noticed that if I run the same simulation twice or more I get the same SINR graph. Is this because of the fixed seed when the simulation is generated? If so is it possible to create a random seed?

Yes, the random seed is controlled by the RngRun parameter. You can set this parameter through the command line, e.g., `./waf --run "your-script --RngRun=1"`

> 3.) When testing the throughput speeds I noticed a big spike at the beginning of the simulation which for a brief moment exceeds the maximum set throughput of the device and then stabilizes. Is there a specific reason to this behavior?

Usually this is because the applications start generating traffic before the connection procedure is completed and fill up the buffers. The throughput remains "higher" util the buffers are emptied.

**Comment by xpbeyo** [comment]
> Hi I am analyzing the TCP-example with some modifications and am wondering if you can help me answer this questions so I can better understand the simulations and their results. 1.) Could you tell me the main characteristics of the ENB (base station). Such as maximum throughput speed. Can I access the code where the enb is generated? I have tested the max throughput with 1 UE and set the speed to 10Gb/s and it came out that the max is around 2.5Gb/s. I am wondering if there are any more important characteristics. 2.) I noticed that if I run the same simulation twice or more I get the same SINR graph. Is this because of the fixed seed when the simulation is generated? If so is it possible to create a random seed? 3.) When testing the throughput speeds I noticed a big spike at the beginning of the simulation which for a brief moment exceeds the maximum set throughput of the device and then stabilizes. Is there a specific reason to this behavior? The graphs for reference: ![tp2_01](https://user-images.githubusercontent.com/36954864/102571969-33791e80-40eb-11eb-8f71-099f86ae6397.png) ![tp2_01](https://user-images.githubusercontent.com/36954864/102572009-4be93900-40eb-11eb-9584-a322ad27d394.png)
> 
> I very much appreciate your time, Thank you.

Hi, I'm very curous in how you obtained this throughput. For me, mmwave-tcp-example and mmwave-tcp-building-example both somehow capped at at throughput of about 700Mb/s for any high sending DataRate that I set, for example, 1Gb/s, 2Gb/s or even 100Gb/s. If you'd like you can email me at shanchun.yi@mail.utoronto.ca
