### ISSUE TITLE
How to lower down network throughput intentionally?

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#191]
Hello, 
In my simulation scenario, I have considered 10 gNbs with an inter-cell distance of 100m. I have used the random-walk mobility model for the UE (16km/h). Also, I have used buildings in my simulation. But according to my results mostly I observed it can provide full coverage and satisfy the required capacity. 

I want to build my scenario in such a way so that I can lower down the n/w throughput.
Is there any way to calibrate the propagation model for this?

Also, as the UE is moving, is there any doppler effect considered?
Have you considered Multipath fading in the propagation loss model?

**Comment by mychele** [comment]
Hi!
There are a few things you can try to decrease the received power:
- change the antenna configuration (with fewer elements for each antenna array (after you create the helper, you can use the SetMmWaveEnb/UeNetDeviceAttribute methods to change the AntennaNum attribute)
- change the beamforming method
- change the bandwidth
- increase the distance of your users
- etc
For channel model details (in the latest release) please take a look at https://arxiv.org/pdf/2002.09341.pdf
I hope this helps.
Michele

**Comment by arghasen10** [comment]
What can be the maximum distance between UE and gNb??

**Comment by mychele** [comment]
There is not a maximum distance in principle, it depends on several factors (including the scenario, beamforming and antenna array configuration, etc).

**Comment by arghasen10** [comment]
@mychele In the previous ns3-mmwave release we had the option to enable Shadowing, NLOS with   
> Config::SetDefault ("ns3::MmWave3gppPropagationLossModel::OptionalNlos", BooleanValue (true));

This option is not available in the latest release. How  can we enable these features?

**Comment by tommasozugno** [comment]
Config::SetDefault ("ns3::ThreeGppPropagationLossModel::ShadowingEnabled", BooleanValue (true));

**Comment by arghasen10** [comment]
@tommasozugno Thanks.
For enabling NLOS what we need to do, as this attribute is not available with the  ThreeGppPropagationLossModel ?

**Comment by tommasozugno** [comment]
This attribute enables shadowing for both LOS and NLOS
