### ISSUE TITLE
Deprecated commands?

### ISSUE THREAD

**Issue by alissonzkv** [nyuwireless-unipd/ns3-mmwave#192]
Hello, 

I was using these two commands normally in the previous version of mmwave with ns-3.29:

**Config::SetDefault ("ns3::MmWavePhyMacCommon::ResourceBlockNum", UintegerValue(1));
Config::SetDefault ("ns3::MmWavePhyMacCommon::ChunkPerRB", UintegerValue(72));**

However, I can no longer use them in the newer version of mmwave.

Could someone please help me to set these values in a new way in the newest version of mmwave?

Best regards,
Alisson

**Comment by tommasozugno** [comment]
Hi, in the [latest release](https://github.com/nyuwireless-unipd/ns3-mmwave/releases/tag/v3.0) we updated the frame structure and the PHY layer numerology to be compliant with the 3GPP NR specifications. We also updated the class MmWavePhyMacCommon to enable a more user-friendly configuration of the different parameters. For instance, if you need to change the  bandwidth or the PHY layer numerology, you just need to configure the attributes "Bandwidth" and "Numerology". 
Let me know if this solves your issue.

Best, 
Tommaso

**Comment by alissonzkv** [comment]
Please, what values should I put in Bandwidth and Numerology to have the same configuration that I had?

**Comment by tommasozugno** [comment]
I am afraid that it is not possible to easily set the old configuration. The fact is that the old frame structure and PHY layer numerology were very different from the 3GPP NR specifications and therefore we decided to update them. 
I recommend you to use the new version, you just need to remove the two lines above. If by all means you need the old configuration please use the previous release.
