### ISSUE TITLE
Error while running mmwave-vehicular-link-adaptation-example.cc

### ISSUE THREAD

**Issue by Liz2004** [nyuwireless-unipd/ns3-mmwave#193]
Hi, I am trying to run this file as it is but it always throws an error as follows during runtime:

aborted. msg="EpcTftClassifier::Classify - Unknown IP type...", file=../src/lte/model/epc-tft-classifier.cc, line=257
terminate called without an active exception
Command ['/path/to/file/mmwave-vehicular-link-adaptation-example'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --gdb").

**Comment by tommasozugno** [comment]
I think this is related to the millicar module, please consider opening an issue [here](https://github.com/signetlabdei/millicar)
