### ISSUE TITLE
Enabling OhBuildingsPropagationLossModel.cc in buildings model.

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#194]
Hello team,

I know that building propagation model can be used with two propagation models. HybridBuildingsPropagationLossModel.cc and OhBuildingsPropagationLossModel.cc.

In my building model with mobility, I want to use just the Okumara Hata model, which is in OhBuildingsPropagationLossModel.cc. Does anyone has any suggestions on enabling this model for my Building propagation model work. 

Thanks & Regards,
Rahul

**Comment by tommasozugno** [comment]
You can use the method MmWaveHelper::SetPathlossModelType to change the propagation loss model
