### ISSUE TITLE
Data bearer error

### ISSUE THREAD

**Issue by Gabriela3000** [nyuwireless-unipd/ns3-mmwave#196]
Hello 
When I try to make a data bearer as follow:
     for (uint32_t u = 0; u < ueNodes.GetN(); ++u)
     {
    	 Ptr<NetDevice> ueDevice = uemmWaveDevs.Get (u);

		 enum EpsBearer::Qci q = EpsBearer::GBR_CONV_VOICE;
		 EpsBearer bearer (q);
		 mmwhelper->ActivateDataRadioBearer (ueDevice, bearer);
     }

I get the following error:
assert failed. cond="bearerId == 0 || bid == bearerId", msg="bearer ID mismatch (2 != 1, the assumption that ID are allocated in the same way by MME and RRC is not valid any more", file=../src/lte/model/lte-enb-rrc.cc, line=439
terminate called without an active exception

Could you please let me know how to fix the issue? 
Thanks in advance

**Comment by tommasozugno** [comment]
This is strange, I would need more details to understand what is going on.
