### ISSUE TITLE
Path Loss when a building is placed between a Tx and Rx

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#197]
Hello everyone,

In HybridBuildingsPropagationLossModel.cc, when a Tx and Rx are outside  (in short range), it will just calculate the path loss from ITU model. 
But what if a building is placed between them. How can I add that building external wall loss also into the path loss model? 

I know that IsLineOfSightBlocked() function from the buildings-channel-condition-model.cc model can be used to find if there is a LOS or NLOS between 2 nodes. But since GetLoss() and IsLineOfSightBlocked() takes 2 different types of arguments, how can I merge them together to generate a path loss that will also add the building material penetration losses too? 

I know I have asked a lot over here. But a small guidance will also be sufficient, as I am pretty much clear about the background model of NS3 for building. But my C++ coding skills are lacking here. 

Thanks & Regards,
Rahul

**Comment by tommasozugno** [comment]
Hi,
BuildingsChannelConditionModel is not related to HybridBuildingsPropagationLossModel, it can be used only with ThreeGppPropagagionLossModel (see [here](https://www.nsnam.org/docs/models/html/propagation.html#channelconditionmodel)). I am not familiar with HybridBuildingsPropagationLossModel, I am sorry.

**Comment by RahulSinghGulia** [comment]
Yes, BuildingsChannelConditionModel & ThreeGppPropagagionLossModel are basically used to get the LOS/NLOS condition between a Tx and Rx. 
HybridBuildingsPropagationLossModel is basically used to find the path loss based on the location of Tx & Rx, considering the losses from the buildings.
for Reference: https://www.nsnam.org/docs/models/html/buildings-design.html#the-building-class

I cleared my error few days back. Thanks tom.

**Comment by tommasozugno** [comment]
BuildingsChannelConditionModel is used to determine the LOS condition, while ThreeGppPropagagionLossModel is used to compute the pathloss based on the condition (don't be confused with ThreeGppChannelConditionModel, which is another model to determine the LOS condition). 

I am not sure but I think HybridBuildingsPropagationLossModel does both the things, i.e., it determines the channel condition and it computes the pathloss. In particular, it does not make use of BuildingsChannelConditionModel.
