### ISSUE TITLE
calling ReportCurrentCellRsrpSinr

### ISSUE THREAD

**Issue by Gabriela3000** [nyuwireless-unipd/ns3-mmwave#198]
Hello
Could you please let me know if the following can properly call ReportCurrentCellRsrpSinr because I get an empty output:

ReportCurrentCellRsrpSinr (Ptr<OutputStreamWrapper> stream,uint64_t imsi, SpectrumValue& sinr, SpectrumValue& power);

Ptr<OutputStreamWrapper> stream;
Config::ConnectWithoutContext 
("/NodeList/*/DeviceList/*/$ns3::MmWaveUeNetDevice/ComponentCarrierMapUe/*/MmWaveUePhy/ReportCurrentCellRsrpSinr", MakeBoundCallback (&ReportCurrentCellRsrpSinr,stream));

Thank you very much

**Comment by tommasozugno** [comment]
Hi, 
I never tried to use that trace source, I am not able to help you without further details on what you are trying to do. 

Best, 
Tommaso

**Comment by Gabriela3000** [comment]
Hi
Thank you very much for reply
I am using this to measure SINR 
Best regards,

**Comment by tommasozugno** [comment]
You can use the file RxPacketTrace.txt which should be automatically generated. See [here](https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces) to understand the meaning of the different fields.

**Comment by Gabriela3000** [comment]
Hello and thank your very much for the answer.
If we want to measure RSRP, we still need to use ReportCurrentCellRsrpSinr function, am I right? 
But the way I mentioned I used the function results in an empty output.
Could you please guide me in this regard?
Best regards
