### ISSUE TITLE
Assign different central frequencies to different eNodeBs

### ISSUE THREAD

**Issue by sladrond** [nyuwireless-unipd/ns3-mmwave#199]
Hi all!

I'm trying to build a scenario with multiple eNodeBs, but I'm worried about the possible interference that could happen between them so I'm trying to assign a different frequency per eNodeB. Could you please let me know how can I do this?

Thanks!

**Comment by tommasozugno** [comment]
In principle this is possible but I don't know if it can be done easily. You could try to create different MmWaveHelper objects, one for each BS and call InstallEnbNetDevice multiple times. This will create multiple channels, one for each BS
