### ISSUE TITLE
Comparing old and new (3GPP) channel model

### ISSUE THREAD

**Issue by AleksandraLo** [nyuwireless-unipd/ns3-mmwave#20]
I'm trying to compare old MmWaveBeamforming channel model with the new 3GPP one.

In order to switch to the old one, is it enough to set these attributes:

mmWaveHelper->SetAttribute ("PathlossModel", StringValue ("ns3::MmWavePropagationLossModel"));
mmWaveHelper->SetAttribute ("ChannelModel", StringValue ("ns3::MmWaveBeamforming"));

i'm not getting any comparable results when using this changes and with the old module, so is there anything else I'm missing?

Thank you!

**Comment by MengleiZhang** [comment]
Hi,

It is enough.

Menglei
