### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ericliujian** [nyuwireless-unipd/ns3-mmwave#200]
I have a question, I download ns3-mmwave and run ./waf build but I saw this:
![Screenshot from 2021-02-05 14-16-03](https://user-images.githubusercontent.com/25019274/107078748-c0bc2380-67bc-11eb-93b9-3233822363f7.png)
![Screenshot from 2021-02-05 14-16-27](https://user-images.githubusercontent.com/25019274/107078754-c3b71400-67bc-11eb-82e1-fb6c65865115.png)

Could you please tell me why? I did not make any change. Thank you for your help.

**Comment by tommasozugno** [comment]
./waf configure --disable-python && ./waf build
