### ISSUE TITLE
SINR from UE-eNodeB pair

### ISSUE THREAD

**Issue by sladrond** [nyuwireless-unipd/ns3-mmwave#201]
Hi there!

I'm currently doing some experiments in which I require to know the SINR between UE and base station. I found that this is stored in the mmwave-enb-phy class but not public and not as getSINR or something similar. Would you suggest any other method to get the instant SINR of a pair of devices? 

Thanks!

**Comment by mychele** [comment]
Hi Sharon,
this would depend on where you need to access the information - can you tell us more on your use case? 
Michele

**Comment by sladrond** [comment]
Hi Michele, 

I'm planning to mimic handover of mmwave without LTE base station, so let's say I'm sending an image from the UE to a remote host through a specific eNodeB, so before sending the image I'd like to check the SINR and in case it is <-5 stop using that link. This is why I'd like to obtain the SINR at a given time. Hope this helps to clarify the question

Thanks!

**Comment by dhruvik1999** [comment]
Hey!

You can use the ReportCurrentCellRsrpSinr callback function to get the SINR values of the channel. This callback function will execute whenever a new SINR value is updated. You can save this SINR value locally and use it before sending the image.

Dhruvik

**Comment by Gabriela3000** [comment]
Dear dhruvik1999
Could you please let me know how to properly call ReportCurrentCellRsrpSinrif functions? I do as follow to all it but I get an empty output:

ReportCurrentCellRsrpSinr (Ptr stream,uint64_t imsi, SpectrumValue& sinr, SpectrumValue& power);

Ptr stream;
Config::ConnectWithoutContext
("/NodeList//DeviceList//$ns3::MmWaveUeNetDevice/ComponentCarrierMapUe/*/MmWaveUePhy/ReportCurrentCellRsrpSinr", MakeBoundCallback (&ReportCurrentCellRsrpSinr,stream));

Thank you very much

**Comment by sladrond** [comment]
Thanks Dhruvik! I'll try that.
