### ISSUE TITLE
RSSI or Path loss stats from mmWave examples

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#203]
Hi Tom,

I really appreciate your help on my previous posts.
I have made all the changes to current ns-3 model. And now I am looking to verify my model results.

I have a query on mmWave module. I am able to get SINR Vs Time graphs from the model mmwave-simple-building-obstacle.cc
I am looking for a way to get RSSI or Path loss stats from mmWave examples. 

I would really appreciate any kind of suggestion on the above mentioned subject. 

Thanks,
Rahul Singh Gulia

**Comment by tommasozugno** [comment]
Hi! You can extract the pathloss values using [this trace](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/bb2c452a964785e0be296c85a55d575591d8405f/src/spectrum/model/spectrum-channel.cc#L91)
