### ISSUE TITLE
a error happen when running  mmwave-tcp-example.cc with two UEs

### ISSUE THREAD

**Issue by RaymondHX** [nyuwireless-unipd/ns3-mmwave#205]
I was running mmwave-tcp-example.cc and fix it to two UEs, but a error happen:"assert failed. cond="tempZoa >= 0&&tempZoa <= 180", msg="the ZOA should be the range of [0,180]", file=../src/spectrum/model/three-gpp-channel-model.cc, line=1192". I don't know where this bug come from because I never do something about zoa。

**Comment by tommasozugno** [comment]
This is strange! Can you please provide the simulation script your are using?

**Comment by RaymondHX** [comment]
I find where the problem is! one of the UE and the eNB has the same coordinates.
