### ISSUE TITLE
Issue with pcap generation

### ISSUE THREAD

**Issue by gonzalitojh** [nyuwireless-unipd/ns3-mmwave#206]
Hi, I have created a network with a remote host connected to the PGW, two ENBs (one lte and one mmWave) connected trough X2 interface and a MC UE device. I have configure the UE as an UDP echo client and the remote host as an UDP echo server. The connection between both of them is okey and the packets are generated correctly (I think).

The problem is, when generating pcap files, I have different pcaps of MME node, PGW node, Remote host and both ENBs (some of them are empty), but not pcap file for the UE device. I need that file in order to know the time when packets are sent and received, to analyze certain info.

I have also tried to generate pcap files in some different examples provided from this module or from lte module, and pcap file is never generated for the UE device.

I have added log for client and server, and by that, I have every sent and received packet in both nodes, the problem is that those logged packets are not identified, so I know when packets are sent a received, but not which packets they are.

Thank you very much for your time.

**Comment by tommasozugno** [comment]
We usually make use of the txt trace files which are automatically generated during the simulation (you can enable the generation of these files by calling the method EnableTraces () of the class MmWaveHelper). The format of these files is described [here](https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces). 

> I have added log for client and server, and by that, I have every sent and received packet in both nodes, the problem is that those logged packets are not identified, so I know when packets are sent a received, but not which packets they are.

This really depends on the application you are using. Can't you log the sequence number of the packets?
