### ISSUE TITLE
Is it possible for a direct communication between UEs without eNBs?

### ISSUE THREAD

**Issue by SplayXu** [nyuwireless-unipd/ns3-mmwave#207]
Is there any possible way to achieve a direct communication between UEs without eNBs? Just like sidelink. I know about the millicar module and I tried. The Millicar can use sidelink but it cannot work with routing protocols like OLSR. This module can work with OLSR but it does not have sidelink feature.

I'm not asking how to achieve sidelink, I'm just anking if it is possible to achieve sidelink by modifying the mmWave code without implementing another module.

Thank you so much

**Comment by tommasozugno** [comment]
Unfortunately this is not possible with this module
