### ISSUE TITLE
Support for Hard Handover

### ISSUE THREAD

**Issue by prabodhmishra** [nyuwireless-unipd/ns3-mmwave#208]
We are trying to replicate results that were published in "Performance Comparison of Dual Connectivity and Hard Handover for LTE-5G Tight Integration". But it seems the support for Hard-HO has been removed from current code base as all references to InterRAT handover in the code are commented. 

1. Is there a tag or branch that we can use if we want to test the Hard-HO scenario. 
2. Also, our initial results from fast switching with parameters as mentioned in the above paper are resulting in significantly lower RLC latencies (around 1 ms) as compared to the values that have been reported in the paper (around 5 ms).

Could you please provide some help in these direction. Thank you.

**Comment by tommasozugno** [comment]
1. You can try with this release: https://github.com/nyuwireless-unipd/ns3-mmwave/tree/mmWave-dc-3.27
2. I think this is because of the RLC configuration used in that particular example

**Comment by njjack** [comment]
Hi, is there any reason why the InterRAT handover is not supported any more?
