### ISSUE TITLE
SINR issue for multiple UEs in LOS scenario

### ISSUE THREAD

**Issue by litianxiang** [nyuwireless-unipd/ns3-mmwave#209]
Hi there,

I've been trying to simulate a scenario with one Enb and 10 UEs (in the same container, randomly distributed between 90 to 100m away from the Enb), using the Line-Of-Sight MmWavePropagationLossModel, they are communicating using mmwave 28GHz and channel bandwidth of 100MHz. I have some questions regarding the results I got from the RxPacketTrace.txt. Below is the result I plotted. The x axis is the ten different UEs, the y axis is the SINR, DL throughput, and UL throughput labeled using different units in the legend.
<img width="688" alt="28ghz100mhz10ue" src="https://user-images.githubusercontent.com/11484504/115199873-80283280-a0a8-11eb-8917-9e1ad9374ae7.png">

1) For some UEs, even when the SINR value was negative, it was still able to receive a certain TB size. Is this expected? I had assumed the TB size would be zero due to the high noise ratio, since it is the transport block size (MAC layer payload).

2) What is causing the huge variation in SINR for each UE, if they are all located at a similar distance to the Enb and inside the same container. The LOS MmWavePropagationLossModel calculates loss based on distance.

3) It seems the SINR is having a similar trend as the DL throughput and an opposite trend as the UL throughput. The SINR for UL/DL are the same for each UE, so I was wondering if the SINR is only measured for the DL?

4) Although the simulation was able to finish (generated all the result for the set simulation time), it did display an error at the end: 
Command ['/home/peter/ns3-mmwave/build/scratch/mmwave-example-1'] terminated with signal SIGSEGV. Run it under a debugger to get more information (./waf --run <program> --gdb").
I was wondering if this would have any impact on the result.

I also attached my code at the bottom for reference.

Any help is kindly appreciated, thank you.
Peter

[mmwave-example-10ue.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/6334270/mmwave-example-10ue.txt)

**Comment by tommasozugno** [comment]
> For some UEs, even when the SINR value was negative, it was still able to receive a certain TB size. Is this expected? I had assumed the TB size would be zero due to the high noise ratio, since it is the transport block size (MAC layer payload). 

It depends on the scheduling algorithm and adaptive modulation and coding scheme you are using, The default scheduler assigns resources to the users whose CQI is > 0. Users with CQI = 0 are considered out of range. The CQI is computed by the method CreateCqiFeedbackWbTdma of the class MmWaveAmc.

> What is causing the huge variation in SINR for each UE, if they are all located at a similar distance to the Enb and inside the same container. The LOS MmWavePropagationLossModel calculates loss based on distance.

I think you are using the ThreeGppPropgationLossModel. To use the MmWavePropagationLossModel you should uncomment this line:
 //ptr_mmWave->SetPathlossModelType("ns3::MmWavePropagationLossModel");

> It seems the SINR is having a similar trend as the DL throughput and an opposite trend as the UL throughput. The SINR for UL/DL are the same for each UE, so I was wondering if the SINR is only measured for the DL?

The SINR is measured for both uplink and downlink

> Although the simulation was able to finish (generated all the result for the set simulation time), it did display an error at the end:
Command ['/home/peter/ns3-mmwave/build/scratch/mmwave-example-1'] terminated with signal SIGSEGV. Run it under a debugger to get more information (./waf --run --gdb").
I was wondering if this would have any impact on the result.

This should not happen. You can run it using gdb to understand what is going on (./waf --run mmwave-example-10ue --command-template="gdb %s").
