### ISSUE TITLE
mmwave-example fails with nondefault working directory

### ISSUE THREAD

**Issue by cslezak** [nyuwireless-unipd/ns3-mmwave#21]
Hi,

I noticed that there are some file paths in the mmwave-beamforming.cc file which assume that the script is being executed in the ns3 top level directory. So for example running `./waf --run mmwave-example` will work fine but directing the output files to a directory called output using the command  `./waf --cwd=output --run mmwave-example` fails. The problem is that it cannot locate SmallScaleFading.txt and a few other files.

I was able to fix this by just adding a #define which gives the path to the ns3 root directory, but I was wondering if there is a better solution.

-Chris

**Comment by mychele** [comment]
Hi Chris,
I think the #define is ok, can you open a pull request?
BTW, if you want to redirect output files you can also use the Config system to set the name of the output files, take a look at [how it's done in the mc-example-udp](https://github.com/nyuwireless/ns3-mmwave/blob/new-handover/scratch/mc-example-udp.cc#L730).
Best,
Michele
