### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by aligorithm** [nyuwireless-unipd/ns3-mmwave#210]
Hi. I'm trying to use the module for my research but after running
`./waf configure
./waf`

The build failed with the following errors:

[2529/3021] Compiling build/src/mesh/bindings/ns3module.cc
04:24:20 runner ['/usr/bin/g++', '-Wall', '-std=c++11', '-fPIC', '-g', '-fdebug-prefix-map=/build/python3.8-wRPQXs/python3.8-3.8.5=.', '-fstack-protector', '-g', '-fwrapv', '-O3', '-fvisibility=hidden', '-Wno-array-bounds', '-pthread', '-I.', '-I..', '-Isrc/mesh/bindings', '-I../src/mesh/bindings', '-I/usr/include/python3.8', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_IF_TUN_H=1', '-DNS_DEPRECATED=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_31=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_30=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_27=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_26=', '-DNS3_DEPRECATED_H', '-DNDEBUG', 'src/mesh/bindings/ns3module.cc', '-c', '-o/home/aligorithm/tools/ns3-mmwave/build/src/mesh/bindings/ns3module.cc.7.o']
In file included from src/lte/bindings/ns3module.cc:1:
src/lte/bindings/ns3module.h:9304:10: error: ‘TraceFadingLossModel’ in namespace ‘ns3’ does not name a type
 9304 |     ns3::TraceFadingLossModel *obj;
      |          ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.h:9313:1: error: expected class-name before ‘{’ token
 9313 | {
      | ^
src/lte/bindings/ns3module.h:9316:70: error: expected ‘)’ before ‘const’
 9316 |     PyNs3TraceFadingLossModel__PythonHelper(ns3::TraceFadingLossModel const & arg0)
      |                                            ~                         ^~~~~~
      |                                                                      )
src/lte/bindings/ns3module.h: In constructor ‘PyNs3TraceFadingLossModel__PythonHelper::PyNs3TraceFadingLossModel__PythonHelper()’:
src/lte/bindings/ns3module.h:9321:36: error: expected class-name before ‘(’ token
 9321 |         : ns3::TraceFadingLossModel(), m_pyself(NULL)
      |                                    ^
src/lte/bindings/ns3module.h:9321:36: error: expected ‘{’ before ‘(’ token
src/lte/bindings/ns3module.h: In member function ‘void PyNs3TraceFadingLossModel__PythonHelper::DoDispose__parent_caller()’:
src/lte/bindings/ns3module.h:9340:52: error: cannot call member function ‘virtual void ns3::SpectrumPropagationLossModel::DoDispose()’ without object
 9340 |     { ns3::SpectrumPropagationLossModel::DoDispose(); }
      |                                                    ^
src/lte/bindings/ns3module.h: In member function ‘void PyNs3TraceFadingLossModel__PythonHelper::NotifyNewAggregate__parent_caller()’:
src/lte/bindings/ns3module.h:9344:39: error: cannot call member function ‘virtual void ns3::Object::NotifyNewAggregate()’ without object
 9344 |     { ns3::Object::NotifyNewAggregate(); }
      |                                       ^
src/lte/bindings/ns3module.h: In member function ‘void PyNs3TraceFadingLossModel__PythonHelper::NotifyConstructionCompleted__parent_caller()’:
src/lte/bindings/ns3module.h:9348:52: error: cannot call member function ‘virtual void ns3::ObjectBase::NotifyConstructionCompleted()’ without object
 9348 |     { ns3::ObjectBase::NotifyConstructionCompleted(); }
      |                                                    ^
src/lte/bindings/ns3module.h: In static member function ‘static ns3::TypeId PyNs3TraceFadingLossModel__PythonHelper::GetTypeId()’:
src/lte/bindings/ns3module.h:9365:26: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
 9365 |         .SetParent< ns3::TraceFadingLossModel > ()
      |                          ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.h:9365:26: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
src/lte/bindings/ns3module.h:9365:50: error: no matching function for call to ‘ns3::TypeId::SetParent<<expression error> >()’
 9365 |         .SetParent< ns3::TraceFadingLossModel > ()
      |                                                  ^
In file included from ./ns3/object-base.h:23,
                 from ./ns3/object.h:29,
                 from ./ns3/lte-handover-algorithm.h:25,
                 from ./ns3/a2-a4-rsrq-handover-algorithm.h:31,
                 from ./ns3/lte-module.h:10,
                 from src/lte/bindings/ns3module.h:41,
                 from src/lte/bindings/ns3module.cc:1:
./ns3/type-id.h:631:1: note: candidate: ‘template<class T> ns3::TypeId ns3::TypeId::SetParent()’
  631 | TypeId::SetParent (void)
      | ^~~~~~
./ns3/type-id.h:631:1: note:   template argument deduction/substitution failed:
In file included from src/lte/bindings/ns3module.cc:1:
src/lte/bindings/ns3module.h:9365:50: error: template argument 1 is invalid
 9365 |         .SetParent< ns3::TraceFadingLossModel > ()
      |                                                  ^
src/lte/bindings/ns3module.cc: In static member function ‘static PyObject* PyNs3TraceFadingLossModel__PythonHelper::_wrap_DoDispose(PyNs3TraceFadingLossModel*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:99972:118: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
99972 |     PyNs3TraceFadingLossModel__PythonHelper *helper = dynamic_cast< PyNs3TraceFadingLossModel__PythonHelper* >(self->obj);
      |                                                                                                                      ^~~
src/lte/bindings/ns3module.cc: In static member function ‘static PyObject* PyNs3TraceFadingLossModel__PythonHelper::_wrap_NotifyNewAggregate(PyNs3TraceFadingLossModel*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:99988:118: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
99988 |     PyNs3TraceFadingLossModel__PythonHelper *helper = dynamic_cast< PyNs3TraceFadingLossModel__PythonHelper* >(self->obj);
      |                                                                                                                      ^~~
src/lte/bindings/ns3module.cc: In static member function ‘static PyObject* PyNs3TraceFadingLossModel__PythonHelper::_wrap_NotifyConstructionCompleted(PyNs3TraceFadingLossModel*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:100004:118: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100004 |     PyNs3TraceFadingLossModel__PythonHelper *helper = dynamic_cast< PyNs3TraceFadingLossModel__PythonHelper* >(self->obj);
       |                                                                                                                      ^~~
src/lte/bindings/ns3module.cc: In member function ‘virtual void PyNs3TraceFadingLossModel__PythonHelper::DoInitialize()’:
src/lte/bindings/ns3module.cc:100021:10: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
100021 |     ns3::TraceFadingLossModel *self_obj_before;
       |          ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100021:32: error: ‘self_obj_before’ was not declared in this scope
100021 |     ns3::TraceFadingLossModel *self_obj_before;
       |                                ^~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100027:14: error: ‘ns3::TraceFadingLossModel’ has not been declared
100027 |         ns3::TraceFadingLossModel::DoInitialize();
       |              ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100033:81: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100033 |     self_obj_before = reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj;
       |                                                                                 ^~~
src/lte/bindings/ns3module.cc:100034:63: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100034 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = (ns3::TraceFadingLossModel*) this;
       |                                                               ^~~
src/lte/bindings/ns3module.cc:100034:75: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
100034 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = (ns3::TraceFadingLossModel*) this;
       |                                                                           ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100034:96: error: expected primary-expression before ‘)’ token
100034 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = (ns3::TraceFadingLossModel*) this;
       |                                                                                                ^
src/lte/bindings/ns3module.cc:100038:67: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100038 |         reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                                   ^~~
src/lte/bindings/ns3module.cc:100047:67: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100047 |         reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                                   ^~~
src/lte/bindings/ns3module.cc:100054:63: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100054 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                               ^~~
src/lte/bindings/ns3module.cc: In member function ‘virtual ns3::Ptr<ns3::SpectrumValue> PyNs3TraceFadingLossModel__PythonHelper::DoCalcRxPowerSpectralDensity(ns3::Ptr<const ns3::SpectrumValue>, ns3::Ptr<const ns3::MobilityModel>, ns3::Ptr<const ns3::MobilityModel>) const’:
src/lte/bindings/ns3module.cc:100066:10: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
100066 |     ns3::TraceFadingLossModel *self_obj_before;
       |          ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100066:32: error: ‘self_obj_before’ was not declared in this scope
100066 |     ns3::TraceFadingLossModel *self_obj_before;
       |                                ^~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100091:81: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100091 |     self_obj_before = reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj;
       |                                                                                 ^~~
src/lte/bindings/ns3module.cc:100092:63: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                               ^~~
src/lte/bindings/ns3module.cc:100092:86: error: ‘TraceFadingLossModel’ in namespace ‘ns3’ does not name a type
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                      ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100092:106: error: expected ‘>’ before ‘*’ token
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                          ^
src/lte/bindings/ns3module.cc:100092:106: error: expected ‘(’ before ‘*’ token
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                          ^
       |                                                                                                          (
src/lte/bindings/ns3module.cc:100092:108: error: expected primary-expression before ‘>’ token
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                            ^
src/lte/bindings/ns3module.cc:100092:117: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                                     ^~~
src/lte/bindings/ns3module.cc:100092:111: error: expected primary-expression before ‘const’
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                               ^~~~~
src/lte/bindings/ns3module.cc:100092:111: error: expected ‘)’ before ‘const’
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                              ~^~~~~
       |                                                                                                               )
src/lte/bindings/ns3module.cc:100092:150: error: expected ‘)’ before ‘;’ token
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                             ~                                        ^
       |                                                                                                                                                      )
src/lte/bindings/ns3module.cc:100092:150: error: expected ‘)’ before ‘;’ token
100092 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = const_cast< ns3::TraceFadingLossModel* >((const ns3::TraceFadingLossModel*) this);
       |                                                                                                                                                      ^
       |                                                                                                                                                      )
src/lte/bindings/ns3module.cc:100166:67: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100166 |         reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                                   ^~~
src/lte/bindings/ns3module.cc:100179:67: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100179 |         reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                                   ^~~
src/lte/bindings/ns3module.cc:100191:63: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100191 |     reinterpret_cast< PyNs3TraceFadingLossModel* >(m_pyself)->obj = self_obj_before;
       |                                                               ^~~
src/lte/bindings/ns3module.cc: In member function ‘virtual void PyNs3TraceFadingLossModel__PythonHelper::DoDispose()’:
src/lte/bindings/ns3module.cc:100209:54: error: cannot call member function ‘virtual void ns3::SpectrumPropagationLossModel::DoDispose()’ without object
100209 |         ns3::SpectrumPropagationLossModel::DoDispose();
       |                                                      ^
src/lte/bindings/ns3module.cc: In member function ‘virtual ns3::TypeId PyNs3TraceFadingLossModel__PythonHelper::GetInstanceTypeId() const’:
src/lte/bindings/ns3module.cc:100258:47: error: cannot call member function ‘virtual ns3::TypeId ns3::Object::GetInstanceTypeId() const’ without object
100258 |         return ns3::Object::GetInstanceTypeId();
       |                                               ^
src/lte/bindings/ns3module.cc:100269:47: error: cannot call member function ‘virtual ns3::TypeId ns3::Object::GetInstanceTypeId() const’ without object
100269 |         return ns3::Object::GetInstanceTypeId();
       |                                               ^
src/lte/bindings/ns3module.cc:100279:47: error: cannot call member function ‘virtual ns3::TypeId ns3::Object::GetInstanceTypeId() const’ without object
100279 |         return ns3::Object::GetInstanceTypeId();
       |                                               ^
src/lte/bindings/ns3module.cc: In member function ‘virtual void PyNs3TraceFadingLossModel__PythonHelper::NotifyNewAggregate()’:
src/lte/bindings/ns3module.cc:100301:41: error: cannot call member function ‘virtual void ns3::Object::NotifyNewAggregate()’ without object
100301 |         ns3::Object::NotifyNewAggregate();
       |                                         ^
src/lte/bindings/ns3module.cc: In member function ‘virtual void PyNs3TraceFadingLossModel__PythonHelper::NotifyConstructionCompleted()’:
src/lte/bindings/ns3module.cc:100346:54: error: cannot call member function ‘virtual void ns3::ObjectBase::NotifyConstructionCompleted()’ without object
100346 |         ns3::ObjectBase::NotifyConstructionCompleted();
       |                                                      ^
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3TraceFadingLossModel__tp_init__0(PyNs3TraceFadingLossModel*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:100398:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100398 |         self->obj = new PyNs3TraceFadingLossModel__PythonHelper(*((PyNs3TraceFadingLossModel *) arg0)->obj);
       |               ^~~
src/lte/bindings/ns3module.cc:100398:104: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100398 |         self->obj = new PyNs3TraceFadingLossModel__PythonHelper(*((PyNs3TraceFadingLossModel *) arg0)->obj);
       |                                                                                                        ^~~
src/lte/bindings/ns3module.cc:100399:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100399 |         self->obj->Ref ();
       |               ^~~
src/lte/bindings/ns3module.cc:100401:59: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100401 |         ((PyNs3TraceFadingLossModel__PythonHelper*) self->obj)->set_pyobj((PyObject *)self);
       |                                                           ^~~
src/lte/bindings/ns3module.cc:100402:38: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100402 |         ns3::CompleteConstruct(self->obj);
       |                                      ^~~
src/lte/bindings/ns3module.cc:100405:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100405 |         self->obj = new ns3::TraceFadingLossModel(*((PyNs3TraceFadingLossModel *) arg0)->obj);
       |               ^~~
src/lte/bindings/ns3module.cc:100405:25: error: expected type-specifier
100405 |         self->obj = new ns3::TraceFadingLossModel(*((PyNs3TraceFadingLossModel *) arg0)->obj);
       |                         ^~~
src/lte/bindings/ns3module.cc:100406:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100406 |         self->obj->Ref ();
       |               ^~~
src/lte/bindings/ns3module.cc:100408:38: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100408 |         ns3::CompleteConstruct(self->obj);
       |                                      ^~~
src/lte/bindings/ns3module.cc: In function ‘int _wrap_PyNs3TraceFadingLossModel__tp_init__1(PyNs3TraceFadingLossModel*, PyObject*, PyObject*, PyObject**)’:
src/lte/bindings/ns3module.cc:100429:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100429 |         self->obj = new PyNs3TraceFadingLossModel__PythonHelper();
       |               ^~~
src/lte/bindings/ns3module.cc:100430:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100430 |         self->obj->Ref ();
       |               ^~~
src/lte/bindings/ns3module.cc:100432:59: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100432 |         ((PyNs3TraceFadingLossModel__PythonHelper*) self->obj)->set_pyobj((PyObject *)self);
       |                                                           ^~~
src/lte/bindings/ns3module.cc:100433:38: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100433 |         ns3::CompleteConstruct(self->obj);
       |                                      ^~~
src/lte/bindings/ns3module.cc:100436:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100436 |         self->obj = new ns3::TraceFadingLossModel();
       |               ^~~
src/lte/bindings/ns3module.cc:100436:25: error: expected type-specifier
100436 |         self->obj = new ns3::TraceFadingLossModel();
       |                         ^~~
src/lte/bindings/ns3module.cc:100437:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100437 |         self->obj->Ref ();
       |               ^~~
src/lte/bindings/ns3module.cc:100439:38: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100439 |         ns3::CompleteConstruct(self->obj);
       |                                      ^~~
src/lte/bindings/ns3module.cc: In function ‘PyObject* _wrap_PyNs3TraceFadingLossModel_AssignStreams(PyNs3TraceFadingLossModel*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:100480:20: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100480 |     retval = self->obj->AssignStreams(stream);
       |                    ^~~
src/lte/bindings/ns3module.cc: In function ‘PyObject* _wrap_PyNs3TraceFadingLossModel_DoInitialize(PyNs3TraceFadingLossModel*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:100490:123: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100490 |     PyNs3TraceFadingLossModel__PythonHelper *helper_class = dynamic_cast<PyNs3TraceFadingLossModel__PythonHelper*> (self->obj);
       |                                                                                                                           ^~~
src/lte/bindings/ns3module.cc:100492:36: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100492 |     (helper_class == NULL)? (self->obj->DoInitialize()) : (self->obj->ns3::TraceFadingLossModel::DoInitialize());
       |                                    ^~~
src/lte/bindings/ns3module.cc:100492:66: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100492 |     (helper_class == NULL)? (self->obj->DoInitialize()) : (self->obj->ns3::TraceFadingLossModel::DoInitialize());
       |                                                                  ^~~
src/lte/bindings/ns3module.cc:100492:76: error: ‘ns3::TraceFadingLossModel’ has not been declared
100492 |     (helper_class == NULL)? (self->obj->DoInitialize()) : (self->obj->ns3::TraceFadingLossModel::DoInitialize());
       |                                                                            ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc: In function ‘PyObject* _wrap_PyNs3TraceFadingLossModel_GetTypeId(PyObject*, PyObject*, PyObject*)’:
src/lte/bindings/ns3module.cc:100505:31: error: ‘ns3::TraceFadingLossModel’ has not been declared
100505 |     ns3::TypeId retval = ns3::TraceFadingLossModel::GetTypeId();
       |                               ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc: In function ‘PyObject* _wrap_PyNs3TraceFadingLossModel__copy__(PyNs3TraceFadingLossModel*, PyObject*)’:
src/lte/bindings/ns3module.cc:100523:14: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100523 |     py_copy->obj = new ns3::TraceFadingLossModel(*self->obj);
       |              ^~~
src/lte/bindings/ns3module.cc:100523:24: error: expected type-specifier
100523 |     py_copy->obj = new ns3::TraceFadingLossModel(*self->obj);
       |                        ^~~
src/lte/bindings/ns3module.cc:100526:56: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100526 |     PyNs3ObjectBase_wrapper_registry[(void *) py_copy->obj] = (PyObject *) py_copy;
       |                                                        ^~~
src/lte/bindings/ns3module.cc: In function ‘void PyNs3TraceFadingLossModel__tp_clear(PyNs3TraceFadingLossModel*)’:
src/lte/bindings/ns3module.cc:100545:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100545 |     if (self->obj) {
       |               ^~~
src/lte/bindings/ns3module.cc:100546:10: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
100546 |     ns3::TraceFadingLossModel *tmp = self->obj;
       |          ^~~~~~~~~~~~~~~~~~~~
src/lte/bindings/ns3module.cc:100546:32: error: ‘tmp’ was not declared in this scope; did you mean ‘tm’?
100546 |     ns3::TraceFadingLossModel *tmp = self->obj;
       |                                ^~~
       |                                tm
src/lte/bindings/ns3module.cc:100546:44: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100546 |     ns3::TraceFadingLossModel *tmp = self->obj;
       |                                            ^~~
src/lte/bindings/ns3module.cc:100547:11: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100547 |     self->obj = NULL;
       |           ^~~
src/lte/bindings/ns3module.cc: In function ‘int PyNs3TraceFadingLossModel__tp_traverse(PyNs3TraceFadingLossModel*, visitproc, void*)’:
src/lte/bindings/ns3module.cc:100558:15: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100558 |     if (self->obj && typeid(*self->obj).name() == typeid(PyNs3TraceFadingLossModel__PythonHelper).name()  && self->obj->GetReferenceCount() == 1)
       |               ^~~
src/lte/bindings/ns3module.cc:100558:36: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100558 |     if (self->obj && typeid(*self->obj).name() == typeid(PyNs3TraceFadingLossModel__PythonHelper).name()  && self->obj->GetReferenceCount() == 1)
       |                                    ^~~
src/lte/bindings/ns3module.cc:100558:116: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100558 |     if (self->obj && typeid(*self->obj).name() == typeid(PyNs3TraceFadingLossModel__PythonHelper).name()  && self->obj->GetReferenceCount() == 1)
       |                                                                                                                    ^~~
src/lte/bindings/ns3module.cc: In function ‘void _wrap_PyNs3TraceFadingLossModel__tp_dealloc(PyNs3TraceFadingLossModel*)’:
src/lte/bindings/ns3module.cc:100569:80: error: ‘struct PyNs3TraceFadingLossModel’ has no member named ‘obj’
100569 |     wrapper_lookup_iter = PyNs3ObjectBase_wrapper_registry.find((void *) self->obj);
       |                                                                                ^~~
src/lte/bindings/ns3module.cc: In function ‘PyObject* PyInit_lte()’:
src/lte/bindings/ns3module.cc:215465:108: error: ‘TraceFadingLossModel’ is not a member of ‘ns3’
215465 |     PyNs3SimpleRefCount__Ns3Object_Ns3ObjectBase_Ns3ObjectDeleter__typeid_map.register_wrapper(typeid(ns3::TraceFadingLossModel), &PyNs3TraceFadingLossModel_Type);
       |                                                                                                            ^~~~~~~~~~~~~~~~~~~~

Waf: Leaving directory `/home/aligorithm/tools/ns3-mmwave/build'
  File "./waf", line 168, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 182, in run_commands
    ctx=run_command(cmd_name)
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Scripting.py", line 375, in execute
    return execute_method(self)
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Build.py", line 93, in execute
    self.execute_build()
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Build.py", line 100, in execute_build
    self.compile()
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Tools/errcheck.py", line 140, in check_compile
    ret=self.orig_compile()
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
  File "/home/aligorithm/tools/ns3-mmwave/.waf3-2.0.18-ff4ae9f5cc05353d3dc3aeff8854ae69/waflib/Errors.py", line 26, in __init__
    WafError.__init__(self,self.format_error())
 
Build failed
 -> task in 'ns3module_lte' failed with exit status 1: 
	{task 140644977482544: cxx ns3module.cc -> ns3module.cc.7.o}
['/usr/bin/g++', '-Wall', '-std=c++11', '-fPIC', '-g', '-fdebug-prefix-map=/build/python3.8-wRPQXs/python3.8-3.8.5=.', '-fstack-protector', '-g', '-fwrapv', '-O3', '-fvisibility=hidden', '-Wno-array-bounds', '-pthread', '-I.', '-I..', '-Isrc/lte/bindings', '-I../src/lte/bindings', '-I/usr/include/python3.8', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_IF_TUN_H=1', '-DNS_DEPRECATED=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_31=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_30=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_27=', '-DNS3_DEPRECATED_H', '-DNS_DEPRECATED_3_26=', '-DNS3_DEPRECATED_H', '-DNDEBUG', 'src/lte/bindings/ns3module.cc', '-c', '-o/home/aligorithm/tools/ns3-mmwave/build/src/lte/bindings/ns3module.cc.7.o']

**Comment by aligorithm** [comment]
This worked after disabling python. However, does that mean python isn't supported by the module?

**Comment by litianxiang** [comment]
I had the same issue, based on the old post #200, it seems it isn't supported.

**Comment by aligorithm** [comment]
Yeah. I guess it can be avoided by including in the readme that python isn't supported. Or maybe we missed it somewhere?

**Comment by tommasozugno** [comment]
Hi, you just need to re-generate the python bindings as described [here](https://www.nsnam.org/docs/manual/html/python.html#using-python-to-run-ns3)
