### ISSUE TITLE
mmwave-tcp-building example Plots 

### ISSUE THREAD

**Issue by RahulSinghGulia** [nyuwireless-unipd/ns3-mmwave#211]
I am trying to simulate the plots given in "A Framework for End-to-End Evaluation of 5G mmWave Cellular Networks in ns-3".

I have made my changes to the backend source code to the path loss models to see their performance. But I can't get as many plots as given in this paper.
I can get SINR vs Time plots from the RxPacketTrace.txt file. But I want to generate the Figure-7 plots in this paper.

![image](https://user-images.githubusercontent.com/68552299/116330497-aed69500-a79b-11eb-962e-e5e78c15f74b.png)

Could you please guide me in any small way possible to generate these graphs. I have looked at lot of places, but could not get much out of it. I would really appreciate any kind of help.

Thank you
-Rahul

**Comment by tommasozugno** [comment]
Hi, for the RTT and CWND plots you can use the TCP traces, have a look at [this example](https://www.nsnam.org/docs/tutorial/html/tracing.html#real-example). Regarding the throughput, you should compute it starting from the application or PDCP traces. To do so, you can write your own script or use [this one](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/scripts/read_traces.pl)
