### ISSUE TITLE
SINR issue for MC-UE LOS scenario

### ISSUE THREAD

**Issue by tommy-ncnu** [nyuwireless-unipd/ns3-mmwave#212]
Hi there,
I've been trying to simulate a scenario with sample/mc-twoenbs.cc, furthermore rearrange gnbs and ue like fig1.  Then plot MmWaveSinrTime.txt using matlab and get fig2.  
Why is there a outage at green and blue gnb every 0.1s? Is it normal to mmWave behavior?
![fig1](https://user-images.githubusercontent.com/51190471/117562554-5d4ed400-b0d2-11eb-9c2b-fc650b30d758.jpg)
![fig2](https://user-images.githubusercontent.com/51190471/117562581-8ff8cc80-b0d2-11eb-914d-dd3371055245.jpg)

Thanks!

**Comment by tommasozugno** [comment]
Hi, this is because in this example a new channel realization is generated every 100 ms. You can configure the update period through the attribute "ns3::ThreeGppChannelModel::UpdatePeriod".

**Comment by tommy-ncnu** [comment]
OK, thanks you
