### ISSUE TITLE
How to achieve visualization

### ISSUE THREAD

**Issue by QingweiJi** [nyuwireless-unipd/ns3-mmwave#214]
After studying some online tutorials, I put ns3-mmwave on the desktop of Ubuntu16.04LTS and decompressed it. It can be successfully compiled through ./waf, but it cannot be visualized. It shows that the ns module is missing, but I put ns3-mmwave on it. Go to the installation folder of ns3, the visualization still cannot be used after compiling successfully, how can I solve it?

**Comment by aligorithm** [comment]
I'm not an expert on this module, but I use NetAnim for visualisation and it works well. The visualization is done offline (i.e. after the simulation has completed running). You just have to configure NetAnime to create the output file.
Here: https://www.nsnam.org/wiki/NetAnim

**Comment by 19981217lilyji** [comment]
Thank you very much for the solution, I will try it as soon as possible

**Comment by QingweiJi** [comment]
> I'm not an expert on this module, but I use NetAnim for visualisation and it works well. The visualization is done offline (i.e. after the simulation has completed running). You just have to configure NetAnime to create the output file.
> Here: https://www.nsnam.org/wiki/NetAnim

Thank you very much for the solution, I will try it as soon as possible

**Comment by tommasozugno** [comment]
Please follow the installation guidelines reporte [here](https://github.com/nyuwireless-unipd/ns3-mmwave#installation). 
Each simulation produces some output files containing different metrics, they are described [here](https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces). You should write your own script (e.g., using python) to extract or compute the metrics of interest and then plot the results.

Best, 
Tommaso
