### ISSUE TITLE
 GBR_CONV_VOICE with ActivateDedicatedEpsBearer and EPC

### ISSUE THREAD

**Issue by Gabriela3000** [nyuwireless-unipd/ns3-mmwave#218]
Hello
I know if we don't have EPC we need to use ActivateDataRadioBearer. But how about when we have EPC?
When we are using EPC and we want to have GBR_CONV_VOICE we need to use ActivateDedicatedEpsBearer, but it shows error as there is no such member. Could you please let me know how should I do that?
Best wishes

**Comment by tommasozugno** [comment]
When you use the EPC a default bearer is automatically created.

Best, 
Tommaso
