### ISSUE TITLE
Can we implement different Network Operators in our Simulation?

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#219]
I want to generate mmwave traces for different network operators (or Network Service Providers). If I want to develop this on my own from where should I start? 

The main objective is to install a simple application on the UE and see its performance under different network operators. As in 4G, we don't need a simulation platform, but for 5G we need a simulation of this.

**Comment by mattia-lecci** [comment]
Hi Argha, what you ask really depends on what you want to achieve.
You would surely need to create multiple eNBs attached to multiple core networks.
Then, depending on what you want to simulate, keep in mind that different operators might have different hadware and/or software running on their eNBs (e.g., they should use different frequency bands, different frequency reuse strategies, different scheduling algorithms, different antennas, etc.).

Furthermore, having multiple core networks in a simulation is not supported out of the box, and would need some code.
You can find [here](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/utils/mmWave-newhandoverBranch-dce18-patch.diff) an example of patch achieving this, although it was targetting a much older version of the simulator.

Hope this can help,
Cheers
