### ISSUE TITLE
mmwave-tcp-tandon

### ISSUE THREAD

**Issue by DavedAgustian** [nyuwireless-unipd/ns3-mmwave#22]
I had ran the mmwave-tcp-tandon.cc scripts and i got the buildings.txt, ENB-UE.txt, UE-TCP CWND and UE-TCP-DATA as the results. Could you explain the features in those files?

**Comment by MengleiZhang** [comment]
That is a testing example. You do not need to worry about that.

Menglei

**Comment by DavedAgustian** [comment]
My Teacher ask to analyst that results. could you explain to me?

**Comment by MengleiZhang** [comment]
The Buildings.txt contains the coordinates of each building object. ENB_UE.txt contains the coordinates of ENB and UE of each data transmission, so I can track the movement of UE. UE-TCP-CWND.txt contains the congestion window dynamics, the last one contains the time of receiving each packet and packet size.

**Comment by DavedAgustian** [comment]
i got an error like this: assert failed. cond="m_roomX <= building->GetNRoomsX ()", file=../src/buildings/model/mobility-building-info.cc, line=93
terminate called without an active exception
Command ['/home/ns-allinone-3.26/ns-3.26/build/scratch/mmwave-tcp-indoor'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").
while i run the mmwave-tcp-indoor. what should i do?

**Comment by MengleiZhang** [comment]
You cannot place a user in a building object without setting the NumOfRoomx, NumOfFloors.

Menglei

**Comment by DavedAgustian** [comment]
please correct if i am wrong, so the mmwave-tcp-indoor is LOS channel model and mmwave-tcp-tandon is NLOS channel model. so user can compute the SNIR from both channel.

**Comment by mychele** [comment]
Hi,
This is not correct. You can use any channel condition, it depends on the
reciprocal position of the base station and the user, and on the obstacles
which are in the middle. In particular, the indoor example uses the model
for indoor scenarios.
Michele

Il 19 giu 2017 05:26, "DavedAgustian" <notifications@github.com> ha scritto:

**Comment by DavedAgustian** [comment]
Dear Mr. Menglei, I was worked to get to know the movements of eNB's and UE's by used NetAnim but both did not appears. I was added this scripts:
#include "ns3/netanim-module.h"
.
.
.
nimationInterface anim ("mmwave-tandon1.xml");
anim.SetConstantPosition (ueNodes.Get(1), 6, 10);
anim.SetConstantPosition (ueNodes.Get(2), 10, 20);
anim.SetConstantPosition (ueNodes.Get(3), 15, 40);

and i got this : 
AnimationInterface WARNING:Node:0 Does not have a mobility model. Use SetConstantPosition if it is stationary
AnimationInterface WARNING:Node:1 Does not have a mobility model. Use SetConstantPosition if it is stationary
AnimationInterface WARNING:Node:2 Does not have a mobility model. Use SetConstantPosition if it is stationary
assert failed. cond="n", file=../src/netanim/model/animation-interface.cc, line=289
terminate called without an active exception
Command ['/home/ns-allinone-3.26/ns-3.26/build/scratch/mmwave-tcp-tandon'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").


any advices, please ?

**Comment by MengleiZhang** [comment]
I never used NetAnim, so I probably could not help.

**Comment by hshrad** [comment]
I got a error You cannot place a user in a building object without setting the NumOfRoomx, NumOfFloors.

**Comment by MengleiZhang** [comment]
Then you just set these parameters.

Menglei

**Comment by hshrad** [comment]
Would you please let me know how to set the NumOfRoomx and NumOfFloors?

My other issue is that I want to design a GUI for a 5G scenario in which there are 4 buildings and I need to generate the SINR map for all of the spots of my map. I saw in ur answers that you are not using NetAnim for graphical user interfaces. What do you suggest in this regard? Is there any relevant example that you have considered so that I can use?

**Comment by MengleiZhang** [comment]
Just set all parameters to 1 should be fine. I have not done anything like this, so I probably cannot help you with it.

Menglei

**Comment by hshrad** [comment]
As far as I see these parameters are all set in the building.cc file. Would you please clarify which file you mean?

**Comment by MengleiZhang** [comment]
Her is an example of set these parameters in the example script.

Ptr < Building > building;
  building = Create<Building> ();
  building->SetBoundaries (Box (20.0, 40.0,
                                0.0, 20.0,
                                0.0, 20.0));
  building->SetBuildingType (Building::Residential);
  building->SetExtWallsType (Building::ConcreteWithWindows);
  building->SetNFloors (1);
  building->SetNRoomsX (1);
  building->SetNRoomsY (1);
