### ISSUE TITLE
RSVP

### ISSUE THREAD

**Issue by lilinstu** [nyuwireless-unipd/ns3-mmwave#220]
Recently, I have been studying various commonly used protocol emulation. May I ask if NS3 can realize RSVP protocol emulation? I have not seen anyone realize RSVP on the Internet, so I have a skeptical attitude about the feasibility.

**Comment by tommasozugno** [comment]
You should submit this question to the ns-3 organization by opening an issue in [this repo](https://gitlab.com/nsnam/ns-3-dev).
