### ISSUE TITLE
How to use " three-gpp-v2v-channel-condition-model" in mmwave building obstacle ?

### ISSUE THREAD

**Issue by mingharti** [nyuwireless-unipd/ns3-mmwave#225]
I am doing research in 5G v2x communication. I was trying to implement the "three-gpp-v2v-channel-condition-model"  for urban scenario using the variable number vehicle with different gNB transmit power and carrier frequency but I was not able to implement. Anybody help me to this problem.

**Comment by tommasozugno** [comment]
You can have a look at [this example](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/new-handover/examples/channel-models/three-gpp-v2v-channel-example.cc). However, the v2v channel model is meant for vehicle-to-vehicle communications, while to model the wireless channel between a vehicle and a base station you should use a v2i model (see table 1 in [this paper](https://dl.acm.org/doi/pdf/10.1145/3460797.3460801), which shows the channel model you should use for different link types).
