### ISSUE TITLE
How to track number of UE connected to a particular base station?

### ISSUE THREAD

**Issue by arghasen10** [nyuwireless-unipd/ns3-mmwave#227]
Hi, I want to **track the number of user equipment** connected to a Base Station. 

Right now we can do that from the **simulated trace files** which is a type of Post Processing. For tracking this parameter can we add a `TraceSource`  in any model class files (like  `mmwave-enb-phy.cc` or `mmwave-net-device.cc` these files) ???

**Comment by tommasozugno** [comment]
Have a look at the class LteEnbRrc, I think you can use the trace which is fired [at this line](https://github.com/nyuwireless-unipd/ns3-mmwave/blob/4ff9e87e8079764e04cbeccd8e85bff15ae16fb3/src/lte/model/lte-enb-rrc.cc#L1567)
