### ISSUE TITLE
evaluate tcp protocols in Manet

### ISSUE THREAD

**Issue by Oma-Alram** [nyuwireless-unipd/ns3-mmwave#228]
Hi,
Any one can help me to add number of nodes and node mobility to tcp-variants-comparison.cc file in ns3 to evaluate tcp protocols in Manet network instead of two node in wired network. The directory of this file is ns3.33/example/tcp/tcp-variants.comparison
Thanks a lot

**Comment by tommasozugno** [comment]
Have a look at the [ns-3 documentation](https://www.nsnam.org/documentation/) or use the [ns-3 user group](https://groups.google.com/g/ns-3-users?pli=1).

**Comment by Oma-Alram** [comment]
Thank you Tommasozugno. I have already post many times in ns3 user group and I have checked in ns3-documentation. No answer up to now.

**Comment by Oma-Alram** [comment]
Hello,
Thank to reply. Unfortunately, I post many times in ns3-user group but there is no help.
Regards
    On Saturday, 16 October 2021, 15:11:01 GMT+8, Tommaso Zugno ***@***.***> wrote:  
 
 


Closed #228.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
