### ISSUE TITLE
Launch simulation without waf

### ISSUE THREAD

**Issue by michael21hej** [nyuwireless-unipd/ns3-mmwave#229]
Dear ns3-mmwave team,

I am trying to launch ns3-mmwave examples using other methods because the waf tool has library dependency.

I am wondering if anyone here has the experience  to launch simulation without waf.

If yes, could you share your methods? Thank you very much.

**Comment by tommasozugno** [comment]
If you already compiled the code, you could try to run the executables directly without using waf. The executable files are in the build/ directory.
