### ISSUE TITLE
tracking enb-eu movements at indoor building

### ISSUE THREAD

**Issue by DharmaYaddi** [nyuwireless-unipd/ns3-mmwave#24]
Hello master, I am working on mmwave-tcp-indoor and trying to add the example situation on it that i can track the ENB-EU movements the same as in mmwave-tandon. but i could'nt found the source of ENB-EU.txt from mmwave-tcp-tandon. any advices ?

**Comment by MengleiZhang** [comment]
Only the 3GPP building propagation loss model logs the mobility tracking
info.

**Comment by DharmaYaddi** [comment]
So that's mean, I cant track the ENB-UE's movements in indoor despite i put the mmwave-3gpp-buildings-propagation-loss-model script on it ?

**Comment by MengleiZhang** [comment]
You should not use the building propagation loss model for indoor scenarios.

**Comment by MengleiZhang** [comment]
You can go to the building propagation loss model and copy the tracing code
to other propagation loss models.

**Comment by DharmaYaddi** [comment]
Thankyou so much Mr. Zhang. I will trying.

**Comment by DharmaYaddi** [comment]
I have been looking for this repository TcpL4Protocol/SocketList/0/CongestionWindow. any clue please ?

**Comment by MengleiZhang** [comment]
I do no think I understand your question. This command is copied from the
official TCP example scripts. You may ask the authors instead.

**Comment by DharmaYaddi** [comment]
I am looking for Congestion Window scripts. I think that is the repositories from the file. any advices?

**Comment by MengleiZhang** [comment]
I guess you are can find them in the Internet folder.
