### ISSUE TITLE
some questions for code in the simulation

### ISSUE THREAD

**Issue by MOUmeiqi** [nyuwireless-unipd/ns3-mmwave#249]
Hi Guys!
my first question: i get the data by runing the code,but i don't konw how to visual the data,such as:plot the SINR figure, i.e. don't konw use the order to open the '.txt' file.
the scond question is how to use the files in the scripts. e,g, such as:plot_latency.py、plot_rate_phy.py. I try to run such as .py file,but  no response.
I would appreciate it if someone could help me with my questions
Yours
JIANG Yizhou

**Comment by pagmatt** [comment]
Hi Jiang,

Personally I generate plots by using a Python script, by loading the trace file I am interested in using Pandas `readcsv` function and then carrying out whatever analysis I am interested in. 
To understand what the various columns of the tracefile mean, you can inspect the code and find where such a trace is logged. For instance, the PHY traces are logged in the MmwavePhyTrace class, and its rows log the transmission/reception of a single PHY lateer PDU. Its most notable columns encode:

- `frame`: the NR frame index
- `subF`: the NR subframe index
- `slot`: the NR slot index
- `rnti`: the RNTI of the user involved in the transmission/reception of the specific PHY PDU
- `1stSym`: the index of the OFDM symbol where the transmission/reception of the specific PHY PDU begins
- `symbol#`: the number of OFDM symbols that the transmission/reception of the specific PHY PDU has been allocated
- `DL/UL`: whether this PHY PDU is a DL or an UL communication
- `ccId`: the ID of the CC used for this PHY PDU
- `SINR(dB)`: the SINR experienced by this PDU, expressed in dB
- `corrupt`: whether this packet was received corrupted 
- `TBler`: the error probability associated to this PHY PDU

**Comment by tommasozugno** [comment]
You can also refer to this wiki page: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces
