### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by angihe93** [nyuwireless-unipd/ns3-mmwave#252]
Hi, I could not build ns3-mmwave by running ./ns3 configure --disable-
python --enable-examples && ./ns3 build. It had several gmake errors. [Here](https://drive.google.com/file/d/1ac_JpYO-Cf14_-dz41bf114MrbMmSl0U/view?usp=sharing) is my saved terminal output for reference. I'm running macOS Monterey 12.5.1. Please let me know if there's anything I should try, or if I should provide any additional info. Thanks

**Comment by Gabrielcarvfer** [comment]
Would you mind trying ``./ns3 configure --disable-werror``? I haven't seen these warnings with the compilers we are testing in the upstream ns-3 project.

**Comment by pagmatt** [comment]
Also, could you please try building the `mmwave` module without adding `millicar` first ? So that we can better identify where the issue stems from and thus discuss it in the proper repository

**Comment by angihe93** [comment]
Thank you. adding --disable-werror flag didn't work, but I was able to build it by removing the line "add_compile_options(-Werror)" in Cmakelists.txt in src/mmwave and src/lte.

**Comment by pagmatt** [comment]
Sorry for that, we fixed it in our private development repo but we haven't pushed the fix to this public repository yet. We will do it soon!
