### ISSUE TITLE
Can you suggest module or example for creating underground zone/ blocking area?

### ISSUE THREAD

**Issue by kaitofah** [nyuwireless-unipd/ns3-mmwave#254]

**Comment by kaitofah** [comment]
I would like to create scenario e.g. underground like parking or tunnel. 
Could you give me the examples or module that I may follow to create that scenario.

Thank you

**Comment by pagmatt** [comment]
Hi,

Usually, we setup simulations using the 3GPP TR 38.901 channel model. As a consequence, the user is usually restricted to whichever scenarios have been defined by 3GPP and, as far as I know, no scenario which closely mimics your goal has been defined as of yet.
Therefore, your options are to either:
- skim through the 38.901 document and look for a scenario which may resemble an underground area
- use the QD ray tracer to define a custom scenario [more challenging and time consuming]

Best, 
Matteo

**Comment by kaitofah** [comment]
> Hi,
> 
> Usually, we setup simulations using the 3GPP TR 38.901 channel model. As a consequence, the user is usually restricted to whichever scenarios have been defined by 3GPP and, as far as I know, no scenario which closely mimics your goal has been defined as of yet. Therefore, your options are to either:
> 
>     * skim through the 38.901 document and look for a scenario which may resemble an underground area
> 
>     * use the QD ray tracer to define a custom scenario [more challenging and time consuming]
> 
> 
> Best, Matteo

Thank you Matteo 
Cheers,
