### ISSUE TITLE
Buffer Problem

### ISSUE THREAD

**Issue by Oma-Alram** [nyuwireless-unipd/ns3-mmwave#255]
Hi
After I run a scenario on ns3-mmWave successively and during the run I got this error:

assert failed. cond="AreEquals (t1->m_lost, t2->m_lost)", msg="Merging one lost and another not lost. Impossible", file=../src/internet/model/tcp-tx-buffer.cc, line=597
terminate called without an active exception

Could someone help to overcome this issue

Thanks

**Comment by pagmatt** [comment]
Hi Oma,

Which script are you running? 
Are you using non-default parameters?
Have you modified the module source in any way?

Best,
Matteo

**Comment by pagmatt** [comment]
Closed due to missing context and thus inability to reproduce
