### ISSUE TITLE
Question about Error Models: no member named SetDlErrorModel

### ISSUE THREAD

**Issue by vibhorguptaa** [nyuwireless-unipd/ns3-mmwave#258]
Hi, I was trying to run some simulations for a TCP study, and wanted to use the Error Models for the DL. 

I tried using the MmWaveHelper::SetUlErrorModel() or MmWaveHelper::SetDlErrorModel(), as suggested in mmwave-error-model.h, but ran into following compilation error:

class ns3::mmwave:MmWaveHelper has no member named SetDlErrorModel.

I tried finding these methods but was not able to locate the code for them in mmwave-helper.h/cc.

I am not sure whether these methods are obsolete and not usable anymore. Is there an alternative to these methods?

**Comment by pagmatt** [comment]
Yes, those are indeed obsolete.
You can change the error model by tuning _both_  following attributes:
`MmWaveAmc::ErrorModelType ` and` MmWaveSpectrumPhy::ErrorModelType`. 
However, in the latest version of the module you do not have the possibility of picking a different error model for DL and UL communications
