### ISSUE TITLE
mc-twoenbs.cc does not generate Mobility trace files

### ISSUE THREAD

**Issue by mchristopoulou** [nyuwireless-unipd/ns3-mmwave#271]
Hi all,

I am using the latest version of ns3-mmwave (new-handover).
The script "mc-twoenbs.cc" does not generate the mobility-related trace files:

- CellIdStatsHandover.txt
- EnbHandoverStartStats.txt
- EnbHandoverEndStats.txt
- UeHandoverStartStats.txt
- UeHandoverEndStats.txt

The other trace files (Data Traces and SINR) are produced correctly.
In addition, I do not see any output coming from the Callback function "NotifyHandoverStartEnb", although the script includes it. I attach the output.

Is there any particular configuration I should do to get the mobility traces, as well?

Thank you
[mc-twoenbs-output.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/12136818/mc-twoenbs-output.txt)

**Comment by mchristopoulou** [comment]
It seems I had to set a value on velocity in line 657:
ueNodes.Get(0)->GetObject<ConstantVelocityMobilityModel>()->SetVelocity(Vector(ueSpeed, 0, 0));
Now, I get properly all mobility traces.

**Comment by NeutrinoLiu** [comment]
this is some sorts of weird, speed in line 657 sets the initial speed of ue which is 0. then the speed get changed to ueSpeed after "transientDuration" then changed back to 0 after "simTime - 1". This simulates a static-move-static trace which should be fine and no need to modify line 657. However, we do need to change line 657 to have it generate handover traces which is weird.

**Comment by mchristopoulou** [comment]
I am using a different mobility model, where the mobility traces are generated properly.
The behavior is indeed weird. In case you come up with an explanation, I would be interested to see it.

Thank you for the feedback.

**Comment by NeutrinoLiu** [comment]
> I am using a different mobility model, where the mobility traces are generated properly. The behavior is indeed weird. In case you come up with an explanation, I would be interested to see it.
> 
> Thank you for the feedback.

which mobility model you use? i think there is only one constant velocity implementation.

**Comment by mchristopoulou** [comment]
> which mobility model you use? i think there is only one constant velocity implementation.


Hi! Sorry for the delayed reply. I hadn't seen the comment :)
I am using a trace file generated by SUMO [https://sumo.dlr.de/docs/Tutorials/Trace_File_Generation.html](https://sumo.dlr.de/docs/Tutorials/Trace_File_Generation.html), instead of the ns-3 implementation.

In this case, the UEs move like vehicles in an urban grid.

Now, I get proper mobility trace files as handovers take place during the vehicle's movement across the urban grid.

**Comment by Eric-648** [comment]
> It seems I had to set a value on velocity in line 657: ueNodes.Get(0)->GetObject()->SetVelocity(Vector(ueSpeed, 0, 0)); Now, I get properly all mobility traces.


Hi, I tried modifying the code you mentioned at line 657, but I did not see the related files:
CellIdStatsHandover.txt
EnbHandoverStartStats.txt
EnbHandoverEndStats.txt
UeHandoverStartStats.txt
UeHandoverEndStats.txt
The results from executing the original mc-twoenbs are the same as yours.
Please tell me how to generate these files.
