### ISSUE TITLE
Ray-Tracing or Measurement Trace Model

### ISSUE THREAD

**Issue by ArndtTU** [nyuwireless-unipd/ns3-mmwave#272]
Hi,

thank you for the simulator. I am interested in the implementation of a channel model that utilizes traces from a ray-tracing software such as QuaDRiGa. According to your paper ( https://ieeexplore.ieee.org/document/8344116 ) as well as the readme it is possible to use measured traces. I tried both the mmWave version 4.0 and 7.0. All code referring to ns3::MmWaveChannelRaytracing has been commented out, and the path mmwave/model/Raytracing/ has been removed. A grep search does not find the class MmWaveChannelRaytracing.
Could you provide an explanation on how to implement such traces by chance?

Thank you very much.

**Comment by ArndtTU** [comment]
The feature seems to have been removed with version 3.0.
Do you think there is an easy way to port the old MmWaveChannelRaytracing class from version 2.0 to version 4.0?
Thank you very much.

**Comment by pagmatt** [comment]
Hi,

Currently, we support the import of channel traces generated using the [ray tracer developed by our group](https://github.com/signetlabdei/qd-realization) (in collaboration with NIST) via the [QD-channel module](https://github.com/signetlabdei/qd-channel). The latter is compatible with the latest mmwave release.
You could either use our ray tracer, whose traces can then be directly plugged in the simulator, or take a look at the above integration module, and the old mmwave codebase, as starting points for introducing the support for traces generated in different ray tracers.

Best,
Matteo
