### ISSUE TITLE
Scheduler (mmwave-flex-tti-mac-scheduler) sigabrt6 error

### ISSUE THREAD

**Issue by fgjeci** [nyuwireless-unipd/ns3-mmwave#275]
I ran into this error when using the scheduler type ns3::MmWaveFlexTtiMacScheduler. The full error stack:

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 20) >= this->size() (which is 20)

Program received signal SIGABRT, Aborted.
0x00007ffff4389438 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  0x00007ffff4389438 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff438b03a in __GI_abort () at abort.c:89
#2  0x00007ffff4cd8dde in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff4ce47a6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff4ce4811 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff4ce4a65 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff4cdb4b1 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff79bc9ba in ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedTriggerReq(ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters const&)
    ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-mmwave-optimized.so
#8  0x00007ffff79752f1 in ns3::mmwave::MmWaveEnbMac::DoSlotIndication(ns3::mmwave::SfnSf) ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-mmwave-optimized.so
#9  0x00007ffff792ac41 in ns3::mmwave::MmWaveEnbPhy::StartTti() ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-mmwave-optimized.so
#10 0x00007ffff793198e in ns3::mmwave::MmWaveEnbPhy::StartSlot() ()
   fromns3-mmwave-new-oran/build/lib/libns3.38.rc1-mmwave-optimized.so
#11 0x00007ffff793231d in ns3::mmwave::MmWaveEnbPhy::EndSlot() ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-mmwave-optimized.so
#12 0x00007ffff50b3009 in ns3::DefaultSimulatorImpl::ProcessOneEvent() ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-core-optimized.so
#13 0x00007ffff50b30d1 in ns3::DefaultSimulatorImpl::Run() ()
   from ns3-mmwave-new-oran/build/lib/libns3.38.rc1-core-optimized.so
#14 0x000000000041ee3d in main ()

**Comment by pagmatt** [comment]
Hi,

Does this happen with the vanilla mmwave module, or are you using a custom version?
Which simulation script are you running, and is it one of the provided examples ?

Best,
Matteo

**Comment by pagmatt** [comment]
Closed due to inactivity
