### ISSUE TITLE
Error in running mmwave-tcp-tandon

### ISSUE THREAD

**Issue by hshrad** [nyuwireless-unipd/ns3-mmwave#28]
I am trying to run the mmwave-tcp-tandon file and each time I run it it shows the following 5 lines : 

UMa scenario, channel condition is fixed to be l, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be l, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be l, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5

and then it comes with the following error: 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Command ['/home/osboxes/Desktop/ns-allinone-3.26/ns3-mmwave-master/build/scratch/mmwave-tcp-tandon'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

would you please let me know how to run this file and also mmwave-tcp-indoor so that it won't cause any errors? Do I need to insert any inputs? Or we just have to run the .cc file using the following command:

./waf --run scratch/mmwave-tcp-tandon

Looking forward to hearing from you.

**Comment by MengleiZhang** [comment]
I did not get any error running this example. Did you make any changes? If so please give us more information, and run it under a debugger.

Menglei

**Comment by hshrad** [comment]
Actually I didn't change anything and just ran the file you have posted on GitHub. Would you please let me know which of the examples that you have provided gives the SINR as the output? That's my goal for using your codes.

**Comment by MengleiZhang** [comment]
Most of them should generate a txt file RxPaccketTrace.txt, where you can find the SINR trace. If you do not see it try to call MmWaveHelper->EnableTraces() Function.

Menglei

**Comment by hshrad** [comment]
When I run the mmwave-tcp-tandon.cc example a few .txt files are generated. 
UE-1-TCP-CWND/DATA/RCWND/RTT/CWND.txt
UE-2-TCP-CWND/DATA/RCWND/RTT/CWND.txt

**Comment by hshrad** [comment]
I need to  generate the SINR for a node with different distances form the BS (as demonstrated in fig.7 of your paper) . When I run the mmwave-tcp-tandon.cc example the following .txt files are generated. It's not clear to me what these values are. Would you please guide me how to get the SINR for a node with a specific distance from the BS as the output? Then I can change the distance and generate SINR for different distances. 

the generated files through running the mmwave-tcp-tandon.cc example: 
UE-1-TCP-CWND/DATA/RCWND/RTT/CWND.txt
UE-2-TCP-CWND/DATA/RCWND/RTT/CWND.txt

**Comment by MengleiZhang** [comment]
Try the following example, and a text file called RxPacektTrace.txt will be generated. There is a column contains the SINR.

> ./waf --run src/mmwave/examples/mmwave-3gpp-channel-test
