### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by danielScLima** [nyuwireless-unipd/ns3-mmwave#280]
I am using the commands indicated to build the project, but it is not building.
It shows some errors, as shown in the image. 
There is something that I am missing?

used commands:
git clone https://github.com/nyuwireless-unipd/ns3-mmwave.git
cd ns3-mmwave
./ns3 configure --disable-python --enable-examples && ./ns3 build

Operating system that I am using: Mint

I also changed the tag, but all of them have similar errors

![image](https://github.com/user-attachments/assets/5bc4b178-b841-4e5b-99cb-f742107621a2)

**Comment by EmoEmoEmoEmo** [comment]
I also meet this problem, could anyone help me

**Comment by EmoEmoEmoEmo** [comment]
Hi, bro, I solve this problem by following the guidence of this post https://groups.google.com/g/ns-3-users/c/v9Js8MyIXRw/m/1syLjkaQAQAJ . @danielScLima

**Comment by pagmatt** [comment]
Thanks for notifying the issue, fixed with commit https://github.com/nyuwireless-unipd/ns3-mmwave/commit/c01be9445db95e59c261fe28891224d4778187e0

**Comment by danielScLima** [comment]
Thanks @EmoEmoEmoEmo and @pagmatt . With the changes done in the mentioned commit the build is working.
