### ISSUE TITLE
Column Headers in RLC and PDCP stats

### ISSUE THREAD

**Issue by vikigenius** [nyuwireless-unipd/ns3-mmwave#29]
I am running the mmwave-tcp-example and i can't figure out what the columns mean in the stats files, like DlRlcStats.txt. Can you explain them, or have a header row while creating the files?

**Comment by mychele** [comment]
Hi,
you can check how these files are generated in the helper classes. 
For example, for the RLC and PDCP stats you have 
RX or TX | Simulation time | Cell ID | RNTI | LCID | packet size | delay (only for RX)
If you prefer the format of the LTE RLC and PDCP traces, you can add an LteHelper in the simulation script and enable the RLC and PDCP traces.
Best,
Michele
