### ISSUE TITLE
channel matrix query

### ISSUE THREAD

**Issue by jq5** [nyuwireless-unipd/ns3-mmwave#30]
Hi All,

1.	When I try and create a channelmatrix model, mmwave crashes with the error "omi transmission do not need beamforming vector", file=../src/mmwave/model/antenna-array-model.cc, line=190

Should I not try and create a channel matrix?  Or is there a means of turning off beam forming for this omni transmission channel?

2.	In a few locations, I see “//for testing” as in “AntennaArrayModel”.  Should I be commenting the “for test” and uncommenting the other code?

Also in this function, should the second line read: “NS_ASSERT_MSG(hAngle>=-180&&hAngle<=180, "the horizontal angle should be the range of [-180,180]");"

double
AntennaArrayModel::GetRadiationPattern (double vAngle, double hAngle)
{
	NS_ASSERT_MSG(vAngle>=0&&vAngle<=180, "the vertical angle should be the range of [0,180]");
	NS_ASSERT_MSG(hAngle>=-180&&vAngle<=180, "the vertical angle should be the range of [0,180]");
	return 1; //for testing
	/*double A_EV = -1*std::min(12*pow((vAngle-90)/65,2),30.0);
	if(hAngle != 0)
	{
		double A_EH = -1*std::min(12*pow(hAngle/65,2),30.0);
		double A = -1*std::min(-1*A_EV-1*A_EH,30.0);
		return pow(10,A/10); //convert to linear;
	}
	else
	{
		return pow(10,A_EV/10); //convert to linear;
	}*/
}

3. Finally, is the a means of making “MmWaveChannelRaytracing” real-time, as it tends to run slow?

Thank you for taking the time to read my queries

**Comment by MengleiZhang** [comment]
Hi,

1. The channel matrix model is already obsoleted by the 3GPP Channel Model, please use the later one.

2. You do not need to change the Antenna Array Model. You are right, hAngle means horizontal angle.

3. I do not know how to make it real-time.

**Comment by jq5** [comment]
brilliant, thank you for letting me know so quickly.
