### ISSUE TITLE
How to use setsector method from antenna array model.

### ISSUE THREAD

**Issue by navjotsingh963** [nyuwireless-unipd/ns3-mmwave#35]
Hello, I am trying to use setsector method from antenna array model using the program mmwave_3gpp_channel_example.cc from scratch folder, but it never goes into that or it never show sector cases in output, I think it is because of omniTx=true, it should be false to use that. How I can use that sector method or I am doing wrong. Basically, I want to create sectors and so that I can show the directionality of the antenna in particular sector using mmwave module. #31

**Comment by MengleiZhang** [comment]
The Cell scan method can be enabled by setting the following attribute to true.

  Config::SetDefault ("ns3::MmWave3gppChannel::CellScan", BooleanValue(false)); // Set true to use cell scanning method, false to use the default power method.

**Comment by navjotsingh963** [comment]
I tried making cell scan method true in mmwave-3gpp-channel-example but no change in output.

I was trying with mmwave-ue-phy.cc

	Ptr<AntennaArrayModel> antennaArray = DynamicCast<AntennaArrayModel> (GetDlSpectrumPhy ()->GetRxAntenna());
	/* set beamforming vector;
	 * for UE, you can choose 16 antenna with 0-7 sectors, or 4 antenna with 0-3 sectors
	 * input is (sector, antenna number)
	 *
	 * */
	antennaArray->SetSector (3,3);

This portion was commented when I made it uncommented it gave me these errors-

navjot@navjot-VirtualBox:~/ns3-mmwave-master$ ./waf --run scratch/diretional
Waf: Entering directory `/home/navjot/ns3-mmwave-master/build'
[1772/2341] Compiling src/mmwave/model/mmwave-ue-phy.cc
../src/mmwave/model/mmwave-ue-phy.cc: In member function ‘void ns3::MmWaveUePhy::SendDataChannels(ns3::Ptr<ns3::PacketBurst>, std::__cxx11::list<ns3::Ptr<ns3::MmWaveControlMessage> >, ns3::Time, uint8_t)’:
../src/mmwave/model/mmwave-ue-phy.cc:640:30: **_****# error: invalid conversion from ‘int’ to ‘uint8_t* {aka unsigned char*}’ [-fpermissive]_****
  **antennaArray->SetSector **(3,3);******
                              ^
In file included from ./ns3/mmwave-phy.h:42:0,
                 from ../src/mmwave/model/mmwave-ue-phy.h:32,
                 from ../src/mmwave/model/mmwave-ue-phy.cc:35:
./ns3/antenna-array-model.h:53:7: ****note:   initializing argument 2 of ‘void ns3::AntennaArrayModel::SetSector(uint8_t, uint8_t*, double)’
  void SetSector (uint8_t sector, uint8_t *antennaNum, double elevation = 90);****
       ^

**As directional antenna works on sectors I want to use this part, Is it possible to use this part if yes where else I have to make changes.**

**Thank you**

**Comment by MengleiZhang** [comment]
The cell scan method is implemented in BeamSearchBeamforming of the MmWave3gppChannel class, as mentioned in our paper.

A demonstration method BeamSearchBeamforming of the MmWave3gppChannel class currently implements a simplied beam search, based on a brute force approach, i.e., it tries all the possible BS-UT sector com- binations and selects the one that returns the maximum received power.

**Comment by navjotsingh963** [comment]
So, there is no need to use" antennaArray->SetSector (3,3); " from mmwave-ue-phy.cc it will automatically find best possible sector?

Thanks for your quick response.

Thank you.

**Comment by MengleiZhang** [comment]
No
