### ISSUE TITLE
Column header and meaning in output of mc-twoenbs.cc 

### ISSUE THREAD

**Issue by cscxxx553** [nyuwireless-unipd/ns3-mmwave#38]
Hi ,
Could you explain the column header and meaning in the following output files which are from mc-twoenbs.cc, please?
hhCellIdStatsHandover_5_10_26_03_2018_06_15_07.txt
hhDlPdcpStats_5_10_26_03_2018_06_15_07.txt
hhDlRlcStats_5_10_26_03_2018_06_15_07.txt
hhEnbHandoverEndStats_5_10_26_03_2018_06_15_07.txt
hhEnbHandoverStartStats_5_10_26_03_2018_06_15_07.txt
hhMmWaveSinrTime_5_10_26_03_2018_06_15_07.txt
hhRlcAmBufferSize_5_10_26_03_2018_06_15_07.txt
hhUeHandoverEndStats_5_10_26_03_2018_06_15_07.txt
hhUeHandoverStartStats_5_10_26_03_2018_06_15_07.txt
hhUlPdcpStats_5_10_26_03_2018_06_15_07.txt
hhUlRlcStats_5_10_26_03_2018_06_15_07.txt
hhX2Stats_5_10_26_03_2018_06_15_07.tx

Thank you!

**Comment by mychele** [comment]
Hi,
please consider this wiki page: https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces
Any feedback is appreciated.
Best,
Michele

**Comment by cscxxx553** [comment]
Thanks a million.
It took me some time to study NS3 PCAP and Tracing system that are not easy to understand and I still do not know it very well.
And I have noticed the wiki page that your provided have three more txt files that were not included in my outcome of the running the mc-twoenbs.cc :
CellIdStats.txt
MmWaveSwitchStats.txt
LteSwitchStats.txt
How could I switch the tracer on?
mmWave package download version is ns3-mmwave-new-handover.zip on 2018/3/5

**Comment by mychele** [comment]
Hi,
these are generated only if a switch between LTE and mmWave or viceversa happens. 
If you don't have them, it means that in your scenario/simulation the switch is not happening.
M

**Comment by cscxxx553** [comment]
Thank you for your help.
