### ISSUE TITLE
O2I propagation for two UEs not working?

### ISSUE THREAD

**Issue by lalexandra88** [nyuwireless-unipd/ns3-mmwave#40]
When I use MmWave3gppBuildingsPropagationLossModel and place one UE inside a building and ENB out of it everything works fine.
But, as soon as I put two UEs inside the building - I get this error message:

'build' finished successfully (5.631s)
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5
UMa scenario, channel condition is fixed to be n, h_BS=25,h_UT=1.5
**msg="indoor propagation loss not implemented yet", file=../src/mmwave/model/mmwave-3gpp-buildings-propagation-loss-model.cc, line=143**
terminate called without an active exception
Command ['/home/alra/Documents/ns3-mmwave-3GPP-channel/build/scratch/mmwave-3gpp-channel-example_random111'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

Any thoughts on why this happens?

**Comment by MengleiZhang** [comment]
Are you using the latest version? That line is already commented in the latest version.

**Comment by lalexandra88** [comment]
Thank you Menglei, after switching to new-handover it works fine.

I have one more question: I can't seem to create RxPacketTrace.txt with mmwave-tdma example from new-handover branch. I have this command:
  
MmWaveHelper->EnableTraces();

and in the mmwave-helper.cc I see that EnableDlPhyTrace and EnableUlPhyTrace were commented out. When I remove the //, I get the same RlcAmBufferSize.txt file as before.

MmWaveHelper::EnableTraces (void)
{       
     //   EnableReportPowerTrace (); ///////////////////////////////////////
	EnableDlPhyTrace ();
	EnableUlPhyTrace ();
	//EnableEnbPacketCountTrace ();
	//EnableUePacketCountTrace ();
	//EnableTransportBlockTrace ();
	EnableRlcTraces ();
	EnablePdcpTraces ();
}

Any suggestions?

**Comment by MengleiZhang** [comment]
Uncomment these 2 lines and make sure to add

MmWaveHelper->EnableTraces(); 

in the example file, then you will be able to see the other trace files.

Menglei

**Comment by lalexandra88** [comment]
I did uncomment those 2 lines but I still only get RlcAmBufferSize trace.

**Comment by MengleiZhang** [comment]
No idea then.

**Comment by mychele** [comment]
Hi, 
which example are you using?
Thanks,
Michele
