### ISSUE TITLE
Getting path loss value

### ISSUE THREAD

**Issue by ghost** [nyuwireless-unipd/ns3-mmwave#43]
Hi, Im trying to reproduce the distance-pathloss graph in the paper
"ns-3 Implementation of the 3GPP MIMO Channel Model for Frequency Spectrum above 6 GHz"
Is it possible to get the pathless value through mmwave helper ? or is there another solution?
Also when i enable the MmWave3gppChannel Log component, I can check the DoCalcRx function is called repeatedly. can you tell me where this function is being called by?
Thank you so so much!

**Comment by MengleiZhang** [comment]
Hi,

If you take a look at the src/mmwave/models/mmwave-3gpp-propagation-loss-model.cc <http://mmwave-3gpp-propagation-loss-model.cc/> line 614, uncomment these scripts and it will log the distance and propagation loss during the summation.

 https://github.com/nyuwireless-unipd/ns3-mmwave/blob/d5e7885544cf54eee5b3746fa2dafb7aa19048fb/src/mmwave/model/mmwave-3gpp-propagation-loss-model.cc#L614

**Comment by ghost** [comment]
Great! Thank you so much. I'll look more into it.
