### ISSUE TITLE
Connection between UEnodes and eNB nodes

### ISSUE THREAD

**Issue by sakib005** [nyuwireless-unipd/ns3-mmwave#48]
Hello,

While running the examples, I could not attach vehicles (UE) with the Tower/base nodes (eNB).

For example, after running the mmwave-simple-epc.cc example, I opened the output in NetAnim. You can see in the following picture the UE (Node 4) is not getting data from eNB (Node 3). I have attahced the .cc file too.

If you could let us know how to solve this issue, it would be great.

![image](https://user-images.githubusercontent.com/20683555/42702883-ceb385e4-8698-11e8-916a-69595572be2e.jpeg)

[mmwave-simple-epc.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/2193481/mmwave-simple-epc.txt)

**Comment by MengleiZhang** [comment]
I am not familiar with NetAnim, but you can see the UPD traffic from the pcap trace files.

**Comment by mychele** [comment]
Hi,
Keep in mind that, before the actual transmission happens on the mmWave
link, the packets need to be forwarded on backhaul and core links. Given
the datarate of the simulation, it may take a while with netanim to get to
the point at which you can see the packets on the mmWave link. Please also
check the other traces the simulation outputs.
Best,
Michele

Il ven 13 lug 2018, 19:07 Menglei <notifications@github.com> ha scritto:

> I am not familiar with NetAnim, but you can see the UPD traffic from the
> pcap trace files.
>

**Comment by sakib005** [comment]
Thank you for your prompt answers.

Sakib

Sakib Mahmud Khan
PhD Candidate
Transportation Cyber-Physical Systems Lab
Glenn Department of Civil Engineering
sakibk@g.clemson.edu|864-569-1082

**Comment by sakib005** [comment]
Thank you for your prompt response.

Sakib
