### ISSUE TITLE
Effect of distance between UeNodes, Remotehost and EnbNodes

### ISSUE THREAD

**Issue by sakib005** [nyuwireless-unipd/ns3-mmwave#49]
Hello, 

I am working with a mobility tracefile, and I modified the 'mmwave_epc_tdma' example. I wanted to pass one packet from one Ue to remotehost using socket, so I can record the individual packet transmission time. I found that if I have the remotehost and EndNodes very close to the UeNodes, the remotehost receives data from the Ue. Practically the cell tower could be very far from the mobile nodes. Is there any feature which would enable the data reception by the remotehost from very far (let's say 3-4 miles away).

Thanks,
Sakib

**Comment by mychele** [comment]
Hi,
given the nature of mmWaves, it is kind of challenging to achieve a very high distance between the base station and the UE (assuming this is what you want to do).
You can try with a larger number of antennas, but there are intrinsic limits given by propagation (for example, see the pathloss curves in https://arxiv.org/abs/1702.04822).
Best,
Michele

**Comment by sakib005** [comment]
Thanks
