### ISSUE TITLE
"mc-twoenbs.cc" Example; m_cellId reAssignment Failure on LTE Handover

### ISSUE THREAD

**Issue by erdemtuna** [nyuwireless-unipd/ns3-mmwave#50]
Hello everyone,

Originating from "mc-twoenbs.cc" example, I edited the scenario by creating 2 LTE eNBs, 3 mmWave cells and 1 UE with constant velocity in x-direction. LTE-enB-1 has 1 mmWave cell connected to itself while the LTE-enB-2 has 2 mmWave cells. 

I have specified LTE Handover Algorithm as `mmwaveHelper->SetAttribute ("LteHandoverAlgorithm", StringValue ("ns3::A2A4RsrqHandoverAlgorithm"));`. I can observe the handover between LTE-enB-1 and LTE-enB-2. As this handover occurs, UE stays connected to the mmWave cell under the LTE-enB-1. When outage occurs for the mmWave, handover to the LTE stack is triggered. However, the simulation tries to handover to the LTE-enB-1 instead of LTE-enB-2. Below I put some descriptive outputs for the simulation (also you can find the scratch code in the attachment). I suppose the problem is with the `m_cellID` variable in the "lte-enb-rrc.cc" but I couldn't figure out why simulation checks the wrong ID?

- Handover between LTE-enB-1 and LTE-enB-2
`
LTE-handover.txt
`

- Handover from mmWave cell to LTE-enB-2
`
[LTE-handover.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/2223485/LTE-handover.txt)
[mmWave-to-LTE-handover.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/2223486/mmWave-to-LTE-handover.txt)
[mc-twoenbs-edited.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/2223487/mc-twoenbs-edited.txt)
mmWave-to-LTE-handover.txt
`

**Comment by mychele** [comment]
Hi Erdem,
thanks for reporting this.
Unfortunately, at this moment, we do not support dual-connectivity handovers among different LTE eNBs. These are two of the items that are missing for enabling this feature:
- complete handover of the primary cell, i.e., the bearer needs to be splitted at the target LTE eNB and not at the source one
- update of the secondary RRC upon handover with the primary RRC at the UE

Please let me know if you are interested in working on this, we look forward to well-coded contributions. I can also give you some pointers.
Best,
Michele

**Comment by erdemtuna** [comment]
Hello Michele,

Thank you for the quick recap about the issue. I actually work on a research about 5G networks that involves dual-connectivity (DC) networks. In the simulation, I want to set up a network that has ability of DC among different LTEs. However, I couldn't understand the class structure of the mmWave module comprehensively (I read the papers about ns3 mmWave module beginning from the "5G mmWave Module for the ns-3 Network Simulator, 2015" up to "Integration of Carrier Aggregation and Dual Connectivity for the ns-3 mmWave Module, 2018"). 

For this reason, I'm not sure if I can handle the problem or not; but I would appreciate if you can give some more information about the steps of this development.

**Comment by mychele** [comment]
Hi,
my first advice is try to understand the events and transitions in the RRC layer. That is really at the core of the DC functionality.
Best,
Michele

**Comment by mychele** [comment]
Hi,
I am closing this issue, feel free to keep in touch with any question on this matter.
Michele
