### ISSUE TITLE
[Query] Configuration value aligning with 3GPP reference

### ISSUE THREAD

**Issue by ramki23** [nyuwireless-unipd/ns3-mmwave#59]
Hi, 

To align the mmwave functioning to 3GPP reference, how should we set the values in MMWavePhyMac Interface? .e.g.  considering 1 Radio Frame = 10 subframes = 80 slots = 10ms and 28GHz spectrum with subcarrier spacing of 120khz. 

Following are my configuration:

- "SymbolPerSlot","Number of symbols per slot",UintegerValue (30),	=> **setting to 14** 
- "SlotsPerSubframe","Number of slots in one subframe",UintegerValue (8),	=> **setting to 8**	    (considering Subcarrier spacing 120kHz)	
- "SymbolsPerSubframe","OFDM symbols per subframe",UintegerValue (24),		=> **setting to 112**   (considering Subcarrier spacing 120kHz => 8*14 = 112)
- "SubframePeriod","Symbol period in microseconds",DoubleValue (100.0),		=> **setting to 1000** microseconds (1ms) as per 3gpp reference
- "SubframePerFrame","Number of subframe per frame",UintegerValue (10),		=> setting to 10
- "SymbolPeriod","Symbol period in microseconds",DoubleValue (4.16),		=> setting this to 8.9 micro seconds 

**Following parameters are not clear in the code :**

- "SubcarriersPerChunk","Number of sub-carriers per chunk",UintegerValue (48),    => This is unclear - as per the paper it seems to be sub-band. Or should this be RBG?
- "ChunkPerRB","Number of chunks comprising a resource block",UintegerValue (72), => This is unclear 
- "ChunkWidth","Width of each chunk in Hz",DoubleValue (13.889e6),		=> This is unclear
- "ResourceBlockNum","Number of resource blocks the entire bandwidth is split into",UintegerValue (1), => This is unclear, what does this mean?
- "NumReferenceSymbols","Number of reference symbols per slot",UintegerValue (6),  => ANy reference in spec?
- "TDDPattern","The control-data pattern for TDD transmission",StringValue ("ccdddddd"), ==> Should this be as per Table 11.1.1-1 in 38.213? why is the pattern having only 8 values. Should that be 14?
- "CtrlSymbols","Number of OFDM symbols for DL control per subframe",UintegerValue (1), => Should this be aligned with on the TDD format?
- "NumRbPerRbg","Number of resource blocks per resource block group",UintegerValue (1),  => Should this be 16 as per Table 5.1.2.2.1-1 in 38.214 for 275 PRBs .		
- "GuardPeriod","Guard period for UL to DL slot transition in microseconds",DoubleValue (4.16), => 3GPP reference?
                             
Can you please suggest the values as per 3GPP for 28Ghz case?

**Comment by tommasozugno** [comment]
Hi,
the implemented schedulers follows the flex TTI structure described in [1] (Figure 6).

> "SymbolPerSlot","Number of symbols per slot",UintegerValue (30),	=> setting to 14

This value is no longer used. If you want to set a fixed number of symbols per slot you can use the SymPerSlot attribute of the schedulers.

> "SubcarriersPerChunk","Number of sub-carriers per chunk",UintegerValue (48), => This is unclear - as per the paper it seems to be sub-band. Or should this be RBG?
> "ChunkPerRB","Number of chunks comprising a resource block",UintegerValue (72), => This is unclear
> "ChunkWidth","Width of each chunk in Hz",DoubleValue (13.889e6),	=> This is unclear

From [1]: "_In the frequency domain, the entire bandwidth of 1 GHz is divided into 72 subbands of width 13.89 MHz, each composed of 48 subcarriers. It is possible to assign UE data to each of these subbands, as is done with Orthogonal Frequency-Division Multiple Access (OFDMA) in LTE, however only TDMA operation is currently supported for reasons we shall explain shortly._"

> "ResourceBlockNum","Number of resource blocks the entire bandwidth is split into",UintegerValue (1), => This is unclear, what does this mean?

The RB is the smallest unit of time-frequency resources that can be allocated to a user, it is ChunkPerRB*ChunkWidth in frequency and 1 slot in time. In this case only TDMA is supported, then each RB cover the entire system bandwidth (ResourceBlockNum=1).

> "NumReferenceSymbols","Number of reference symbols per slot",UintegerValue (6), => ANy reference in spec?
> "TDDPattern","The control-data pattern for TDD transmission",StringValue ("ccdddddd"), ==> Should this be as per Table 11.1.1-1 in 38.213? why is the pattern having only 8 values. Should that be 14?

This value is not used.

> "CtrlSymbols","Number of OFDM symbols for DL control per subframe",UintegerValue (1), => Should this be aligned with on the TDD format?

Currently this value is not used in the code. To get the number of DL/UL ctrl symbols, GetDlCtrlSymbols() and GetUlCtrlSymbols() methods are used.

> "NumRbPerRbg","Number of resource blocks per resource block group",UintegerValue (1), => Should this be 16 as per Table 5.1.2.2.1-1 in 38.214 for 275 PRBs .

It depends on the bandwidth.

> "GuardPeriod","Guard period for UL to DL slot transition in microseconds",DoubleValue (4.16), => 3GPP reference?

This is a simulation parameter.

Best,
Tommaso

[1] "End-to-End Simulation of 5G mmWave Networks", Marco Mezzavilla, Menglei Zhang, Michele Polese, Russell Ford, Sourjya Dutta, Sundeep Rangan, Michele Zorzi (https://arxiv.org/abs/1705.02882)

**Comment by ramki23** [comment]
Hi  , 

Referring to your clarification:
> The RB is the smallest unit of time-frequency resources that can be allocated to a user, it is ChunkPerRB*ChunkWidth in frequency and 1 slot in time. In this case only TDMA is supported, then each RB cover the entire system bandwidth (ResourceBlockNum=1).

I am trying to interpret the "symbol#" in "RxPacketTrace.txt" when I run "mmwave-epc-tdma.cc". So when the traces indicate "symbol#" as 8, then I understand -  in that slot, scheduler has allocated 8 symbols (out of total 48384 symbols) to RNTI=1. Is that correct?

The default mmwave configuration is assumed ==> subcarriersperChunk =48, ChunkperRB=72 and ResourceBlockNum =1, Hence total number of symbols per slot = 14symbols per slot x 48 x 72 = 48384 symbols.

Also kindly note that the low value of SINR in the attached trace was due to UE distance (of 300m) from BTS - Intentionally done to check the range. 
![mmwave resource allocation](https://user-images.githubusercontent.com/43127369/46197836-89a1f180-c328-11e8-80ae-f06331f837e7.png)


Thanks, 
Ramakrishnan
> Hi,
> the implemented schedulers follows the flex TTI structure described in [1] (Figure 6).
> 
> > "SymbolPerSlot","Number of symbols per slot",UintegerValue (30),	=> setting to 14
> 
> This value is no longer used. If you want to set a fixed number of symbols per slot you can use the SymPerSlot attribute of the schedulers.
> 
> > "SubcarriersPerChunk","Number of sub-carriers per chunk",UintegerValue (48), => This is unclear - as per the paper it seems to be sub-band. Or should this be RBG?
> > "ChunkPerRB","Number of chunks comprising a resource block",UintegerValue (72), => This is unclear
> > "ChunkWidth","Width of each chunk in Hz",DoubleValue (13.889e6),	=> This is unclear
> 
> From [1]: "_In the frequency domain, the entire bandwidth of 1 GHz is divided into 72 subbands of width 13.89 MHz, each composed of 48 subcarriers. It is possible to assign UE data to each of these subbands, as is done with Orthogonal Frequency-Division Multiple Access (OFDMA) in LTE, however only TDMA operation is currently supported for reasons we shall explain shortly._"
> 
> > "ResourceBlockNum","Number of resource blocks the entire bandwidth is split into",UintegerValue (1), => This is unclear, what does this mean?
> 
> The RB is the smallest unit of time-frequency resources that can be allocated to a user, it is ChunkPerRB*ChunkWidth in frequency and 1 slot in time. In this case only TDMA is supported, then each RB cover the entire system bandwidth (ResourceBlockNum=1).
> 
> > "NumReferenceSymbols","Number of reference symbols per slot",UintegerValue (6), => ANy reference in spec?
> > "TDDPattern","The control-data pattern for TDD transmission",StringValue ("ccdddddd"), ==> Should this be as per Table 11.1.1-1 in 38.213? why is the pattern having only 8 values. Should that be 14?
> 
> This value is not used.
> 
> > "CtrlSymbols","Number of OFDM symbols for DL control per subframe",UintegerValue (1), => Should this be aligned with on the TDD format?
> 
> Currently this value is not used in the code. To get the number of DL/UL ctrl symbols, GetDlCtrlSymbols() and GetUlCtrlSymbols() methods are used.
> 
> > "NumRbPerRbg","Number of resource blocks per resource block group",UintegerValue (1), => Should this be 16 as per Table 5.1.2.2.1-1 in 38.214 for 275 PRBs .
> 
> It depends on the bandwidth.
> 
> > "GuardPeriod","Guard period for UL to DL slot transition in microseconds",DoubleValue (4.16), => 3GPP reference?
> 
> This is a simulation parameter.
> 
> Best,
> Tommaso
> 
> [1] "End-to-End Simulation of 5G mmWave Networks", Marco Mezzavilla, Menglei Zhang, Michele Polese, Russell Ford, Sourjya Dutta, Sundeep Rangan, Michele Zorzi (https://arxiv.org/abs/1705.02882)

**Comment by tommasozugno** [comment]
Hi,
If you use the default values, each frame contains 10 subframes and each subframe contains 24 symbols (*). The first and the last symbols of each subframe (index 0 and index 23) are reserved for DL and UL CTRL, respectively, while the others are used for DL and UL DATA. All the available schedulers follow the flex TTI frame structure described in the paper, in which a variable number of DL and UL DATA symbols are allocated to each user. 

> So when the traces indicate "symbol#" as 8, then I understand - in that slot, scheduler has allocated 8 symbols (out of total 48384 symbols) to RNTI=1. Is that correct?

1stSym is the index of the first allocated symbol within the specified subframe while symbol# is the number of allocated symbols (out of 24).
For instance, the first row of the trace file you attached says that symbols 1 to 22 of subframe 6 have been allocated to RNTI 1 for DL DATA.

(*) You can configure the number of symbols per subframe and the number of subframes per frame using the SymbolsPerSubframe and SubframePerFrame attributes.

Best,
Tommaso
