### ISSUE TITLE
[Dual Connectivity] RLC buffer forwarding and PDCP reordering

### ISSUE THREAD

**Issue by MengleiZhang** [nyuwireless-unipd/ns3-mmwave#63]
1> I observed packet losses in uplink when the traffic is switching between mmWave and LTE. Is the RCL buffer forwarding function only for downlink?

2> I am trying to implement re-ordering at the PDCP layer, is there any references?

Menglei

**Comment by MengleiZhang** [comment]
For question 1. I found out the PDCP packets were not missing, RLC just removed the original PDCP header and added a new one with new sequence number.

Menglei

**Comment by MengleiZhang** [comment]
While study the UlPdcpStats.txt, sometime there is a single PDCP packets generates huge delay (several seconds) when the user is switched from mmWave to LTE.  The reason is from the file Lte-ue-rrc.cc line 1686-1692, as following.

 Ptr<Packet> segmentedRlcsdu = rlcAm->GetSegmentedRlcsdu();
        if (segmentedRlcsdu != NULL){
          segmentedRlcsdu->PeekHeader(pdcpHeader);
          NS_LOG_DEBUG(this << "UE RRC: SegmentedRlcSdu = " << segmentedRlcsdu->GetSize() << " SEQ = " << pdcpHeader.GetSequenceNumber());
          //insert the complete version of the fragmented SDU to the front of txonBuffer.
          txonBuffer.insert(txonBuffer.begin(),segmentedRlcsdu);
        }

There is an "old" PDCP packet copied to the txonBuffer. Why you keep this PDCP packet? If this PDCP packet is necessary, I suggest to remove the pdcpTag and do not include it in the latency measurement.
Menglei

**Comment by mychele** [comment]
Hi Menglei,
for 2), you could take a look at TS 36.323 for LTE (or 38.323 for NR).
As for your question on the delayed packet, for completely lossless HO you would need to transfer all the packets that have been transmitted but not ACKed (such as this segment) and those that have been NACKed. PDCP reordering could be useful to filter out on the receiving side those that have already been received.
Best,
Michele

**Comment by wanghui19960311** [comment]
I observed packet losses in uplink when the traffic is switching between mmWave and LTE. But I cannot find the received packets
