### ISSUE TITLE
mmwave_clarification_multiconnectivity

### ISSUE THREAD

**Issue by ediblb** [nyuwireless-unipd/ns3-mmwave#65]
hi,
as far as I understand there is an algorithm that choses the best direction(max gain) for each pair gnb-ue,instead is it possible to change the amplitude of the beam or is it costant?
thanks in advance

**Comment by mychele** [comment]
Hi,
you cannot directly control the amplitude of the beam.
You can change the number of antennas at the UE and the base station, this will impact the overall beamforming gain.
Michele

**Comment by ediblb** [comment]
ok thanks
