### ISSUE TITLE
Mmwave amc test TBS calculation  and writing on RxPacketTrace.txt correctly acoording to 3GPP 5G NR specs

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#73]
Hi all,
I am working on adapting ns-3 mmwave module for 5G NR according to the 3GPP specs. Now, my concern is to get the new TBS values by running mmwave-amc-test.cc example script after changing the tables on the mmwave-amc.cc file according to 3GPP TS 38.214. After GetTbSizeFromMcsSymbols code in mmwave-amc.cc  (line 185) I added a cout and observed the TBS value as I expected. On the contrary, the tbs values on the RxPacketTrace.txt is different. I changed maxtbsize value on phy-mac-common.cc  (from 0x7FFF to 0x7FFFF )  and run again the example, but nothing changed. Also, I could not exactly trace the path how RxPacketTrace reads the tbSize values. My questions are:
1.) What should I change on the code to get correct values on RxPacketTrace file ?
2.)What is the reason for using different functions to calculate the tbs values in mmwave-amc.cc (GetTbszieFromMcsSymbols or GetTbSizeFromMcs) 
3.) A general question; regarding facilitation of the debugging process, which branch do you recommend for me to work on?

Thanks in advance,
Furkan

**Comment by tommasozugno** [comment]
Hi Furkan!
> 1.) What should I change on the code to get correct values on RxPacketTrace file ?

Which scheduler are you using? Did you try to enable the logs for the scheduler and to check the TB size there? Notice that the value returned by GetTbSizeFromMcsSymbols is in bits while the one in RxPacketTrace.txt is in bytes.

> 2.)What is the reason for using different functions to calculate the tbs values in mmwave-amc.cc (GetTbszieFromMcsSymbols or GetTbSizeFromMcs)

Currently only GetTbsizeFromMcsSymbols is used.

> 3.) A general question; regarding facilitation of the debugging process, which branch do you recommend for me to work on?

Please use the new-handover branch.

Best, 
Tommaso

**Comment by Faydin94** [comment]
Thanks for your fast response. I am using MmwaveFlexTtiMacScheduler. After made bit to byte conversion I solved the problem, thanks.
Yet, my purpose is to change the values on the table 1 of the end to end simulation of the 5G mmwave networks to adapt this module according to the 5G specs and I could not get the expected results. 
For example, I changed the subframe length from 100 us to 1 ms, and also the symbol length and symbolspersubframe (8.9 us and 112) and TBS value nearly does not change. What could be the reason?
Regards, Furkan

**Comment by tommasozugno** [comment]
Hi, 
Could you please provide us with the script you are using for your simulations?

Best,
Tommaso

**Comment by FurkanAydin2018** [comment]
I've only changed the parameters below in mmwave phy-mac-common.cc . Rest is the same with the mmwave-amc-test according to the comparison with head revision.  
MmWavePhyMacCommon::MmWavePhyMacCommon ()
 //m_symbolsPerSlot (14),
: m_symbolPeriod (4.16),
  m_symbolsPerSubframe (24),
  m_subframePeriod (120.0),
  m_ctrlSymbols (2),
  m_dlCtrlSymbols (1),
  m_ulCtrlSymbols (1),
  //m_slotsPerSubframe (8),
  m_subframesPerFrame (10),
  m_numRefSymbols (6),
	m_numRbPerRbg (1),
  m_numSubCarriersPerChunk (48),
  m_chunksPerRb (72),
  m_numRefScPerRb (6),
  m_numRefScPerSym (792),
  m_chunkWidth (1.44e6),
  m_numRb (1),
  m_numHarqProcess (20),
  m_harqTimeout (20),
  m_centerFrequency (28e9),
  m_guardPeriod (4.16),
  m_l1L2CtrlLatency (2),
  m_l1L2DataLatency (2),
  m_ulSchedDelay (1),
	m_wbCqiPeriodUs (500),
	m_tbDecodeLatencyUs (100.0),
	m_maxTbSizeBytes (0x7FFF)

**Comment by Faydin94** [comment]
I've only changed the values below in the mmwave phy-mac-common.cc. According to the comparison with the head revision rest is the same in the mmwave-amc-test.cc. 

 //m_symbolsPerSlot (14),
: m_symbolPeriod (8.9),
  m_symbolsPerSubframe (112),
  m_subframePeriod (1000.0),
  m_ctrlSymbols (2),
  m_dlCtrlSymbols (1),
  m_ulCtrlSymbols (1),
  //m_slotsPerSubframe (8),
  m_subframesPerFrame (10),
  m_numRefSymbols (6),
	m_numRbPerRbg (1),
  m_numSubCarriersPerChunk (12),
  m_chunksPerRb (264),
  m_numRefScPerRb (6),
  m_numRefScPerSym (792),
  m_chunkWidth (1.44e6),
  m_numRb (1),
  m_numHarqProcess (20),
  m_harqTimeout (20),
  m_centerFrequency (28e9),
  m_guardPeriod (8.9),
  m_l1L2CtrlLatency (2),
  m_l1L2DataLatency (2),
  m_ulSchedDelay (1),
	m_wbCqiPeriodUs (500),
	m_tbDecodeLatencyUs (100.0),
	m_maxTbSizeBytes (0x7FFF)

**Comment by Faydin94** [comment]
I figured out that I've also changed the SINR range  (from 15 dB to 25 dB since my purpose is to get max tbs values.) When I ran again the example in the -7 dB- 30 dB range I observed tbs values change much. So, it seems that tbs value changes but the limit on its max values is settled to uint16_t (65536) and it mislead me.   I changed the maxTbSizeBytes value to uint32_t but result is the same. How can I change  the limit of this value? Which parameters in which files should I change?
Best, Furkan.

**Comment by tommasozugno** [comment]
Be sure that the values of the parameters are those you actually set, you should configure them using the ns-3 [attribute system](https://www.nsnam.org/docs/manual/html/attributes.html) (`Config::SetDefault ("ns3::MmWavePhyMacCommon::AttributeName", Value() `);
).

**Comment by Faydin94** [comment]
I've used attribute system and set the parameters. Test worked as I expect. Yet, in the RxPacketTrace.txt file tbSize values has a limit - I believe uint16_t in somewhere of the mmwave-phy-rx-trace.cc - and the value does not increase after around 65000, it just starts from zero. I have tried to changed all tbsize types to uint32_t, but nothing changed. How can I increase the limit in that script, which parameters and data types should I change?     
Thanks

**Comment by MengleiZhang** [comment]
Can you try to update the following functions. Let us know if the problem
is still not resolved.

Menglei

**Comment by mychele** [comment]
@MengleiZhang which functions?

**Comment by Faydin94** [comment]
Finally, I solved my problem. In RxPacketTrace.cc file I put a cout after the line : 

_fprintf (log_file, "%lld \t %llu \n",(long long int) Now().GetMicroSeconds (), (long long unsigned) tbSize);_

and I saw that tbSize  was introduced in uint64_t and prints the values greater than 65535 while the tbSize in the below line introduced as uint32_t and can not pass 65535:

_m_rxPacketTraceFile << "DL\t" << params.m_frameNum << "\t" << (unsigned)params.m_sfNum << "\t" << (unsigned)params.m_symStart
			<< "\t" << (unsigned)params.m_numSym << "\t" << params.m_cellId
			<< "\t" << params.m_rnti << "\t" << params.m_tbSize << "\t" << (unsigned)params.m_mcs << "\t" << (unsigned)params.m_rv << "\t"
			<< 10*log10(params.m_sinr) << "\t\t" << params.m_corrupt <<"\t" << params.m_tbler << std::endl;_
 
   After I changed all tbSize and related data types to uint64_t the limitation, problem disappeared. What could be reason for this? Did you mean something related with this issue by saying updating the functions?
Regards, Furkan

**Comment by MengleiZhang** [comment]
Hi,

As shown in the attached figure in the previous email,

1> in function AddExpectedTb (), the input size should change to uint32_t.
2> In expectedTbInfo_t struct, the size parameter should change to uint32_t.

Menglei

**Comment by mychele** [comment]
Hi @Faydin94,
we pushed a fix in https://github.com/nyuwireless-unipd/ns3-mmwave/commit/469e416e359f533e07897c241bcb8e7463e8a6db
Can you try it?
We would also be curious to try the tables that you set in mmwave-amc.cc - would you like to prepare a pull request with that updated code?
Thanks,
Michele

**Comment by Faydin94** [comment]
Hi Michelle,
Since I have faced with some problems with the new handover branch, I was working with master branch. Hence, there are several differences in these branch. So, I committed the updated code. By the way, updated code is work well. 
Regards, Furkan

**Comment by mychele** [comment]
Hi,
the master branch is not up-to-date with the current development.
Which issues do you have?

**Comment by Faydin94** [comment]
I was getting more than 40 errors for mmwave-amc-test (not for all examples). Also, the branch was not creating the RxPacketTrace file which was main focus of mine. After I switched to the master branch these issues are disappeared.

**Comment by mychele** [comment]
Hi, 
thanks for reporting this.
We fixed the issue that was preventing mmwave-amc-test from logging the packets in RxPacketTrace in #79. 
We are not experiencing errors with mmwave-amc-test, though. 
Michele
