### ISSUE TITLE
Mmwave Content of Examples & Applicable Scenarios   

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#84]
Hi, 
Is there any tutorial which explains the contents of the examples in terms of their scenarios,limitations such as which of them enables multi user tests or which of them offer mobile UE scenarios etc.
Thanks in advance,
Furkan

**Comment by tommasozugno** [comment]
Hi,
Most of them are described here https://arxiv.org/pdf/1705.02882.pdf

Best,
Tommaso

**Comment by Faydin94** [comment]
Thanks

10 Ara 2018 Pzt 19:24 tarihinde tommasozugno <notifications@github.com>
şunu yazdı:
