### ISSUE TITLE
SINR change for LOS & NLOS States for MmWave Examples

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#85]
Hı,
For both mmwave-epc-tdma and mmwave-simple-epc examples, SINR values are not decreasing when I ran the examples in LOS or NLOS cases(In these examples UE have minimum distance with eNB and it is getting away from eNB ). For simple-epc example SINR changes as in below. Is it an expected result or wrong? If ıt ıs normal could you explain the reason?
Regards,
Furkan 

![samples from simple-epc rxpackettrace](https://user-images.githubusercontent.com/44889685/49809593-5d671000-fd70-11e8-86f9-4d91aafc3a01.png)

**Comment by tommasozugno** [comment]
Hi, 
How do you change the channel condition (LOS/NLOS)? You should consider a larger time interval or you should try to increase the value of `minDistance` in `mmwave-simple-epc`. 

Best,
Tommaso

**Comment by Faydin94** [comment]
Hi,
I ran the example for LOS case. I think the reason is because the "distrv" random parameter which both examples include (lines 174-177 for simple-epc and lines 185-189 for epc-tdma). That parameter chooses distance randomly not in increasing order. For my purpose, how can I change that parameter so that distance have an increasing path?
Best,
Furkan

**Comment by tommasozugno** [comment]
Hi,
Yes, you are right. If you want the UEs moving away from the gNB with a constant speed you can use the [ConstantVelocityMobilityModel](https://www.nsnam.org/doxygen/classns3_1_1_constant_velocity_mobility_model.html). Additionally, you should set a fixed value for `dist`, in such a way that the initial position of the UEs is not random.

Best,
Tommaso

**Comment by Faydin94** [comment]
Thanks,
Furkan
