### ISSUE TITLE
Mmwave-simple-building-obstacle UL-DL mcs value problem

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#86]
Hi, 
I am working on mmwave-simple-building-obstacle example. For different UE velocity values I ran the example. For all cases UL mcs and hence tbsize values are greater than those of DL even the SINR values are the same (as you can see on figure). What is the reason for this? If you are using a table to assign mcs values for SINR ranges, where can I find it?
Regards,
Furkan    
                                                                                                    
![simple building obstacle samples](https://user-images.githubusercontent.com/44889685/50163298-38831780-02f1-11e9-815f-9196c6e23227.PNG)

**Comment by tommasozugno** [comment]
Hi,
This is weird, I tried with other examples but I did not find any relevant difference. What is the speed of the UE you are considering in this case?

The MCS is computed in the scheduler using the methods `GetMcsFromCqi ()` and `CreateCqiFeedbackWbTdma ()` of the `MmWaveAmc` class. For instance, in `MmWaveFlexTtiMacScheduler` is computed here for the DL https://github.com/nyuwireless-unipd/ns3-mmwave/blob/7c25c1b91d005374746c1529a3bed5beb849a455/src/mmwave/model/mmwave-flex-tti-mac-scheduler.cc#L1008 and here for the UL https://github.com/nyuwireless-unipd/ns3-mmwave/blob/7c25c1b91d005374746c1529a3bed5beb849a455/src/mmwave/model/mmwave-flex-tti-mac-scheduler.cc#L1084

Best,
Tommaso

**Comment by Faydin94** [comment]
I ran the example firstly with default velocity values and then with (0,30,0),(0,10,0),(0,0,0) values. The results are as I mentioned before. Now, I build a new-handover branch from scratch. After ran the example, I saw that 
for UL: SINR=2.90 dB  mcs=9  tbs=3617  
for DL: SINR=3.87 dB  mcs=8 and tbs=3118 
Could it be a mapping problem only for this example for DL or UL?
Best,
Furkan

**Comment by tommasozugno** [comment]
Hi Furkan,

This is because the average SINR value that you see in the trace is the one measured at the time when the TB transmission takes place, while the MCS value is the one that has been computed by the scheduler when the transmission was scheduled.

Best,
Tommaso

**Comment by Faydin94** [comment]
Hı,
I see your point, thanks. Then, how can I trace SINR for comparison of DL and UL cases in synchronized manner. Does any shifting operation in time does handle the problem?
Best,
Furkan

**Comment by tommasozugno** [comment]
Hi,

You can use the LOG messages of the `MmWaveAmc` or the `MmWaveFlexTtiMacScheduler` classes.

Best,
Tommaso

**Comment by Faydin94** [comment]
Thanks
