### ISSUE TITLE
mmwave module fail to build

### ISSUE THREAD

**Issue by LunaBaoBao** [nyuwireless-unipd/ns3-mmwave#90]
version: ns3-mmwave-new-handover

macOS High Sierra/version 10.13.6

Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

after typing ./waf,  getting the following error

Waf: Leaving directory `/Users/username/tarballs/ns3-mmwave-new-handover/build'
Build failed
 -> task in 'mmwave-ca-diff-bandwidth' failed with exit status 1 (run with -v to display more information)

typing ./waf -v, getting this

Build failed
 -> task in 'mmwave-ca-diff-bandwidth' failed with exit status 1: 
	{task 4576837456: cxx mmwave-ca-diff-bandwidth.cc -> mmwave-ca-diff-bandwidth.cc.15.o}
['/usr/local/opt/llvm/bin/clang++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-unused-local-typedefs', '-Wno-potentially-evaluated-expression', '-std=c++11', '-I.', '-I..', '-I/usr/include/libxml2', '-DNS3_BUILD_PROFILE_DEBUG', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_SQLITE3=1', '../src/mmwave/examples/mmwave-ca-diff-bandwidth.cc', '-c', '-o/Users/username/tarballs/ns3-mmwave-new-handover/build/src/mmwave/examples/mmwave-ca-diff-bandwidth.cc.15.o']

**Comment by tommasozugno** [comment]
Hi, 
There may be some issues with macOS, please try with a linux distro (I'm using Ubuntu 16.04).
We will check this ASAP.

Best,
Tommaso
