### ISSUE TITLE
Generating DlPdcpStats

### ISSUE THREAD

**Issue by ermyyusnia** [nyuwireless-unipd/ns3-mmwave#91]
Hello,

I currently running a simulation using mmwave-epc-tdma.cc script and i want to analyze realtime video using an Evalvid module (https://gitlab.com/gercom/evalvid-ns3/) but when i add the evalvid script to the "Install and start applications on UEs and remote host" part, the DlPdcpStats isn't generated. My question is, which part of the script that generates the DlPdcpStats? I'll attach my script.

Thank you!

Regards,
Ermy
[videoscript.txt](https://github.com/nyuwireless-unipd/ns3-mmwave/files/2785795/videoscript.txt)

**Comment by tommasozugno** [comment]
Hi,
The McUe/EnbPdcp classes fire a callback each time a PDCP PDU is sent or received. These callbacks are connected to the methods Dl/UlRxPdu and Dl/UlTxPdu of the class MmWaveBearerStatsCalculator and the connection is handled by MmWaveBearerStatsConnector.

First you should try to enable the McUe/EnbPdcp logs and see if you are actually transmitting/receiving DL packets.
Let us know :)

Best,
Tommaso

**Comment by rezapoorzare** [comment]
Dear Tommaso, 
I am new in ns3mmwave and I am trying to understand the generated results.
what are the different columns in the generated files? let's start with DlPdcpStats.txt. The first column is the time what are the others?
Thanks a lot

**Comment by tommasozugno** [comment]
Hi, all the trace files are described here https://github.com/nyuwireless-unipd/ns3-mmwave/wiki/ns3-mmWave-traces

**Comment by rezapoorzare** [comment]
Dear Tommaso,
Thanks a millionnnn.
