### ISSUE TITLE
Scheduler and Parameter

### ISSUE THREAD

**Issue by nadiramumtaz08** [nyuwireless-unipd/ns3-mmwave#92]
Hello,

I'd like to ask about the implementation of MR and EDF algorithm.
1. On "End-to-End Simulation of 5G mmWave Networks" paper, you stated that  "The Maximum Rate policy realized in the MmWaveFlexTtiMrMacScheduler class schedules only the users with the highest SINRs to maximize cell throughput", my question is, what is the threshold for the SINR in this system?
2. "The MmWave-FlexTtiEdfMacScheduler class implements an Earliest Deadline First policy, which is a priority queue-based policy that weighs flows by their relative deadlines for packet delivery", the question is where can i find the information about this deadline for each packet?
3. On which script can we find that this simulation is using the 28 GHz frequency and 1 Gbps bandwidth?
Thank you.

Best,
Nadira

**Comment by tommasozugno** [comment]
Hi Nadira,
I'm not the one who implemented these mac schedulers but I will try to answer anyway.
1. The `MmWaveFlexTtiMaxRateMacScheduler` tries to serve all the users starting from those with higher MCS. If the TB size is big enough all the users will be served
2. The deadline depends on the QoS class of the bearer whose packets belong to. This deadline is set in the method `DoCschedLcConfigReq` and its value depends on the packet delay budget associated to the bearer. As you can see from the implementation of this method the scheduler works only using bearers of type `EpsBearer::NGBR_LOW_LAT_EMBB_AR`
3. In the class `MmWavePhyMacCommon`

Best,
Tommaso
