### ISSUE TITLE
Problem on DL and UL Throughput plots of Simple Building Obstacle Scenarios

### ISSUE THREAD

**Issue by Faydin94** [nyuwireless-unipd/ns3-mmwave#93]
Hi,
I am trying to get DL and UL plots of simple building obstacle scenario for different positions of UEs and eNBs. I build three different scenarios with 4 eNBs and 5 UEs which I gave positions of them first attach. I was expecting higher throughput performance as congestion decreases. For DL it nearly holds but for UL results differ. I attached two figures. 
What could be the reason? Is there any better scenario to clearly verify this? (I used 3gpp channel and 3gpp propagationloss model)

Best, Furkan   

![ue and enb positions](https://user-images.githubusercontent.com/44889685/51823826-942dc100-22f1-11e9-8b60-b1869769662d.png)
![dl cdf](https://user-images.githubusercontent.com/44889685/51823834-9a23a200-22f1-11e9-9df1-1218ac646a4c.png)
![ul cdf](https://user-images.githubusercontent.com/44889685/51823844-9e4fbf80-22f1-11e9-8802-5f51ec735e72.png)

**Comment by tommasozugno** [comment]
Hi Furkan,
It may depends from many different factors, could you please provide the simulation script and the parameters you are using? Are you computing the throughput at the application layer?

Best, 
Tommaso
