### ISSUE TITLE
whether can support digital beamforming or hybrid beamforming ?

### ISSUE THREAD

**Issue by LegendBC** [nyuwireless-unipd/ns3-mmwave#99]
Hi!
Thanks for your great simulator! I'm doing my project on mmwave module. But I have some questions.
whether it can support digital beamforming or hybrid beamforming ? If the answer is yes, where can I set the beamforming mode?

**Comment by tommasozugno** [comment]
Hi, 
No, only analog beamforming is supported.

Best,
Tommaso
